// @generated by protoc-gen-es v2.11.0
// @generated from file m8/platform/iam/v1/authentication_assurance_level.proto (package m8.platform.iam.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file m8/platform/iam/v1/authentication_assurance_level.proto.
 */
export declare const file_m8_platform_iam_v1_authentication_assurance_level: GenFile;

/**
 * Authentication assurance level required or achieved by an authentication flow.
 *
 * @generated from enum m8.platform.iam.v1.AuthenticationAssuranceLevel
 */
export enum AuthenticationAssuranceLevel {
  /**
   * Authentication assurance level is not specified.
   *
   * @generated from enum value: AUTHENTICATION_ASSURANCE_LEVEL_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * AAL0 means no authenticated user assurance has been established.
   *
   * Example:
   * - anonymous request before primary authentication
   * - public client flow before user interaction
   * - policy evaluation that has not yet selected an authentication requirement
   *
   * @generated from enum value: AUTHENTICATION_ASSURANCE_LEVEL_AAL0 = 1;
   */
  AAL0 = 1,

  /**
   * AAL1 provides basic assurance that the claimant controls an authenticator.
   *
   * Example:
   * - single-factor password authentication
   * - one-time password sent to a registered email address
   * - low-risk access where basic authentication is sufficient
   *
   * @generated from enum value: AUTHENTICATION_ASSURANCE_LEVEL_AAL1 = 2;
   */
  AAL1 = 2,

  /**
   * AAL2 provides high confidence through multi-factor authentication.
   *
   * Example:
   * - password plus one-time password
   * - password plus push approval
   * - passkey or WebAuthn authentication used as a phishing-resistant factor
   *
   * @generated from enum value: AUTHENTICATION_ASSURANCE_LEVEL_AAL2 = 3;
   */
  AAL2 = 3,

  /**
   * AAL2_PLUS provides AAL2 assurance with additional local requirements.
   *
   * Example:
   * - AAL2 with a phishing-resistant factor preferred by policy
   * - AAL2 with transaction binding for a sensitive operation
   * - AAL2 with a trusted managed device requirement
   *
   * @generated from enum value: AUTHENTICATION_ASSURANCE_LEVEL_AAL2_PLUS = 4;
   */
  AAL2_PLUS = 4,

  /**
   * AAL3 provides very high confidence with phishing-resistant authentication.
   *
   * Example:
   * - hardware-backed WebAuthn credential with verifier impersonation resistance
   * - high-risk operation requiring the strongest available authenticator
   * - privileged access requiring proof of possession of a strong authenticator
   *
   * @generated from enum value: AUTHENTICATION_ASSURANCE_LEVEL_AAL3 = 5;
   */
  AAL3 = 5,
}

/**
 * Describes the enum m8.platform.iam.v1.AuthenticationAssuranceLevel.
 */
export declare const AuthenticationAssuranceLevelSchema: GenEnum<AuthenticationAssuranceLevel>;

