// @generated by protoc-gen-es v2.11.0
// @generated from file m8/platform/iam/v1/authentication_resource_context.proto (package m8.platform.iam.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { AuthenticationChallenge } from "./authentication_challenge_pb";

/**
 * Describes the file m8/platform/iam/v1/authentication_resource_context.proto.
 */
export declare const file_m8_platform_iam_v1_authentication_resource_context: GenFile;

/**
 * TenantContext identifies tenant boundary references for assurance evaluation and audit.
 * Resource Manager remains the source of truth for tenant and resource hierarchy.
 *
 * Example:
 * - tenant id used to load authentication requirements
 * - realm used by an authorization server
 * - region used for data residency routing
 *
 * @generated from message m8.platform.iam.v1.TenantContext
 */
export declare type TenantContext = Message<"m8.platform.iam.v1.TenantContext"> & {
  /**
   * Stable tenant identifier.
   *
   * @generated from field: string tenant_id = 1;
   */
  tenantId: string;

  /**
   * Stable organization identifier when different from tenant id.
   *
   * @generated from field: string organization_id = 2;
   */
  organizationId: string;

  /**
   * Authorization realm or tenant realm.
   *
   * @generated from field: string realm = 3;
   */
  realm: string;

  /**
   * Region where tenant requirements and data residency should be evaluated.
   *
   * @generated from field: string region = 4;
   */
  region: string;

  /**
   * Isolation domain for multi-tenant routing.
   *
   * @generated from field: string isolation_domain = 5;
   */
  isolationDomain: string;

  /**
   * Runtime environment such as prod, stage, or dev.
   *
   * @generated from field: string environment = 6;
   */
  environment: string;

  /**
   * Additional non-sensitive tenant attributes.
   *
   * @generated from field: map<string, string> attributes = 7;
   */
  attributes: { [key: string]: string };
};

/**
 * Describes the message m8.platform.iam.v1.TenantContext.
 * Use `create(TenantContextSchema)` to create a new message.
 */
export declare const TenantContextSchema: GenMessage<TenantContext>;

/**
 * ClientContext describes the client requesting authentication.
 * Resource Manager remains the source of truth for client configuration and lifecycle.
 *
 * Example:
 * - public mobile application
 * - confidential server-side web application
 * - first-party back-office client
 *
 * @generated from message m8.platform.iam.v1.ClientContext
 */
export declare type ClientContext = Message<"m8.platform.iam.v1.ClientContext"> & {
  /**
   * OAuth or platform client identifier.
   *
   * @generated from field: string client_id = 1;
   */
  clientId: string;

  /**
   * Client type used for authentication assurance selection.
   *
   * @generated from field: m8.platform.iam.v1.ClientType type = 2;
   */
  type: ClientType;

  /**
   * Trust level assigned to the client.
   *
   * @generated from field: m8.platform.iam.v1.ClientTrustLevel trust_level = 3;
   */
  trustLevel: ClientTrustLevel;

  /**
   * Display name safe for audit and decision explanations.
   *
   * @generated from field: string display_name = 4;
   */
  displayName: string;

  /**
   * Application identifier when separate from client id.
   *
   * @generated from field: string application_id = 5;
   */
  applicationId: string;

  /**
   * Redirect URI requested by the client.
   *
   * @generated from field: string redirect_uri = 6;
   */
  redirectUri: string;

  /**
   * Whether the client is first-party.
   *
   * @generated from field: bool first_party = 7;
   */
  firstParty: boolean;

  /**
   * Whether the client authenticates as a confidential client.
   *
   * @generated from field: bool confidential = 8;
   */
  confidential: boolean;

  /**
   * Challenges allowed for this client.
   *
   * @generated from field: repeated m8.platform.iam.v1.AuthenticationChallenge allowed_challenges = 9;
   */
  allowedChallenges: AuthenticationChallenge[];

  /**
   * Additional non-sensitive client attributes.
   *
   * @generated from field: map<string, string> attributes = 10;
   */
  attributes: { [key: string]: string };
};

/**
 * Describes the message m8.platform.iam.v1.ClientContext.
 * Use `create(ClientContextSchema)` to create a new message.
 */
export declare const ClientContextSchema: GenMessage<ClientContext>;

/**
 * TransactionContext describes the protected operation for transaction-aware authentication decisions.
 * M8 Access remains responsible for deciding whether the subject may perform the operation.
 *
 * Example:
 * - transfer money to a counterparty
 * - update a privileged security setting
 * - access a sensitive resource
 *
 * @generated from message m8.platform.iam.v1.TransactionContext
 */
export declare type TransactionContext = Message<"m8.platform.iam.v1.TransactionContext"> & {
  /**
   * Operation name or category.
   *
   * @generated from field: string operation = 1;
   */
  operation: string;

  /**
   * Resource affected by the operation.
   *
   * @generated from field: m8.platform.iam.v1.ResourceRef resource = 2;
   */
  resource?: ResourceRef;

  /**
   * Action being performed on the resource.
   *
   * @generated from field: string action = 3;
   */
  action: string;

  /**
   * Sensitivity of the operation.
   *
   * @generated from field: m8.platform.iam.v1.OperationSensitivity sensitivity = 4;
   */
  sensitivity: OperationSensitivity;

  /**
   * Human-readable transaction binding message shown to the user.
   *
   * @generated from field: string binding_message = 5;
   */
  bindingMessage: string;

  /**
   * Short transaction binding code shown to the user.
   *
   * @generated from field: string binding_code = 6;
   */
  bindingCode: string;

  /**
   * Monetary amount involved in the operation.
   *
   * @generated from field: m8.platform.iam.v1.MoneyAmount amount = 7;
   */
  amount?: MoneyAmount;

  /**
   * Counterparty identifier or reference.
   *
   * @generated from field: string counterparty_id = 8;
   */
  counterpartyId: string;

  /**
   * Counterparty display name safe for audit and user confirmation.
   *
   * @generated from field: string counterparty_display_name = 9;
   */
  counterpartyDisplayName: string;

  /**
   * Whether the operation changes security posture.
   *
   * @generated from field: bool security_sensitive = 10;
   */
  securitySensitive: boolean;

  /**
   * Whether the operation changes privileges or roles.
   *
   * @generated from field: bool privilege_sensitive = 11;
   */
  privilegeSensitive: boolean;

  /**
   * Whether the operation accesses or changes sensitive data.
   *
   * @generated from field: bool data_sensitive = 12;
   */
  dataSensitive: boolean;

  /**
   * Additional non-sensitive transaction attributes.
   *
   * @generated from field: map<string, string> attributes = 13;
   */
  attributes: { [key: string]: string };
};

/**
 * Describes the message m8.platform.iam.v1.TransactionContext.
 * Use `create(TransactionContextSchema)` to create a new message.
 */
export declare const TransactionContextSchema: GenMessage<TransactionContext>;

/**
 * ResourceRef identifies a resource without embedding the full resource payload.
 * Resource Manager remains the source of truth for resource metadata and lifecycle.
 *
 * @generated from message m8.platform.iam.v1.ResourceRef
 */
export declare type ResourceRef = Message<"m8.platform.iam.v1.ResourceRef"> & {
  /**
   * Resource type, such as account, project, or credential.
   *
   * @generated from field: string type = 1;
   */
  type: string;

  /**
   * Resource identifier or opaque reference.
   *
   * @generated from field: string id = 2;
   */
  id: string;

  /**
   * Tenant or namespace that owns the resource.
   *
   * @generated from field: string owner_id = 3;
   */
  ownerId: string;

  /**
   * Display name safe for audit.
   *
   * @generated from field: string display_name = 4;
   */
  displayName: string;
};

/**
 * Describes the message m8.platform.iam.v1.ResourceRef.
 * Use `create(ResourceRefSchema)` to create a new message.
 */
export declare const ResourceRefSchema: GenMessage<ResourceRef>;

/**
 * MoneyAmount represents a monetary amount used for transaction confirmation.
 *
 * @generated from message m8.platform.iam.v1.MoneyAmount
 */
export declare type MoneyAmount = Message<"m8.platform.iam.v1.MoneyAmount"> & {
  /**
   * ISO 4217 currency code.
   *
   * @generated from field: string currency = 1;
   */
  currency: string;

  /**
   * Decimal amount as a string to avoid floating-point loss.
   *
   * @generated from field: string value = 2;
   */
  value: string;
};

/**
 * Describes the message m8.platform.iam.v1.MoneyAmount.
 * Use `create(MoneyAmountSchema)` to create a new message.
 */
export declare const MoneyAmountSchema: GenMessage<MoneyAmount>;

/**
 * Type of OAuth or platform client that initiated authentication.
 *
 * @generated from enum m8.platform.iam.v1.ClientType
 */
export enum ClientType {
  /**
   * Client type is not specified.
   *
   * @generated from enum value: CLIENT_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Browser-based web application.
   *
   * @generated from enum value: CLIENT_TYPE_WEB = 1;
   */
  WEB = 1,

  /**
   * Native mobile application.
   *
   * @generated from enum value: CLIENT_TYPE_MOBILE = 2;
   */
  MOBILE = 2,

  /**
   * Single-page application.
   *
   * @generated from enum value: CLIENT_TYPE_SPA = 3;
   */
  SPA = 3,

  /**
   * Server-side confidential application.
   *
   * @generated from enum value: CLIENT_TYPE_SERVER_SIDE = 4;
   */
  SERVER_SIDE = 4,

  /**
   * Machine-to-machine service client.
   *
   * @generated from enum value: CLIENT_TYPE_SERVICE = 5;
   */
  SERVICE = 5,

  /**
   * Command-line client.
   *
   * @generated from enum value: CLIENT_TYPE_CLI = 6;
   */
  CLI = 6,

  /**
   * Device or embedded client.
   *
   * @generated from enum value: CLIENT_TYPE_DEVICE = 7;
   */
  DEVICE = 7,
}

/**
 * Describes the enum m8.platform.iam.v1.ClientType.
 */
export declare const ClientTypeSchema: GenEnum<ClientType>;

/**
 * Trust level assigned to the requesting client.
 *
 * @generated from enum m8.platform.iam.v1.ClientTrustLevel
 */
export enum ClientTrustLevel {
  /**
   * Client trust level is not specified.
   *
   * @generated from enum value: CLIENT_TRUST_LEVEL_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Public client without strong client authentication.
   *
   * @generated from enum value: CLIENT_TRUST_LEVEL_PUBLIC = 1;
   */
  PUBLIC = 1,

  /**
   * Confidential client with client authentication.
   *
   * @generated from enum value: CLIENT_TRUST_LEVEL_CONFIDENTIAL = 2;
   */
  CONFIDENTIAL = 2,

  /**
   * Trusted client approved by the platform.
   *
   * @generated from enum value: CLIENT_TRUST_LEVEL_TRUSTED = 3;
   */
  TRUSTED = 3,

  /**
   * First-party client owned by the tenant or platform.
   *
   * @generated from enum value: CLIENT_TRUST_LEVEL_FIRST_PARTY = 4;
   */
  FIRST_PARTY = 4,

  /**
   * Third-party client outside direct platform control.
   *
   * @generated from enum value: CLIENT_TRUST_LEVEL_THIRD_PARTY = 5;
   */
  THIRD_PARTY = 5,

  /**
   * Client has restricted trust by Resource Manager configuration.
   *
   * @generated from enum value: CLIENT_TRUST_LEVEL_RESTRICTED = 6;
   */
  RESTRICTED = 6,
}

/**
 * Describes the enum m8.platform.iam.v1.ClientTrustLevel.
 */
export declare const ClientTrustLevelSchema: GenEnum<ClientTrustLevel>;

/**
 * Sensitivity of the operation protected by authentication.
 *
 * @generated from enum m8.platform.iam.v1.OperationSensitivity
 */
export enum OperationSensitivity {
  /**
   * Operation sensitivity is not specified.
   *
   * @generated from enum value: OPERATION_SENSITIVITY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Low-sensitivity operation.
   *
   * @generated from enum value: OPERATION_SENSITIVITY_LOW = 1;
   */
  LOW = 1,

  /**
   * Medium-sensitivity operation.
   *
   * @generated from enum value: OPERATION_SENSITIVITY_MEDIUM = 2;
   */
  MEDIUM = 2,

  /**
   * High-sensitivity operation.
   *
   * @generated from enum value: OPERATION_SENSITIVITY_HIGH = 3;
   */
  HIGH = 3,

  /**
   * Critical operation with the strongest controls.
   *
   * @generated from enum value: OPERATION_SENSITIVITY_CRITICAL = 4;
   */
  CRITICAL = 4,
}

/**
 * Describes the enum m8.platform.iam.v1.OperationSensitivity.
 */
export declare const OperationSensitivitySchema: GenEnum<OperationSensitivity>;

