// @generated by protoc-gen-es v2.11.0
// @generated from file m8/platform/iam/v1/authentication_service.proto (package m8.platform.iam.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { AuthenticationSubject } from "./authentication_subject_pb";
import type { AuthenticationContext } from "./authentication_context_pb";
import type { AuthenticationMethod } from "./authentication_challenge_pb";
import type { Authentication, AuthenticationSchema } from "./authentication_pb";
import type { OperationSchema } from "../../../../google/longrunning/operations_pb";

/**
 * Describes the file m8/platform/iam/v1/authentication_service.proto.
 */
export declare const file_m8_platform_iam_v1_authentication_service: GenFile;

/**
 * Request to start an authentication operation.
 *
 * @generated from message m8.platform.iam.v1.StartAuthenticationRequest
 */
export declare type StartAuthenticationRequest = Message<"m8.platform.iam.v1.StartAuthenticationRequest"> & {
  /**
   * Required. Public client application identifier that initiates authentication.
   * The value must be a UUID.
   *
   * The server resolves this value to ClientConfig, project_id, user_pool_id,
   * allowed providers, allowed methods, and authentication policies.
   * Clients must not send project_id or user_pool_id in StartAuthenticationRequest.
   *
   * @generated from field: string client_id = 1;
   */
  clientId: string;

  /**
   * Optional. Subject identifier or hint used to resolve the authenticating user.
   *
   * @generated from field: m8.platform.iam.v1.AuthenticationSubject subject = 2;
   */
  subject?: AuthenticationSubject;

  /**
   * Optional. Additional authentication context used for policy and challenge selection.
   *
   * @generated from field: m8.platform.iam.v1.AuthenticationContext context = 3;
   */
  context?: AuthenticationContext;

  /**
   * Optional. Client preferences that influence authentication workflow selection.
   *
   * @generated from field: m8.platform.iam.v1.AuthenticationStartOptions options = 4;
   */
  options?: AuthenticationStartOptions;

  /**
   * Optional. Idempotency key for StartAuthentication retries.
   *
   * The same client_id and request_id must resolve to the same Authentication
   * operation. When omitted, retries are not guaranteed to be idempotent.
   *
   * @generated from field: string request_id = 5;
   */
  requestId: string;
};

/**
 * Describes the message m8.platform.iam.v1.StartAuthenticationRequest.
 * Use `create(StartAuthenticationRequestSchema)` to create a new message.
 */
export declare const StartAuthenticationRequestSchema: GenMessage<StartAuthenticationRequest>;

/**
 * Request to read the latest authentication operation snapshot.
 *
 * @generated from message m8.platform.iam.v1.GetAuthenticationRequest
 */
export declare type GetAuthenticationRequest = Message<"m8.platform.iam.v1.GetAuthenticationRequest"> & {
  /**
   * Required. Stable unique identifier of the authentication operation to read.
   * The value must be a valid UUID string.
   *
   * The server returns the latest known aggregate snapshot. This request does
   * not change authentication state and is safe for client or BFF polling.
   *
   * Example:
   * {
   *   "authentication_id": "7b0b93f5-6f4a-4c5b-9a9d-2b58a67e1c34"
   * }
   *
   * @generated from field: string authentication_id = 1;
   */
  authenticationId: string;
};

/**
 * Describes the message m8.platform.iam.v1.GetAuthenticationRequest.
 * Use `create(GetAuthenticationRequestSchema)` to create a new message.
 */
export declare const GetAuthenticationRequestSchema: GenMessage<GetAuthenticationRequest>;

/**
 * Request to cancel an active authentication operation.
 *
 * @generated from message m8.platform.iam.v1.CancelAuthenticationRequest
 */
export declare type CancelAuthenticationRequest = Message<"m8.platform.iam.v1.CancelAuthenticationRequest"> & {
  /**
   * Required. Stable unique identifier of the authentication operation to cancel.
   * The value must be a valid UUID string.
   *
   * @generated from field: string authentication_id = 1;
   */
  authenticationId: string;

  /**
   * Optional. Human-readable or machine-readable reason for cancellation.
   *
   * Example:
   * - "user_closed_login_window"
   * - "client_restarted_flow"
   * - "session_replaced"
   * - "admin_requested"
   *
   * @generated from field: string reason = 2;
   */
  reason: string;

  /**
   * Optional. Idempotency key for retrying cancellation.
   *
   * CancelAuthentication is naturally idempotent for terminal states, but
   * request_id allows the server to deduplicate concurrent cancellation attempts.
   * The same authentication_id and request_id must resolve to the same
   * cancellation result.
   *
   * Example:
   * {
   *   "authentication_id": "7b0b93f5-6f4a-4c5b-9a9d-2b58a67e1c34",
   *   "reason": "user_closed_login_window",
   *   "request_id": "0d8b7e3e-7e1c-4b7e-8a8f-1f3c2c4f9d11"
   * }
   *
   * @generated from field: string request_id = 3;
   */
  requestId: string;
};

/**
 * Describes the message m8.platform.iam.v1.CancelAuthenticationRequest.
 * Use `create(CancelAuthenticationRequestSchema)` to create a new message.
 */
export declare const CancelAuthenticationRequestSchema: GenMessage<CancelAuthenticationRequest>;

/**
 * Request to resend the current authentication challenge.
 *
 * @generated from message m8.platform.iam.v1.ResendAuthenticationChallengeRequest
 */
export declare type ResendAuthenticationChallengeRequest = Message<"m8.platform.iam.v1.ResendAuthenticationChallengeRequest"> & {
  /**
   * Required. Identifier of the authentication operation.
   *
   * @generated from field: string authentication_id = 1;
   */
  authenticationId: string;

  /**
   * Required. Identifier of the challenge to resend.
   *
   * The value must match Authentication.current_challenge.challenge_id.
   *
   * @generated from field: string challenge_id = 2;
   */
  challengeId: string;

  /**
   * Optional. Idempotency key for retrying resend safely.
   *
   * The same authentication_id, challenge_id, and request_id must resolve to the
   * same resend result.
   *
   * @generated from field: string request_id = 3;
   */
  requestId: string;
};

/**
 * Describes the message m8.platform.iam.v1.ResendAuthenticationChallengeRequest.
 * Use `create(ResendAuthenticationChallengeRequestSchema)` to create a new message.
 */
export declare const ResendAuthenticationChallengeRequestSchema: GenMessage<ResendAuthenticationChallengeRequest>;

/**
 * Request to select another authentication method or provider.
 *
 * @generated from message m8.platform.iam.v1.SelectAuthenticationChallengeRequest
 */
export declare type SelectAuthenticationChallengeRequest = Message<"m8.platform.iam.v1.SelectAuthenticationChallengeRequest"> & {
  /**
   * Required. Identifier of the authentication operation.
   *
   * @generated from field: string authentication_id = 1;
   */
  authenticationId: string;

  /**
   * Required. Authentication method selected by the client or user.
   *
   * @generated from field: m8.platform.iam.v1.AuthenticationMethod method = 2;
   */
  method: AuthenticationMethod;

  /**
   * Optional. Provider identifier for provider-based methods.
   *
   * Example:
   * - "google"
   * - "saml-corp"
   * - "mobile-id-at"
   * - "m8-sms"
   *
   * @generated from field: string provider_id = 3;
   */
  providerId: string;

  /**
   * Optional. Idempotency key for retrying selection safely.
   *
   * The same authentication_id, method, provider_id, and request_id must resolve
   * to the same selection result.
   *
   * @generated from field: string request_id = 4;
   */
  requestId: string;
};

/**
 * Describes the message m8.platform.iam.v1.SelectAuthenticationChallengeRequest.
 * Use `create(SelectAuthenticationChallengeRequestSchema)` to create a new message.
 */
export declare const SelectAuthenticationChallengeRequestSchema: GenMessage<SelectAuthenticationChallengeRequest>;

/**
 * Request to submit the current authentication challenge response.
 *
 * @generated from message m8.platform.iam.v1.SubmitAuthenticationChallengeRequest
 */
export declare type SubmitAuthenticationChallengeRequest = Message<"m8.platform.iam.v1.SubmitAuthenticationChallengeRequest"> & {
  /**
   * Required. Stable unique identifier of the authentication operation.
   *
   * @generated from field: string authentication_id = 1;
   */
  authenticationId: string;

  /**
   * Required. Identifier of the current challenge being answered.
   *
   * The value must match Authentication.current_challenge.challenge_id.
   *
   * @generated from field: string challenge_id = 2;
   */
  challengeId: string;

  /**
   * Required. Response or proof for the current challenge. Raw passwords and
   * OTP codes are accepted only in this request and must never be returned in
   * Authentication, AuthenticationContext, AuthenticationChallengeInfo, or
   * AuthenticationError.
   *
   * @generated from oneof m8.platform.iam.v1.SubmitAuthenticationChallengeRequest.response
   */
  response: {
    /**
     * OTP code submitted by the user.
     *
     * @generated from field: m8.platform.iam.v1.OtpChallengeResponse otp = 10;
     */
    value: OtpChallengeResponse;
    case: "otp";
  } | {
    /**
     * Password submitted by the user.
     *
     * @generated from field: m8.platform.iam.v1.PasswordChallengeResponse password = 11;
     */
    value: PasswordChallengeResponse;
    case: "password";
  } | {
    /**
     * WebAuthn assertion produced by the browser or platform authenticator.
     *
     * @generated from field: m8.platform.iam.v1.WebAuthnAssertionResponse webauthn = 12;
     */
    value: WebAuthnAssertionResponse;
    case: "webauthn";
  } | {
    /**
     * Approval result submitted by an approval-capable client.
     *
     * @generated from field: m8.platform.iam.v1.ApprovalChallengeResponse approval = 13;
     */
    value: ApprovalChallengeResponse;
    case: "approval";
  } | { case: undefined; value?: undefined };

  /**
   * Optional. Idempotency key for retrying challenge submission safely.
   *
   * @generated from field: string request_id = 100;
   */
  requestId: string;
};

/**
 * Describes the message m8.platform.iam.v1.SubmitAuthenticationChallengeRequest.
 * Use `create(SubmitAuthenticationChallengeRequestSchema)` to create a new message.
 */
export declare const SubmitAuthenticationChallengeRequestSchema: GenMessage<SubmitAuthenticationChallengeRequest>;

/**
 * OtpChallengeResponse contains an OTP code submitted by the user.
 *
 * It is request-only data and must never be returned in public snapshots.
 *
 * @generated from message m8.platform.iam.v1.OtpChallengeResponse
 */
export declare type OtpChallengeResponse = Message<"m8.platform.iam.v1.OtpChallengeResponse"> & {
  /**
   * Required. One-time password code submitted for verification.
   *
   * @generated from field: string code = 1;
   */
  code: string;
};

/**
 * Describes the message m8.platform.iam.v1.OtpChallengeResponse.
 * Use `create(OtpChallengeResponseSchema)` to create a new message.
 */
export declare const OtpChallengeResponseSchema: GenMessage<OtpChallengeResponse>;

/**
 * PasswordChallengeResponse contains a password submitted by the user.
 *
 * It is request-only data and must never be returned, logged, or stored in the
 * public authentication snapshot.
 *
 * @generated from message m8.platform.iam.v1.PasswordChallengeResponse
 */
export declare type PasswordChallengeResponse = Message<"m8.platform.iam.v1.PasswordChallengeResponse"> & {
  /**
   * Required. Password submitted for verification.
   *
   * @generated from field: string password = 1;
   */
  password: string;
};

/**
 * Describes the message m8.platform.iam.v1.PasswordChallengeResponse.
 * Use `create(PasswordChallengeResponseSchema)` to create a new message.
 */
export declare const PasswordChallengeResponseSchema: GenMessage<PasswordChallengeResponse>;

/**
 * WebAuthnAssertionResponse contains the browser assertion response for a
 * WebAuthn/passkey challenge.
 *
 * @generated from message m8.platform.iam.v1.WebAuthnAssertionResponse
 */
export declare type WebAuthnAssertionResponse = Message<"m8.platform.iam.v1.WebAuthnAssertionResponse"> & {
  /**
   * Required. Base64url-encoded credential identifier.
   *
   * @generated from field: string credential_id = 1;
   */
  credentialId: string;

  /**
   * Required. Base64url-encoded clientDataJSON.
   *
   * @generated from field: string client_data_json = 2;
   */
  clientDataJson: string;

  /**
   * Required. Base64url-encoded authenticatorData.
   *
   * @generated from field: string authenticator_data = 3;
   */
  authenticatorData: string;

  /**
   * Required. Base64url-encoded assertion signature.
   *
   * @generated from field: string signature = 4;
   */
  signature: string;

  /**
   * Optional. Base64url-encoded WebAuthn user handle, when supplied by the authenticator.
   *
   * @generated from field: string user_handle = 5;
   */
  userHandle: string;
};

/**
 * Describes the message m8.platform.iam.v1.WebAuthnAssertionResponse.
 * Use `create(WebAuthnAssertionResponseSchema)` to create a new message.
 */
export declare const WebAuthnAssertionResponseSchema: GenMessage<WebAuthnAssertionResponse>;

/**
 * ApprovalChallengeResponse contains an approval or denial result.
 *
 * @generated from message m8.platform.iam.v1.ApprovalChallengeResponse
 */
export declare type ApprovalChallengeResponse = Message<"m8.platform.iam.v1.ApprovalChallengeResponse"> & {
  /**
   * Required. True when the user approved the challenge, false when denied.
   *
   * @generated from field: bool approved = 1;
   */
  approved: boolean;
};

/**
 * Describes the message m8.platform.iam.v1.ApprovalChallengeResponse.
 * Use `create(ApprovalChallengeResponseSchema)` to create a new message.
 */
export declare const ApprovalChallengeResponseSchema: GenMessage<ApprovalChallengeResponse>;

/**
 * Request to process a callback from an external identity provider.
 *
 * @generated from message m8.platform.iam.v1.HandleAuthenticationCallbackRequest
 */
export declare type HandleAuthenticationCallbackRequest = Message<"m8.platform.iam.v1.HandleAuthenticationCallbackRequest"> & {
  /**
   * Required. Provider identifier that produced the callback.
   *
   * Example:
   * - "google"
   * - "saml-corp"
   * - "mobile-id-at"
   *
   * @generated from field: string provider_id = 1;
   */
  providerId: string;

  /**
   * Optional. Authentication operation identifier.
   *
   * Some providers allow resolving the authentication operation from state,
   * RelayState, or provider-specific transaction identifiers instead.
   *
   * @generated from field: string authentication_id = 2;
   */
  authenticationId: string;

  /**
   * Optional. OIDC or OAuth authorization code.
   *
   * The server exchanges this value internally if needed. It must not be
   * returned in public responses.
   *
   * @generated from field: string code = 3;
   */
  code: string;

  /**
   * Optional. OIDC or OAuth state value.
   *
   * The server validates this value internally for callback correlation and
   * anti-CSRF protection. It must not expose secrets.
   *
   * @generated from field: string state = 4;
   */
  state: string;

  /**
   * Optional. SAML response payload.
   *
   * This field may contain a large base64-encoded SAMLResponse. The server must
   * validate the assertion internally and must not return raw assertions in
   * public responses.
   *
   * @generated from field: string saml_response = 5;
   */
  samlResponse: string;

  /**
   * Optional. SAML RelayState value.
   *
   * @generated from field: string relay_state = 6;
   */
  relayState: string;

  /**
   * Optional. Raw query parameters received from the provider callback.
   *
   * This is useful for provider-specific integrations. Do not store or expose
   * secrets from this map in public responses.
   *
   * @generated from field: map<string, string> raw_query = 7;
   */
  rawQuery: { [key: string]: string };

  /**
   * Optional. Raw form parameters received from the provider callback.
   *
   * This is useful for SAML POST binding and provider-specific callbacks. Do not
   * store or expose secrets from this map in public responses.
   *
   * @generated from field: map<string, string> raw_form = 8;
   */
  rawForm: { [key: string]: string };

  /**
   * Optional. Idempotency key for retrying callback handling safely.
   *
   * The same provider_id, callback state, code, relay_state, and request_id must
   * resolve to the same callback result.
   *
   * @generated from field: string request_id = 9;
   */
  requestId: string;
};

/**
 * Describes the message m8.platform.iam.v1.HandleAuthenticationCallbackRequest.
 * Use `create(HandleAuthenticationCallbackRequestSchema)` to create a new message.
 */
export declare const HandleAuthenticationCallbackRequestSchema: GenMessage<HandleAuthenticationCallbackRequest>;

/**
 * Response returned after processing an external provider callback.
 *
 * @generated from message m8.platform.iam.v1.HandleAuthenticationCallbackResponse
 */
export declare type HandleAuthenticationCallbackResponse = Message<"m8.platform.iam.v1.HandleAuthenticationCallbackResponse"> & {
  /**
   * Output only. Updated authentication snapshot.
   *
   * The snapshot must not contain provider tokens, raw assertions, client
   * secrets, internal callback secrets, OTP codes, or passwords.
   *
   * @generated from field: m8.platform.iam.v1.Authentication authentication = 1;
   */
  authentication?: Authentication;

  /**
   * Output only. Optional redirect URI where the browser should be redirected
   * after callback handling.
   *
   * This URI must be validated by the server against the original client
   * configuration and callback state.
   *
   * @generated from field: string redirect_uri = 2;
   */
  redirectUri: string;

  /**
   * Output only. Indicates whether the provider callback completed the
   * authentication operation.
   *
   * @generated from field: bool completed = 3;
   */
  completed: boolean;
};

/**
 * Describes the message m8.platform.iam.v1.HandleAuthenticationCallbackResponse.
 * Use `create(HandleAuthenticationCallbackResponseSchema)` to create a new message.
 */
export declare const HandleAuthenticationCallbackResponseSchema: GenMessage<HandleAuthenticationCallbackResponse>;

/**
 * Metadata for the StartAuthentication long-running operation.
 *
 * @generated from message m8.platform.iam.v1.StartAuthenticationOperationMetadata
 */
export declare type StartAuthenticationOperationMetadata = Message<"m8.platform.iam.v1.StartAuthenticationOperationMetadata"> & {
  /**
   * Output only. Current snapshot of the authentication operation.
   *
   * The value is updated as the workflow advances through state transitions and
   * can be used by clients to poll progress before the operation completes.
   *
   * @generated from field: m8.platform.iam.v1.Authentication authentication = 1;
   */
  authentication?: Authentication;
};

/**
 * Describes the message m8.platform.iam.v1.StartAuthenticationOperationMetadata.
 * Use `create(StartAuthenticationOperationMetadataSchema)` to create a new message.
 */
export declare const StartAuthenticationOperationMetadataSchema: GenMessage<StartAuthenticationOperationMetadata>;

/**
 * AuthenticationStartOptions contains optional client preferences for starting authentication.
 *
 * The server may use these values to select login experience, provider, method,
 * and assurance requirements, but policy can override unsupported or disallowed
 * preferences.
 *
 * Example:
 * - passkey-first login requests requested_authentication_method =
 *   AUTHENTICATION_METHOD_WEBAUTHN_PASSKEY
 * - tenant-specific UI flow sends `login_experience_version`
 * - OIDC request passes acr_values requested by the relying party
 *
 * @generated from message m8.platform.iam.v1.AuthenticationStartOptions
 */
export declare type AuthenticationStartOptions = Message<"m8.platform.iam.v1.AuthenticationStartOptions"> & {
  /**
   * Optional. Login experience version requested by the client.
   *
   * Example:
   * - "default"
   * - "passkey-first"
   * - "passwordless-v2"
   *
   * @generated from field: string login_experience_version = 1;
   */
  loginExperienceVersion: string;

  /**
   * Optional. Preferred authentication provider identifier.
   * This selects a provider, channel, or provider integration for the requested
   * method. AuthenticationSubject.provider_id scopes subject identifiers and
   * must not be used to select the login provider.
   *
   * Example:
   * - WebAuthn provider id for passkey authentication
   * - OIDC provider id for external identity provider login
   * - Mobile ID provider id for mobile operator authentication
   *
   * @generated from field: string requested_provider_id = 2;
   */
  requestedProviderId: string;

  /**
   * Optional. Deprecated. Use requested_authentication_method for standard
   * methods and requested_method_id for custom, provider, or plugin methods.
   *
   * Deprecated examples:
   * - "passkey"
   * - "password"
   * - "otp"
   * - "mobile_id"
   *
   * @generated from field: string requested_method = 3 [deprecated = true];
   * @deprecated
   */
  requestedMethod: string;

  /**
   * Optional. Requested Authentication Context Class Reference values.
   *
   * Example:
   * - "AAL1" for normal login
   * - "AAL2" for multi-factor authentication
   * - "AAL3" for hardware-backed phishing-resistant authentication
   *
   * @generated from field: repeated string acr_values = 4;
   */
  acrValues: string[];

  /**
   * Optional. Preferred standard authentication method requested by the client.
   *
   * Use requested_method_id for custom, provider, or plugin methods not modeled
   * by AuthenticationMethod.
   *
   * @generated from field: m8.platform.iam.v1.AuthenticationMethod requested_authentication_method = 5;
   */
  requestedAuthenticationMethod: AuthenticationMethod;

  /**
   * Optional. Preferred custom, provider, or plugin method identifier.
   *
   * This complements requested_authentication_method and must be interpreted
   * against server-side client, provider, and policy configuration.
   *
   * @generated from field: string requested_method_id = 6;
   */
  requestedMethodId: string;
};

/**
 * Describes the message m8.platform.iam.v1.AuthenticationStartOptions.
 * Use `create(AuthenticationStartOptionsSchema)` to create a new message.
 */
export declare const AuthenticationStartOptionsSchema: GenMessage<AuthenticationStartOptions>;

/**
 * Service that starts and drives authentication operations.
 *
 * General flow:
 * - StartAuthentication creates an authentication operation.
 * - GetAuthentication polls the public-safe operation snapshot.
 * - Authentication.available_challenges builds dynamic login UI.
 * - SelectAuthenticationChallenge selects an allowed method, provider, channel,
 *   or integration.
 * - ResendAuthenticationChallenge redelivers an OTP-like current challenge.
 * - SubmitAuthenticationChallenge submits the user or client proof for the
 *   current challenge.
 * - HandleAuthenticationCallback accepts external provider callbacks.
 * - CancelAuthentication cancels an active operation.
 *
 * @generated from service m8.platform.iam.v1.AuthenticationService
 */
export declare const AuthenticationService: GenService<{
  /**
   * Starts a new authentication operation.
   *
   * The returned long-running operation resolves to Authentication when the
   * authentication workflow reaches a terminal state.
   *
   * @generated from rpc m8.platform.iam.v1.AuthenticationService.StartAuthentication
   */
  startAuthentication: {
    methodKind: "unary";
    input: typeof StartAuthenticationRequestSchema;
    output: typeof OperationSchema;
  },
  /**
   * Returns the latest snapshot of an authentication operation.
   *
   * It is safe to call this method repeatedly for polling. The response must not
   * contain sensitive challenge secrets such as OTP codes, passwords, provider
   * tokens, or internal callback secrets.
   *
   * Authorization:
   * - caller must be allowed to read the operation in the resolved project and
   *   user pool
   * - public clients may only read operations they started or are allowed to poll
   *
   * @generated from rpc m8.platform.iam.v1.AuthenticationService.GetAuthentication
   */
  getAuthentication: {
    methodKind: "unary";
    input: typeof GetAuthenticationRequestSchema;
    output: typeof AuthenticationSchema;
  },
  /**
   * Cancels an active authentication operation.
   *
   * The method is idempotent. Canceling an already terminal authentication
   * returns the current snapshot without changing its state.
   *
   * Cancel transition:
   * - fully cancelable active states transition to CANCELED
   * - cancel during VERIFYING, AUTHORIZATION_HANDOFF_PENDING, or FINALIZING may
   *   return an unchanged snapshot if verification or finalization already
   *   passed the safe cancellation point
   * - terminal states are returned unchanged
   * - a successful transition updates update_time and increments version
   * - terminal snapshots keep their existing update_time and version
   *
   * Implementation TODO:
   * - load Authentication by authentication_id
   * - return terminal snapshots unchanged
   * - persist state = CANCELED with optimistic version check
   * - emit audit or outbox event when the event model exists
   * - signal or cancel the underlying Temporal workflow
   *
   * Authorization:
   * - caller must be allowed to cancel the authentication operation
   * - public clients may cancel only their own active operation
   * - admin and service callers may cancel according to policy
   *
   * @generated from rpc m8.platform.iam.v1.AuthenticationService.CancelAuthentication
   */
  cancelAuthentication: {
    methodKind: "unary";
    input: typeof CancelAuthenticationRequestSchema;
    output: typeof AuthenticationSchema;
  },
  /**
   * Resends the current challenge when the selected method supports resend,
   * such as SMS OTP or email OTP.
   *
   * The method does not create a new authentication operation and must not
   * expose OTP codes or other challenge secrets. It is intended for active
   * operations whose current_challenge allows resend.
   *
   * Allowed states:
   * - CHALLENGE_DELIVERED
   * - WAITING_FOR_USER
   * - CHALLENGE_RETRY_REQUIRED
   * - STEP_UP_REQUIRED
   *
   * State transition:
   * - WAITING_FOR_USER -> CHALLENGE_DELIVERED or WAITING_FOR_USER
   * - state_reason becomes AUTHENTICATION_STATE_REASON_OTP_RESENT
   * - current_challenge resend metadata may be updated
   * - update_time is updated and version is incremented
   *
   * Idempotency:
   * - same authentication_id, challenge_id, and request_id returns the same
   *   resend result
   *
   * Implementation TODO:
   * - signal Temporal workflow with ResendChallengeSignal
   * - let workflow enforce cooldown, rate limit, and provider policy
   * - update current_challenge without exposing OTP codes or provider secrets
   *
   * Authorization:
   * - caller must be allowed to operate on this authentication operation
   * - public clients may resend only their own current challenge
   *
   * @generated from rpc m8.platform.iam.v1.AuthenticationService.ResendAuthenticationChallenge
   */
  resendAuthenticationChallenge: {
    methodKind: "unary";
    input: typeof ResendAuthenticationChallengeRequestSchema;
    output: typeof AuthenticationSchema;
  },
  /**
   * Selects an allowed authentication method or provider for an existing
   * authentication operation.
   *
   * This method prepares a new public-safe current_challenge but does not verify
   * user identity by itself. It does not accept passwords, OTP codes, WebAuthn
   * assertions, provider authorization codes, or provider tokens.
   *
   * Allowed states:
   * - IDENTIFYING, when the subject is already sufficiently resolved
   * - EVALUATING, when policy has already resolved allowed options
   * - CHALLENGE_DELIVERED
   * - WAITING_FOR_USER
   * - CHALLENGE_RETRY_REQUIRED
   * - STEP_UP_REQUIRED
   *
   * State transition:
   * - current_challenge is replaced with a newly prepared challenge
   * - state usually becomes CHALLENGE_PREPARING, CHALLENGE_DELIVERED, or
   *   WAITING_FOR_USER
   * - state_reason becomes AUTHENTICATION_STATE_REASON_CHALLENGE_RESELECTED
   * - update_time is updated and version is incremented
   *
   * If the requested method or provider is not allowed, the operation is not
   * changed and the server should return a command error or a safe
   * Authentication.error with METHOD_NOT_ALLOWED or PROVIDER_NOT_ALLOWED.
   *
   * Implementation TODO:
   * - signal Temporal workflow with SelectChallengeSignal
   * - let workflow enforce allowed methods, providers, risk decision, and policy
   * - prepare a new current_challenge without exposing secrets
   *
   * Authorization:
   * - caller can select only methods and providers allowed by client policy,
   *   user pool policy, risk decision, and current authentication state
   *
   * @generated from rpc m8.platform.iam.v1.AuthenticationService.SelectAuthenticationChallenge
   */
  selectAuthenticationChallenge: {
    methodKind: "unary";
    input: typeof SelectAuthenticationChallengeRequestSchema;
    output: typeof AuthenticationSchema;
  },
  /**
   * Submits a user or client response to the current authentication challenge.
   *
   * This method accepts the proof or response required by current_challenge and
   * returns an updated public-safe Authentication snapshot. The response must
   * never contain passwords, OTP codes, provider tokens, raw callback secrets,
   * private WebAuthn server-side session secrets, or raw provider responses.
   *
   * Allowed states:
   * - CHALLENGE_DELIVERED
   * - WAITING_FOR_USER
   * - CHALLENGE_RETRY_REQUIRED
   * - STEP_UP_REQUIRED
   *
   * State transition:
   * - WAITING_FOR_USER -> VERIFYING
   * - VERIFYING -> AUTHENTICATED | CHALLENGE_RETRY_REQUIRED | DENIED | BLOCKED
   *   | ATTEMPTS_EXCEEDED | EXPIRED | FAILED
   *
   * Idempotency:
   * - same authentication_id, challenge_id, and request_id returns the same
   *   submission result
   *
   * Implementation TODO:
   * - signal Temporal workflow with SubmitChallengeSignal
   * - workflow verifies proof or response
   * - workflow updates attempts, state_reason, current_challenge, and error
   * - workflow never stores raw passwords or OTP codes in the public snapshot
   *
   * Authorization:
   * - caller must be allowed to operate on this authentication operation
   * - public clients may submit only their own current challenge
   *
   * @generated from rpc m8.platform.iam.v1.AuthenticationService.SubmitAuthenticationChallenge
   */
  submitAuthenticationChallenge: {
    methodKind: "unary";
    input: typeof SubmitAuthenticationChallengeRequestSchema;
    output: typeof AuthenticationSchema;
  },
  /**
   * Processes callbacks from external identity providers.
   *
   * Providers include OIDC, SAML, Mobile ID, bank ID, national ID, or custom
   * providers. The method validates provider state internally and must not
   * expose provider tokens, raw assertions, client secrets, or internal callback
   * secrets in the response.
   *
   * HTTP bindings:
   * - GET is used by OIDC/OAuth authorization code callbacks.
   * - POST is used by SAML POST binding and provider-specific callbacks.
   *
   * Callback behavior:
   * - validate provider_id
   * - resolve Authentication by authentication_id, state, relay_state, or
   *   provider transaction identifiers
   * - validate state, relay state, nonce, anti-CSRF data, signatures, tokens, or
   *   provider-specific proof internally
   * - update state_reason to PROVIDER_CALLBACK_RECEIVED or
   *   PROVIDER_CALLBACK_INVALID
   * - transition through VERIFYING, FINALIZING, AUTHENTICATED, DENIED, BLOCKED,
   *   or FAILED according to validation and policy
   *
   * Idempotency:
   * - same provider_id, callback state, code, relay_state, and request_id returns
   *   the same callback result
   *
   * Implementation TODO:
   * - signal Temporal workflow with ProviderCallbackSignal
   * - let workflow validate callback data and finish the provider step
   *
   * Authorization:
   * - provider callbacks must be authenticated or validated through state,
   *   signature, SAML validation, OIDC token validation, or provider-specific
   *   verification
   * - public clients must not be trusted to assert callback success
   *
   * @generated from rpc m8.platform.iam.v1.AuthenticationService.HandleAuthenticationCallback
   */
  handleAuthenticationCallback: {
    methodKind: "unary";
    input: typeof HandleAuthenticationCallbackRequestSchema;
    output: typeof HandleAuthenticationCallbackResponseSchema;
  },
}>;

