// @generated by protoc-gen-es v2.11.0
// @generated from file m8/platform/iam/v1/authentication_challenge.proto (package m8.platform.iam.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file m8/platform/iam/v1/authentication_challenge.proto.
 */
export const file_m8_platform_iam_v1_authentication_challenge = /*@__PURE__*/
  fileDesc("CjFtOC9wbGF0Zm9ybS9pYW0vdjEvYXV0aGVudGljYXRpb25fY2hhbGxlbmdlLnByb3RvEhJtOC5wbGF0Zm9ybS5pYW0udjEqyAIKF0F1dGhlbnRpY2F0aW9uQ2hhbGxlbmdlEigKJEFVVEhFTlRJQ0FUSU9OX0NIQUxMRU5HRV9VTlNQRUNJRklFRBAAEiAKHEFVVEhFTlRJQ0FUSU9OX0NIQUxMRU5HRV9PVFAQARIlCiFBVVRIRU5USUNBVElPTl9DSEFMTEVOR0VfQVBQUk9WQUwQAhImCiJBVVRIRU5USUNBVElPTl9DSEFMTEVOR0VfTU9CSUxFX0lEEAMSJQohQVVUSEVOVElDQVRJT05fQ0hBTExFTkdFX1dFQkFVVEhOEAQSIQodQVVUSEVOVElDQVRJT05fQ0hBTExFTkdFX09JREMQBRIhCh1BVVRIRU5USUNBVElPTl9DSEFMTEVOR0VfU0FNTBAGEiUKIUFVVEhFTlRJQ0FUSU9OX0NIQUxMRU5HRV9QQVNTV09SRBAHQjdaNWdpdGh1Yi5jb20vbTgtdGVhbS9nby1nZW5wcm90by9tOC9wbGF0Zm9ybS9pYW0vdjE7aWFtYgZwcm90bzM");

/**
 * Describes the enum m8.platform.iam.v1.AuthenticationChallenge.
 */
export const AuthenticationChallengeSchema = /*@__PURE__*/
  enumDesc(file_m8_platform_iam_v1_authentication_challenge, 0);

/**
 * Challenge type required to continue or complete authentication.
 *
 * @generated from enum m8.platform.iam.v1.AuthenticationChallenge
 */
export const AuthenticationChallenge = /*@__PURE__*/
  tsEnum(AuthenticationChallengeSchema);

