// @generated by protoc-gen-es v2.11.0
// @generated from file m8/platform/iam/v1/authentication_request_context.proto (package m8.platform.iam.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import type { AuthenticationChallenge } from "./authentication_challenge_pb";

/**
 * Describes the file m8/platform/iam/v1/authentication_request_context.proto.
 */
export declare const file_m8_platform_iam_v1_authentication_request_context: GenFile;

/**
 * RequestMetadata describes how the authentication request entered the platform.
 *
 * Example:
 * - browser login request from web
 * - backchannel CIBA request from an OAuth client
 * - internal retry from an authentication workflow
 *
 * @generated from message m8.platform.iam.v1.RequestMetadata
 */
export declare type RequestMetadata = Message<"m8.platform.iam.v1.RequestMetadata"> & {
  /**
   * Request identifier used for idempotency and correlation.
   *
   * @generated from field: string request_id = 1;
   */
  requestId: string;

  /**
   * Source channel that submitted the request.
   *
   * @generated from field: m8.platform.iam.v1.RequestSource source = 2;
   */
  source: RequestSource;

  /**
   * Source-specific identifier such as storefront, mobile app, or integration id.
   *
   * @generated from field: string source_id = 3;
   */
  sourceId: string;

  /**
   * Client-provided idempotency key if available.
   *
   * @generated from field: string idempotency_key = 4;
   */
  idempotencyKey: string;

  /**
   * Correlation identifier propagated across services.
   *
   * @generated from field: string correlation_id = 5;
   */
  correlationId: string;

  /**
   * Time when the request was received.
   *
   * @generated from field: google.protobuf.Timestamp request_time = 6;
   */
  requestTime?: Timestamp;

  /**
   * Requested locale or language tag.
   *
   * @generated from field: string locale = 7;
   */
  locale: string;

  /**
   * Hash of the user agent string; raw user agent may be stored outside this context.
   *
   * @generated from field: string user_agent_hash = 8;
   */
  userAgentHash: string;

  /**
   * Additional non-sensitive request attributes.
   *
   * @generated from field: map<string, string> attributes = 9;
   */
  attributes: { [key: string]: string };
};

/**
 * Describes the message m8.platform.iam.v1.RequestMetadata.
 * Use `create(RequestMetadataSchema)` to create a new message.
 */
export declare const RequestMetadataSchema: GenMessage<RequestMetadata>;

/**
 * AuthenticationIntent captures why authentication is being requested.
 *
 * Example:
 * - primary sign-in
 * - step-up before changing payment details
 * - delegated authentication for a CIBA transaction
 *
 * @generated from message m8.platform.iam.v1.AuthenticationIntent
 */
export declare type AuthenticationIntent = Message<"m8.platform.iam.v1.AuthenticationIntent"> & {
  /**
   * Business purpose of the authentication operation.
   *
   * @generated from field: string purpose = 1;
   */
  purpose: string;

  /**
   * Operation or workflow name that requires authentication.
   *
   * @generated from field: string operation = 2;
   */
  operation: string;

  /**
   * Challenges requested or preferred by the caller.
   *
   * @generated from field: repeated m8.platform.iam.v1.AuthenticationChallenge requested_challenges = 3;
   */
  requestedChallenges: AuthenticationChallenge[];

  /**
   * Requested OIDC-compatible acr values from the caller.
   *
   * @generated from field: repeated string requested_acr_values = 4;
   */
  requestedAcrValues: string[];

  /**
   * Scopes requested by the client or operation.
   *
   * @generated from field: repeated string requested_scopes = 5;
   */
  requestedScopes: string[];

  /**
   * Whether the requested flow should avoid password entry when possible.
   *
   * @generated from field: bool passwordless = 6;
   */
  passwordless: boolean;

  /**
   * Whether authentication is delegated to an external provider.
   *
   * @generated from field: bool delegated = 7;
   */
  delegated: boolean;

  /**
   * Whether the caller explicitly requested step-up authentication.
   *
   * @generated from field: bool step_up_requested = 8;
   */
  stepUpRequested: boolean;

  /**
   * Additional non-sensitive intent attributes.
   *
   * @generated from field: map<string, string> attributes = 9;
   */
  attributes: { [key: string]: string };
};

/**
 * Describes the message m8.platform.iam.v1.AuthenticationIntent.
 * Use `create(AuthenticationIntentSchema)` to create a new message.
 */
export declare const AuthenticationIntentSchema: GenMessage<AuthenticationIntent>;

/**
 * Source from which an authentication request entered the platform.
 *
 * @generated from enum m8.platform.iam.v1.RequestSource
 */
export enum RequestSource {
  /**
   * Request source is not specified.
   *
   * @generated from enum value: REQUEST_SOURCE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Request originated from a browser-based web application.
   *
   * @generated from enum value: REQUEST_SOURCE_WEB = 1;
   */
  WEB = 1,

  /**
   * Request originated from a native mobile application.
   *
   * @generated from enum value: REQUEST_SOURCE_MOBILE_APP = 2;
   */
  MOBILE_APP = 2,

  /**
   * Request originated from a backend API integration.
   *
   * @generated from enum value: REQUEST_SOURCE_API = 3;
   */
  API = 3,

  /**
   * Request originated from an internal back-office system.
   *
   * @generated from enum value: REQUEST_SOURCE_BACKOFFICE = 4;
   */
  BACKOFFICE = 4,

  /**
   * Request originated from a retail or point-of-sale channel.
   *
   * @generated from enum value: REQUEST_SOURCE_RETAIL = 5;
   */
  RETAIL = 5,

  /**
   * Request originated from a partner integration.
   *
   * @generated from enum value: REQUEST_SOURCE_PARTNER = 6;
   */
  PARTNER = 6,

  /**
   * Request originated from an internal system workflow.
   *
   * @generated from enum value: REQUEST_SOURCE_SYSTEM = 7;
   */
  SYSTEM = 7,
}

/**
 * Describes the enum m8.platform.iam.v1.RequestSource.
 */
export declare const RequestSourceSchema: GenEnum<RequestSource>;

