// @generated by protoc-gen-es v2.11.0
// @generated from file m8/platform/iam/v1/authentication_service.proto (package m8.platform.iam.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { AuthenticationSubject } from "./authentication_subject_pb";
import type { AuthenticationContext } from "./authentication_context_pb";
import type { Authentication } from "./authentication_pb";
import type { OperationSchema } from "../../../../google/longrunning/operations_pb";

/**
 * Describes the file m8/platform/iam/v1/authentication_service.proto.
 */
export declare const file_m8_platform_iam_v1_authentication_service: GenFile;

/**
 * Request to start an authentication operation.
 *
 * @generated from message m8.platform.iam.v1.StartAuthenticationRequest
 */
export declare type StartAuthenticationRequest = Message<"m8.platform.iam.v1.StartAuthenticationRequest"> & {
  /**
   * Required. Immutable client application identifier that initiates authentication.
   *
   * @generated from field: string client_id = 1;
   */
  clientId: string;

  /**
   * Optional. Subject identifier or hint used to resolve the authenticating user.
   *
   * @generated from field: m8.platform.iam.v1.AuthenticationSubject subject = 2;
   */
  subject?: AuthenticationSubject;

  /**
   * Optional. Additional authentication context used for policy and challenge selection.
   *
   * @generated from field: m8.platform.iam.v1.AuthenticationContext context = 3;
   */
  context?: AuthenticationContext;

  /**
   * Optional. Client preferences that influence authentication workflow selection.
   *
   * @generated from field: m8.platform.iam.v1.AuthenticationStartOptions options = 4;
   */
  options?: AuthenticationStartOptions;
};

/**
 * Describes the message m8.platform.iam.v1.StartAuthenticationRequest.
 * Use `create(StartAuthenticationRequestSchema)` to create a new message.
 */
export declare const StartAuthenticationRequestSchema: GenMessage<StartAuthenticationRequest>;

/**
 * Metadata for the StartAuthentication long-running operation.
 *
 * @generated from message m8.platform.iam.v1.StartAuthenticationOperationMetadata
 */
export declare type StartAuthenticationOperationMetadata = Message<"m8.platform.iam.v1.StartAuthenticationOperationMetadata"> & {
  /**
   * Output only. Current snapshot of the authentication operation.
   *
   * The value is updated as the workflow advances through state transitions and
   * can be used by clients to poll progress before the operation completes.
   *
   * @generated from field: m8.platform.iam.v1.Authentication authentication = 1;
   */
  authentication?: Authentication;
};

/**
 * Describes the message m8.platform.iam.v1.StartAuthenticationOperationMetadata.
 * Use `create(StartAuthenticationOperationMetadataSchema)` to create a new message.
 */
export declare const StartAuthenticationOperationMetadataSchema: GenMessage<StartAuthenticationOperationMetadata>;

/**
 * AuthenticationStartOptions contains optional client preferences for starting authentication.
 *
 * The server may use these values to select login experience, provider, method,
 * and assurance requirements, but policy can override unsupported or disallowed
 * preferences.
 *
 * Example:
 * - passkey-first login requests `requested_method` = "passkey"
 * - tenant-specific UI flow sends `login_experience_version`
 * - OIDC request passes acr_values requested by the relying party
 *
 * @generated from message m8.platform.iam.v1.AuthenticationStartOptions
 */
export declare type AuthenticationStartOptions = Message<"m8.platform.iam.v1.AuthenticationStartOptions"> & {
  /**
   * Optional. Login experience version requested by the client.
   *
   * Example:
   * - "default"
   * - "passkey-first"
   * - "passwordless-v2"
   *
   * @generated from field: string login_experience_version = 1;
   */
  loginExperienceVersion: string;

  /**
   * Optional. Preferred authentication provider identifier.
   *
   * Example:
   * - WebAuthn provider id for passkey authentication
   * - OIDC provider id for external identity provider login
   * - Mobile ID provider id for mobile operator authentication
   *
   * @generated from field: string requested_provider_id = 2;
   */
  requestedProviderId: string;

  /**
   * Optional. Preferred authentication method requested by the client.
   *
   * Example:
   * - "passkey"
   * - "password"
   * - "otp"
   * - "mobile_id"
   *
   * @generated from field: string requested_method = 3;
   */
  requestedMethod: string;

  /**
   * Optional. Requested Authentication Context Class Reference values.
   *
   * Example:
   * - "AAL1" for normal login
   * - "AAL2" for multi-factor authentication
   * - "AAL3" for hardware-backed phishing-resistant authentication
   *
   * @generated from field: repeated string acr_values = 4;
   */
  acrValues: string[];
};

/**
 * Describes the message m8.platform.iam.v1.AuthenticationStartOptions.
 * Use `create(AuthenticationStartOptionsSchema)` to create a new message.
 */
export declare const AuthenticationStartOptionsSchema: GenMessage<AuthenticationStartOptions>;

/**
 * Service that starts and drives authentication operations.
 *
 * @generated from service m8.platform.iam.v1.AuthenticationService
 */
export declare const AuthenticationService: GenService<{
  /**
   * Starts a new authentication operation.
   *
   * The returned long-running operation resolves to Authentication when the
   * authentication workflow reaches a terminal state.
   *
   * @generated from rpc m8.platform.iam.v1.AuthenticationService.StartAuthentication
   */
  startAuthentication: {
    methodKind: "unary";
    input: typeof StartAuthenticationRequestSchema;
    output: typeof OperationSchema;
  },
}>;

