// @generated by protoc-gen-es v2.11.0
// @generated from file m8/platform/iam/v1/authentication_error.proto (package m8.platform.iam.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file m8/platform/iam/v1/authentication_error.proto.
 */
export declare const file_m8_platform_iam_v1_authentication_error: GenFile;

/**
 * AuthenticationError contains safe error details for terminal or problem
 * states.
 *
 * It must not contain stack traces, secrets, tokens, OTP codes, passwords, raw
 * provider responses, or private risk model details.
 *
 * @generated from message m8.platform.iam.v1.AuthenticationError
 */
export declare type AuthenticationError = Message<"m8.platform.iam.v1.AuthenticationError"> & {
  /**
   * Output only. Typed error code for SDK branching.
   *
   * @generated from field: m8.platform.iam.v1.AuthenticationErrorCode typed_code = 6;
   */
  typedCode: AuthenticationErrorCode;

  /**
   * Output only. Safe human-readable error message.
   *
   * This message must not contain stack traces, secrets, tokens, OTP codes,
   * passwords, or raw provider responses.
   *
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * Output only. State reason associated with this error.
   *
   * @generated from field: m8.platform.iam.v1.AuthenticationStateReason reason = 3;
   */
  reason: AuthenticationStateReason;

  /**
   * Output only. Provider related to the error, if any.
   *
   * Example:
   * - "google"
   * - "saml-corp"
   * - "mobile-id-at"
   *
   * @generated from field: string provider_id = 4;
   */
  providerId: string;

  /**
   * Output only. Safe provider-level error code, if a provider returned one.
   *
   * This must not contain raw provider responses, tokens, assertions, callback
   * secrets, stack traces, or user-entered secrets.
   *
   * @generated from field: string provider_error_code = 7;
   */
  providerErrorCode: string;

  /**
   * Output only. Indicates whether retrying the same operation may succeed.
   *
   * @generated from field: bool retryable = 5;
   */
  retryable: boolean;
};

/**
 * Describes the message m8.platform.iam.v1.AuthenticationError.
 * Use `create(AuthenticationErrorSchema)` to create a new message.
 */
export declare const AuthenticationErrorSchema: GenMessage<AuthenticationError>;

/**
 * AuthenticationStateReason explains the latest authentication state transition.
 *
 * Values are safe to expose to clients and internal admin UI. They must not
 * encode secrets, provider tokens, raw provider responses, stack traces, or
 * private risk model details.
 *
 * @generated from enum m8.platform.iam.v1.AuthenticationStateReason
 */
export enum AuthenticationStateReason {
  /**
   * Authentication state reason is not specified.
   *
   * @generated from enum value: AUTHENTICATION_STATE_REASON_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Authentication operation was accepted by the server.
   *
   * @generated from enum value: AUTHENTICATION_STATE_REASON_START_ACCEPTED = 1;
   */
  START_ACCEPTED = 1,

  /**
   * Subject was successfully resolved.
   *
   * @generated from enum value: AUTHENTICATION_STATE_REASON_SUBJECT_RESOLVED = 2;
   */
  SUBJECT_RESOLVED = 2,

  /**
   * Subject could not be found or resolved.
   *
   * @generated from enum value: AUTHENTICATION_STATE_REASON_SUBJECT_NOT_FOUND = 3;
   */
  SUBJECT_NOT_FOUND = 3,

  /**
   * Risk decision allowed authentication to continue.
   *
   * @generated from enum value: AUTHENTICATION_STATE_REASON_RISK_ALLOWED = 4;
   */
  RISK_ALLOWED = 4,

  /**
   * Risk decision requires an additional challenge.
   *
   * @generated from enum value: AUTHENTICATION_STATE_REASON_RISK_CHALLENGE_REQUIRED = 5;
   */
  RISK_CHALLENGE_REQUIRED = 5,

  /**
   * Risk decision blocked authentication.
   *
   * @generated from enum value: AUTHENTICATION_STATE_REASON_RISK_BLOCKED = 6;
   */
  RISK_BLOCKED = 6,

  /**
   * Challenge was selected.
   *
   * @generated from enum value: AUTHENTICATION_STATE_REASON_CHALLENGE_SELECTED = 7;
   */
  CHALLENGE_SELECTED = 7,

  /**
   * OTP was sent.
   *
   * @generated from enum value: AUTHENTICATION_STATE_REASON_OTP_SENT = 8;
   */
  OTP_SENT = 8,

  /**
   * OTP resend was requested and accepted.
   *
   * @generated from enum value: AUTHENTICATION_STATE_REASON_OTP_RESENT = 9;
   */
  OTP_RESENT = 9,

  /**
   * Submitted OTP was invalid.
   *
   * @generated from enum value: AUTHENTICATION_STATE_REASON_OTP_INVALID = 10;
   */
  OTP_INVALID = 10,

  /**
   * Attempts limit was exceeded.
   *
   * @generated from enum value: AUTHENTICATION_STATE_REASON_ATTEMPTS_EXCEEDED = 11;
   */
  ATTEMPTS_EXCEEDED = 11,

  /**
   * User approved authentication in another channel.
   *
   * @generated from enum value: AUTHENTICATION_STATE_REASON_USER_APPROVED = 12;
   */
  USER_APPROVED = 12,

  /**
   * User denied authentication in another channel.
   *
   * @generated from enum value: AUTHENTICATION_STATE_REASON_USER_DENIED = 13;
   */
  USER_DENIED = 13,

  /**
   * External provider redirect is required.
   *
   * @generated from enum value: AUTHENTICATION_STATE_REASON_PROVIDER_REDIRECT_REQUIRED = 14;
   */
  PROVIDER_REDIRECT_REQUIRED = 14,

  /**
   * External provider callback was received.
   *
   * @generated from enum value: AUTHENTICATION_STATE_REASON_PROVIDER_CALLBACK_RECEIVED = 15;
   */
  PROVIDER_CALLBACK_RECEIVED = 15,

  /**
   * External provider callback validation failed.
   *
   * @generated from enum value: AUTHENTICATION_STATE_REASON_PROVIDER_CALLBACK_INVALID = 16;
   */
  PROVIDER_CALLBACK_INVALID = 16,

  /**
   * External provider timed out.
   *
   * @generated from enum value: AUTHENTICATION_STATE_REASON_PROVIDER_TIMEOUT = 17;
   */
  PROVIDER_TIMEOUT = 17,

  /**
   * WebAuthn assertion was invalid.
   *
   * @generated from enum value: AUTHENTICATION_STATE_REASON_WEBAUTHN_ASSERTION_INVALID = 18;
   */
  WEBAUTHN_ASSERTION_INVALID = 18,

  /**
   * Authentication completed successfully.
   *
   * @generated from enum value: AUTHENTICATION_STATE_REASON_AUTHENTICATED = 19;
   */
  AUTHENTICATED = 19,

  /**
   * Authentication expired.
   *
   * @generated from enum value: AUTHENTICATION_STATE_REASON_EXPIRED = 20;
   */
  EXPIRED = 20,

  /**
   * Authentication was canceled.
   *
   * @generated from enum value: AUTHENTICATION_STATE_REASON_CANCELED = 21;
   */
  CANCELED = 21,

  /**
   * Authentication failed because of an internal error.
   *
   * @generated from enum value: AUTHENTICATION_STATE_REASON_INTERNAL_ERROR = 22;
   */
  INTERNAL_ERROR = 22,

  /**
   * Client selected a different authentication challenge.
   *
   * @generated from enum value: AUTHENTICATION_STATE_REASON_CHALLENGE_RESELECTED = 23;
   */
  CHALLENGE_RESELECTED = 23,

  /**
   * Challenge resend is not allowed yet.
   *
   * @generated from enum value: AUTHENTICATION_STATE_REASON_RESEND_NOT_AVAILABLE = 24;
   */
  RESEND_NOT_AVAILABLE = 24,

  /**
   * Requested method is not allowed for this client, user, or context.
   *
   * @generated from enum value: AUTHENTICATION_STATE_REASON_METHOD_NOT_ALLOWED = 25;
   */
  METHOD_NOT_ALLOWED = 25,

  /**
   * Requested provider is not allowed for this client, user, or context.
   *
   * @generated from enum value: AUTHENTICATION_STATE_REASON_PROVIDER_NOT_ALLOWED = 26;
   */
  PROVIDER_NOT_ALLOWED = 26,
}

/**
 * Describes the enum m8.platform.iam.v1.AuthenticationStateReason.
 */
export declare const AuthenticationStateReasonSchema: GenEnum<AuthenticationStateReason>;

/**
 * AuthenticationErrorCode provides stable typed error codes for SDK branching.
 *
 * Values are safe to expose to clients. Provider-specific error details belong
 * in AuthenticationError.provider_error_code only when the code is safe and does
 * not include raw provider responses or secrets.
 *
 * @generated from enum m8.platform.iam.v1.AuthenticationErrorCode
 */
export enum AuthenticationErrorCode {
  /**
   * Authentication error code is not specified.
   *
   * @generated from enum value: AUTHENTICATION_ERROR_CODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Subject could not be found or resolved.
   *
   * @generated from enum value: AUTHENTICATION_ERROR_CODE_SUBJECT_NOT_FOUND = 1;
   */
  SUBJECT_NOT_FOUND = 1,

  /**
   * Requested authentication method is not allowed.
   *
   * @generated from enum value: AUTHENTICATION_ERROR_CODE_METHOD_NOT_ALLOWED = 2;
   */
  METHOD_NOT_ALLOWED = 2,

  /**
   * Requested provider is not allowed.
   *
   * @generated from enum value: AUTHENTICATION_ERROR_CODE_PROVIDER_NOT_ALLOWED = 3;
   */
  PROVIDER_NOT_ALLOWED = 3,

  /**
   * Provider callback was invalid or failed validation.
   *
   * @generated from enum value: AUTHENTICATION_ERROR_CODE_PROVIDER_CALLBACK_INVALID = 4;
   */
  PROVIDER_CALLBACK_INVALID = 4,

  /**
   * Retry attempts were exceeded.
   *
   * @generated from enum value: AUTHENTICATION_ERROR_CODE_ATTEMPTS_EXCEEDED = 5;
   */
  ATTEMPTS_EXCEEDED = 5,

  /**
   * Authentication expired.
   *
   * @generated from enum value: AUTHENTICATION_ERROR_CODE_EXPIRED = 6;
   */
  EXPIRED = 6,

  /**
   * Authentication was blocked by policy or risk decision.
   *
   * @generated from enum value: AUTHENTICATION_ERROR_CODE_BLOCKED = 7;
   */
  BLOCKED = 7,

  /**
   * Authentication was denied by the user or provider.
   *
   * @generated from enum value: AUTHENTICATION_ERROR_CODE_DENIED = 8;
   */
  DENIED = 8,

  /**
   * Internal or technical error.
   *
   * @generated from enum value: AUTHENTICATION_ERROR_CODE_INTERNAL = 9;
   */
  INTERNAL = 9,
}

/**
 * Describes the enum m8.platform.iam.v1.AuthenticationErrorCode.
 */
export declare const AuthenticationErrorCodeSchema: GenEnum<AuthenticationErrorCode>;

