// @generated by protoc-gen-es v2.11.0
// @generated from file m8/platform/iam/v1/authentication_challenge_decision_context.proto (package m8.platform.iam.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { AuthenticationChallenge } from "./authentication_challenge_pb";

/**
 * Describes the file m8/platform/iam/v1/authentication_challenge_decision_context.proto.
 */
export declare const file_m8_platform_iam_v1_authentication_challenge_decision_context: GenFile;

/**
 * ChallengeDecisionContext captures selected, current, and fallback challenges.
 *
 * Example:
 * - selected challenge is Mobile ID
 * - current challenge is OTP
 * - delivery channel is Mobile ID SMS fallback
 *
 * @generated from message m8.platform.iam.v1.ChallengeDecisionContext
 */
export declare type ChallengeDecisionContext = Message<"m8.platform.iam.v1.ChallengeDecisionContext"> & {
  /**
   * Primary challenge selected for the authentication operation.
   *
   * @generated from field: m8.platform.iam.v1.AuthenticationChallenge selected_challenge = 1;
   */
  selectedChallenge: AuthenticationChallenge;

  /**
   * Challenge that must be completed now.
   *
   * @generated from field: m8.platform.iam.v1.AuthenticationChallenge current_challenge = 2;
   */
  currentChallenge: AuthenticationChallenge;

  /**
   * Preferred challenges before requirement and provider filtering.
   *
   * @generated from field: repeated m8.platform.iam.v1.AuthenticationChallenge preferred_challenges = 3;
   */
  preferredChallenges: AuthenticationChallenge[];

  /**
   * Challenges allowed by authentication requirements and client capability.
   *
   * @generated from field: repeated m8.platform.iam.v1.AuthenticationChallenge allowed_challenges = 4;
   */
  allowedChallenges: AuthenticationChallenge[];

  /**
   * Fallback challenges that may be used if the current path fails.
   *
   * @generated from field: repeated m8.platform.iam.v1.AuthenticationChallenge fallback_challenges = 5;
   */
  fallbackChallenges: AuthenticationChallenge[];

  /**
   * Delivery channel for the current challenge.
   *
   * @generated from field: m8.platform.iam.v1.ChallengeDeliveryChannel delivery_channel = 6;
   */
  deliveryChannel: ChallengeDeliveryChannel;

  /**
   * Number of attempts already used for the current challenge.
   *
   * @generated from field: int32 attempts_used = 7;
   */
  attemptsUsed: number;

  /**
   * Number of attempts remaining for the current challenge.
   *
   * @generated from field: int32 attempts_remaining = 8;
   */
  attemptsRemaining: number;

  /**
   * Time-to-live for the current challenge in seconds.
   *
   * @generated from field: int64 ttl_seconds = 9;
   */
  ttlSeconds: bigint;

  /**
   * Whether a fallback challenge or provider has already been used.
   *
   * @generated from field: bool fallback_used = 10;
   */
  fallbackUsed: boolean;

  /**
   * Reason codes explaining challenge selection.
   *
   * @generated from field: repeated string selection_reasons = 11;
   */
  selectionReasons: string[];
};

/**
 * Describes the message m8.platform.iam.v1.ChallengeDecisionContext.
 * Use `create(ChallengeDecisionContextSchema)` to create a new message.
 */
export declare const ChallengeDecisionContextSchema: GenMessage<ChallengeDecisionContext>;

/**
 * Delivery channel used to expose a challenge to the user or client.
 *
 * @generated from enum m8.platform.iam.v1.ChallengeDeliveryChannel
 */
export enum ChallengeDeliveryChannel {
  /**
   * Challenge delivery channel is not specified.
   *
   * @generated from enum value: CHALLENGE_DELIVERY_CHANNEL_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * One-time password is delivered by SMS.
   *
   * @generated from enum value: CHALLENGE_DELIVERY_CHANNEL_SMS = 1;
   */
  SMS = 1,

  /**
   * One-time password or link is delivered by email.
   *
   * @generated from enum value: CHALLENGE_DELIVERY_CHANNEL_EMAIL = 2;
   */
  EMAIL = 2,

  /**
   * Challenge is delivered through a push notification.
   *
   * @generated from enum value: CHALLENGE_DELIVERY_CHANNEL_PUSH = 3;
   */
  PUSH = 3,

  /**
   * Challenge is delivered through Telegram.
   *
   * @generated from enum value: CHALLENGE_DELIVERY_CHANNEL_TELEGRAM = 4;
   */
  TELEGRAM = 4,

  /**
   * Challenge is delivered through VK.
   *
   * @generated from enum value: CHALLENGE_DELIVERY_CHANNEL_VK = 5;
   */
  VK = 5,

  /**
   * Mobile ID challenge uses operator SIM-push approval.
   *
   * @generated from enum value: CHALLENGE_DELIVERY_CHANNEL_MOBILE_ID_SIM_PUSH = 6;
   */
  MOBILE_ID_SIM_PUSH = 6,

  /**
   * Mobile ID challenge falls back to SMS OTP delivery.
   *
   * @generated from enum value: CHALLENGE_DELIVERY_CHANNEL_MOBILE_ID_SMS = 7;
   */
  MOBILE_ID_SMS = 7,

  /**
   * Challenge is delivered through a WebAuthn browser or client ceremony.
   *
   * @generated from enum value: CHALLENGE_DELIVERY_CHANNEL_WEBAUTHN = 8;
   */
  WEBAUTHN = 8,

  /**
   * Challenge is delivered through an OpenID Connect redirect.
   *
   * @generated from enum value: CHALLENGE_DELIVERY_CHANNEL_OIDC_REDIRECT = 9;
   */
  OIDC_REDIRECT = 9,

  /**
   * Challenge is delivered through a SAML redirect.
   *
   * @generated from enum value: CHALLENGE_DELIVERY_CHANNEL_SAML_REDIRECT = 10;
   */
  SAML_REDIRECT = 10,
}

/**
 * Describes the enum m8.platform.iam.v1.ChallengeDeliveryChannel.
 */
export declare const ChallengeDeliveryChannelSchema: GenEnum<ChallengeDeliveryChannel>;

