apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: m8-flink-session
  namespace: m8-data
  annotations:
    argocd.argoproj.io/sync-wave: "-45"
spec:
  image: docker.io/library/flink:2.2.0@sha256:7ecfab9d5e8ec6987a248b32f6605b5fe9bcb7347aea0d7b1bc3976588408681
  imagePullPolicy: IfNotPresent
  flinkVersion: v2_2
  mode: native
  serviceAccount: m8-flink
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
    rest.profiling.enabled: "true"
    state.checkpoints.dir: file:///tmp/flink-checkpoints
    state.savepoints.dir: file:///tmp/flink-savepoints
    kubernetes.operator.job.upgrade.last-state.max.allowed.checkpoint.age: "1 h"
  podTemplate:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 9999
        runAsGroup: 9999
        fsGroup: 9999
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: flink-main-container
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
  jobManager:
    replicas: 1
    resource:
      cpu: 1
      memory: "1536m"
  taskManager:
    replicas: 2
    resource:
      cpu: 2
      memory: "2048m"
