apiVersion: v1
kind: Namespace
metadata:
  name: m8-data
  labels:
    app.kubernetes.io/name: m8-data
    app.kubernetes.io/part-of: m8-platform
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
