apiVersion: kafka.strimzi.io/v1
kind: KafkaConnector
metadata:
  name: debezium-connector-sql02-cr
  namespace: debezium
  labels:
    strimzi.io/cluster: debezium-connect-sql02-cr
spec:
  class: io.debezium.connector.sqlserver.SqlServerConnector
  config:
    connector.class: io.debezium.connector.sqlserver.SqlServerConnector
    database.connectionTimeout: "120000"
    database.encrypt: "false"
    database.hostname: sql02.alena.ru
    database.names: CR
    database.password: coopha+o5Aphaes&i2oh
    database.port: "1433"
    database.queryTimeout: "0"
    database.socketTimeout: "3000000"
    database.sqlserver.agent.status.query: |-
      SELECT CASE WHEN EXISTS (
        SELECT 1
        FROM #db.sys.dm_server_services
        WHERE LOWER([filename]) LIKE N'%sqlagent.exe%'
          AND [status] = 4
      ) THEN 1 ELSE 0 END
    database.user: debezium_user
    errors.max.retries: 20
    heartbeat.interval.ms: 10000
    key.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    max.batch.size: 2048
    max.queue.size: 8192
    poll.interval.ms: 500
    retriable.restart.connector.wait.ms: 60000
    schema.history.internal: io.debezium.storage.kafka.history.KafkaSchemaHistory
    schema.history.internal.consumer.sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule
      required username="cdc-cr-producer" password="javsam-8qykje-fowhaT";
    schema.history.internal.consumer.sasl.mechanism: SCRAM-SHA-512
    schema.history.internal.consumer.security.protocol: SASL_SSL
    schema.history.internal.consumer.ssl.truststore.location: /mnt/kafka-certs/ca.crt
    schema.history.internal.consumer.ssl.truststore.type: PEM
    schema.history.internal.kafka.bootstrap.servers: rc1a-an3ivliisaqgs0nb.mdb.yandexcloud.net:9091,rc1d-93nrmjafghmd0gct.mdb.yandexcloud.net:9091,rc1e-vrheh76ndbah9ciu.mdb.yandexcloud.net:9091
    schema.history.internal.kafka.recovery.attempts: 10
    schema.history.internal.kafka.recovery.poll.interval.ms: 5000
    schema.history.internal.kafka.sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule
      required username="cdc-cr-producer" password="javsam-8qykje-fowhaT";
    schema.history.internal.kafka.sasl.mechanism: SCRAM-SHA-512
    schema.history.internal.kafka.security.protocol: SASL_SSL
    schema.history.internal.kafka.ssl.truststore.location: /mnt/kafka-certs/ca.crt
    schema.history.internal.kafka.ssl.truststore.type: PEM
    schema.history.internal.kafka.topic: cdc.CR.mssql.schema-history
    schema.history.internal.producer.sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule
      required username="cdc-cr-producer" password="javsam-8qykje-fowhaT";
    schema.history.internal.producer.sasl.mechanism: SCRAM-SHA-512
    schema.history.internal.producer.security.protocol: SASL_SSL
    schema.history.internal.producer.ssl.truststore.location: /mnt/kafka-certs/ca.crt
    schema.history.internal.producer.ssl.truststore.type: PEM
    schema.history.internal.store.only.captured.tables.ddl: "true"
    signal.consumer.auto.offset.reset: earliest
    signal.consumer.sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule
      required username="cdc-cr-producer" password="javsam-8qykje-fowhaT";
    signal.consumer.sasl.mechanism: SCRAM-SHA-512
    signal.consumer.security.protocol: SASL_SSL
    signal.consumer.ssl.truststore.location: /mnt/kafka-certs/ca.crt
    signal.consumer.ssl.truststore.type: PEM
    signal.enabled.channels: kafka
    signal.kafka.bootstrap.servers: rc1a-an3ivliisaqgs0nb.mdb.yandexcloud.net:9091,rc1d-93nrmjafghmd0gct.mdb.yandexcloud.net:9091,rc1e-vrheh76ndbah9ciu.mdb.yandexcloud.net:9091
    signal.kafka.groupId: kafka-signal
    signal.kafka.poll.timeout.ms: 5000
    signal.kafka.topic: cdc.CR.signal
    snapshot.fetch.size: 2000
    snapshot.isolation.mode: snapshot
    snapshot.locking.mode: none
    snapshot.max.threads: 1
    #snapshot.mode: recovery
    snapshot.mode: initial
    table.include.list: dbo._Reference4,dbo._Reference50,dbo._InfoRg4139
    topic.heartbeat.name: cdc.CR.heartbeat
    topic.prefix: cdc
    transforms: unwrap
    transforms.unwrap.delete.handling.mode: rewrite
    transforms.unwrap.drop.tombstones: false
    transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
  tasksMax: 1


