COMPOSE=docker compose -f docker-compose.yml
INSTALL_DIR ?= /usr/local/bin
KIND_VERSION ?=
KUBECTL_VERSION ?=
HELM_VERSION ?=
KIND_CLUSTER_NAME ?= m8-local
KIND_CONFIG ?= deploy/local/kind-config.yaml
KUBE_CONTEXT ?= kind-$(KIND_CLUSTER_NAME)
CLICKSTACK_RELEASE ?= m8-clickstack
CLICKSTACK_NAMESPACE ?= m8-observability
CLICKSTACK_OPERATORS_RELEASE ?= clickstack-operators
CLICKSTACK_OPERATORS_NAMESPACE ?= clickstack-system
CLICKSTACK_VALUES ?= deploy/local/clickstack-values.yaml
CLICKSTACK_TIMEOUT ?= 15m
CLICKSTACK_UI_PORT ?= 8080
CLICKSTACK_OTLP_GRPC_PORT ?= 4317
CLICKSTACK_OTLP_HTTP_PORT ?= 4318

.PHONY: up down restart logs shell ps clean
.PHONY: tools\:install-kind tools\:install-kubectl tools\:install-helm
.PHONY: dev\:up dev\:down dev\:reset
.PHONY: clickstack\:install clickstack\:uninstall clickstack\:reset clickstack\:status clickstack\:port-forward

up:
	$(COMPOSE) up -d

down:
	$(COMPOSE) down

restart:
	$(COMPOSE) down
	$(COMPOSE) up -d

logs:
	$(COMPOSE) logs -f

shell:
	$(COMPOSE) exec app bash

ps:
	$(COMPOSE) ps

clean:
	$(COMPOSE) down -v

tools\:install-kind:
	KIND_VERSION="$(KIND_VERSION)" INSTALL_DIR="$(INSTALL_DIR)" scripts/install-kind-macos.sh

tools\:install-kubectl:
	KUBECTL_VERSION="$(KUBECTL_VERSION)" INSTALL_DIR="$(INSTALL_DIR)" scripts/install-kubectl-macos.sh

tools\:install-helm:
	HELM_VERSION="$(HELM_VERSION)" INSTALL_DIR="$(INSTALL_DIR)" scripts/install-helm-macos.sh

dev\:up:
	KIND_CLUSTER_NAME="$(KIND_CLUSTER_NAME)" KIND_CONFIG="$(KIND_CONFIG)" scripts/dev-kind-cluster.sh up

dev\:down:
	KIND_CLUSTER_NAME="$(KIND_CLUSTER_NAME)" scripts/dev-kind-cluster.sh down

dev\:reset:
	KIND_CLUSTER_NAME="$(KIND_CLUSTER_NAME)" KIND_CONFIG="$(KIND_CONFIG)" scripts/dev-kind-cluster.sh reset

clickstack\:install:
	KIND_CLUSTER_NAME="$(KIND_CLUSTER_NAME)" \
	KUBE_CONTEXT="$(KUBE_CONTEXT)" \
	CLICKSTACK_RELEASE="$(CLICKSTACK_RELEASE)" \
	CLICKSTACK_NAMESPACE="$(CLICKSTACK_NAMESPACE)" \
	CLICKSTACK_OPERATORS_RELEASE="$(CLICKSTACK_OPERATORS_RELEASE)" \
	CLICKSTACK_OPERATORS_NAMESPACE="$(CLICKSTACK_OPERATORS_NAMESPACE)" \
	CLICKSTACK_VALUES="$(CLICKSTACK_VALUES)" \
	CLICKSTACK_TIMEOUT="$(CLICKSTACK_TIMEOUT)" \
	scripts/dev-clickstack.sh install

clickstack\:uninstall:
	KIND_CLUSTER_NAME="$(KIND_CLUSTER_NAME)" \
	KUBE_CONTEXT="$(KUBE_CONTEXT)" \
	CLICKSTACK_RELEASE="$(CLICKSTACK_RELEASE)" \
	CLICKSTACK_NAMESPACE="$(CLICKSTACK_NAMESPACE)" \
	CLICKSTACK_OPERATORS_RELEASE="$(CLICKSTACK_OPERATORS_RELEASE)" \
	CLICKSTACK_OPERATORS_NAMESPACE="$(CLICKSTACK_OPERATORS_NAMESPACE)" \
	CLICKSTACK_TIMEOUT="$(CLICKSTACK_TIMEOUT)" \
	scripts/dev-clickstack.sh uninstall

clickstack\:reset:
	KIND_CLUSTER_NAME="$(KIND_CLUSTER_NAME)" \
	KUBE_CONTEXT="$(KUBE_CONTEXT)" \
	CLICKSTACK_RELEASE="$(CLICKSTACK_RELEASE)" \
	CLICKSTACK_NAMESPACE="$(CLICKSTACK_NAMESPACE)" \
	CLICKSTACK_OPERATORS_RELEASE="$(CLICKSTACK_OPERATORS_RELEASE)" \
	CLICKSTACK_OPERATORS_NAMESPACE="$(CLICKSTACK_OPERATORS_NAMESPACE)" \
	CLICKSTACK_VALUES="$(CLICKSTACK_VALUES)" \
	CLICKSTACK_TIMEOUT="$(CLICKSTACK_TIMEOUT)" \
	scripts/dev-clickstack.sh reset

clickstack\:status:
	KIND_CLUSTER_NAME="$(KIND_CLUSTER_NAME)" \
	KUBE_CONTEXT="$(KUBE_CONTEXT)" \
	CLICKSTACK_RELEASE="$(CLICKSTACK_RELEASE)" \
	CLICKSTACK_NAMESPACE="$(CLICKSTACK_NAMESPACE)" \
	CLICKSTACK_OPERATORS_RELEASE="$(CLICKSTACK_OPERATORS_RELEASE)" \
	CLICKSTACK_OPERATORS_NAMESPACE="$(CLICKSTACK_OPERATORS_NAMESPACE)" \
	scripts/dev-clickstack.sh status

clickstack\:port-forward:
	KIND_CLUSTER_NAME="$(KIND_CLUSTER_NAME)" \
	KUBE_CONTEXT="$(KUBE_CONTEXT)" \
	CLICKSTACK_RELEASE="$(CLICKSTACK_RELEASE)" \
	CLICKSTACK_NAMESPACE="$(CLICKSTACK_NAMESPACE)" \
	CLICKSTACK_UI_PORT="$(CLICKSTACK_UI_PORT)" \
	CLICKSTACK_OTLP_GRPC_PORT="$(CLICKSTACK_OTLP_GRPC_PORT)" \
	CLICKSTACK_OTLP_HTTP_PORT="$(CLICKSTACK_OTLP_HTTP_PORT)" \
	scripts/dev-clickstack.sh port-forward
