apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iam-worker
  template:
    metadata:
      labels:
        app: iam-worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/m8platform/iam:latest
          args: ["./worker"]
          envFrom:
            - secretRef:
                name: iamd-env
