apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flink-1c
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: m8-flink
  source:
    repoURL: https://github.com/m8-team/platform.git
    targetRevision: main
    path: deploy/flink/installations/flink-1c/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: flink-1c
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - SkipDryRunOnMissingResource=true
