apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: flink-1c-sql
    files:
      - 10-source-price-types.sql=sources/price-types.sql
      - 20-view-price-types-normalized.sql=views/price-types-normalized.sql
      - 30-sink-price-types.sql=sinks/price-types.sql
      - 40-job-price-types.sql=jobs/price-types.sql

generatorOptions:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
