// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: m8/platform/iam/v1/authentication.proto

package iam

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/m8-team/go-genproto/m8/platform/extension/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticationHandoff_Type int32

const (
	AuthenticationHandoff_TYPE_UNSPECIFIED      AuthenticationHandoff_Type = 0
	AuthenticationHandoff_AUTHORIZATION_CODE    AuthenticationHandoff_Type = 1
	AuthenticationHandoff_CIBA_AUTH_REQ_ID      AuthenticationHandoff_Type = 2
	AuthenticationHandoff_SESSION_HANDOFF       AuthenticationHandoff_Type = 3
	AuthenticationHandoff_JWT_BEARER_ASSERTION  AuthenticationHandoff_Type = 4
	AuthenticationHandoff_KEYCLOAK_LOGIN_ACTION AuthenticationHandoff_Type = 5
)

// Enum value maps for AuthenticationHandoff_Type.
var (
	AuthenticationHandoff_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "AUTHORIZATION_CODE",
		2: "CIBA_AUTH_REQ_ID",
		3: "SESSION_HANDOFF",
		4: "JWT_BEARER_ASSERTION",
		5: "KEYCLOAK_LOGIN_ACTION",
	}
	AuthenticationHandoff_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED":      0,
		"AUTHORIZATION_CODE":    1,
		"CIBA_AUTH_REQ_ID":      2,
		"SESSION_HANDOFF":       3,
		"JWT_BEARER_ASSERTION":  4,
		"KEYCLOAK_LOGIN_ACTION": 5,
	}
)

func (x AuthenticationHandoff_Type) Enum() *AuthenticationHandoff_Type {
	p := new(AuthenticationHandoff_Type)
	*p = x
	return p
}

func (x AuthenticationHandoff_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthenticationHandoff_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_m8_platform_iam_v1_authentication_proto_enumTypes[0].Descriptor()
}

func (AuthenticationHandoff_Type) Type() protoreflect.EnumType {
	return &file_m8_platform_iam_v1_authentication_proto_enumTypes[0]
}

func (x AuthenticationHandoff_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthenticationHandoff_Type.Descriptor instead.
func (AuthenticationHandoff_Type) EnumDescriptor() ([]byte, []int) {
	return file_m8_platform_iam_v1_authentication_proto_rawDescGZIP(), []int{3, 0}
}

type Authentication struct {
	state                   protoimpl.MessageState           `protogen:"open.v1"`
	Id                      string                           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientId                string                           `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Subject                 *AuthenticationSubjectSnapshot   `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Purpose                 AuthenticationPurpose            `protobuf:"varint,4,opt,name=purpose,proto3,enum=m8.platform.iam.v1.AuthenticationPurpose" json:"purpose,omitempty"`
	State                   AuthenticationState              `protobuf:"varint,5,opt,name=state,proto3,enum=m8.platform.iam.v1.AuthenticationState" json:"state,omitempty"`
	StateReason             AuthenticationStateReason        `protobuf:"varint,6,opt,name=state_reason,json=stateReason,proto3,enum=m8.platform.iam.v1.AuthenticationStateReason" json:"state_reason,omitempty"`
	CurrentChallenge        *AuthenticationChallengeInfo     `protobuf:"bytes,7,opt,name=current_challenge,json=currentChallenge,proto3" json:"current_challenge,omitempty"`
	AvailableChallenges     []*AuthenticationChallengeOption `protobuf:"bytes,8,rep,name=available_challenges,json=availableChallenges,proto3" json:"available_challenges,omitempty"`
	Error                   *AuthenticationError             `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	Result                  *AuthenticationResult            `protobuf:"bytes,10,opt,name=result,proto3" json:"result,omitempty"`
	Context                 *AuthenticationContext           `protobuf:"bytes,11,opt,name=context,proto3" json:"context,omitempty"`
	CreateTime              *timestamppb.Timestamp           `protobuf:"bytes,12,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime              *timestamppb.Timestamp           `protobuf:"bytes,13,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	ExpireTime              *timestamppb.Timestamp           `protobuf:"bytes,14,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	Etag                    string                           `protobuf:"bytes,15,opt,name=etag,proto3" json:"etag,omitempty"`
	RequestedAssuranceLevel AuthenticationAssuranceLevel     `protobuf:"varint,16,opt,name=requested_assurance_level,json=requestedAssuranceLevel,proto3,enum=m8.platform.iam.v1.AuthenticationAssuranceLevel" json:"requested_assurance_level,omitempty"`
	Version                 int64                            `protobuf:"varint,17,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Authentication) Reset() {
	*x = Authentication{}
	mi := &file_m8_platform_iam_v1_authentication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authentication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authentication) ProtoMessage() {}

func (x *Authentication) ProtoReflect() protoreflect.Message {
	mi := &file_m8_platform_iam_v1_authentication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authentication.ProtoReflect.Descriptor instead.
func (*Authentication) Descriptor() ([]byte, []int) {
	return file_m8_platform_iam_v1_authentication_proto_rawDescGZIP(), []int{0}
}

func (x *Authentication) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Authentication) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Authentication) GetSubject() *AuthenticationSubjectSnapshot {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *Authentication) GetPurpose() AuthenticationPurpose {
	if x != nil {
		return x.Purpose
	}
	return AuthenticationPurpose_AUTHENTICATION_PURPOSE_UNSPECIFIED
}

func (x *Authentication) GetState() AuthenticationState {
	if x != nil {
		return x.State
	}
	return AuthenticationState_AUTHENTICATION_STATE_UNSPECIFIED
}

func (x *Authentication) GetStateReason() AuthenticationStateReason {
	if x != nil {
		return x.StateReason
	}
	return AuthenticationStateReason_AUTHENTICATION_STATE_REASON_UNSPECIFIED
}

func (x *Authentication) GetCurrentChallenge() *AuthenticationChallengeInfo {
	if x != nil {
		return x.CurrentChallenge
	}
	return nil
}

func (x *Authentication) GetAvailableChallenges() []*AuthenticationChallengeOption {
	if x != nil {
		return x.AvailableChallenges
	}
	return nil
}

func (x *Authentication) GetError() *AuthenticationError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Authentication) GetResult() *AuthenticationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Authentication) GetContext() *AuthenticationContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *Authentication) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Authentication) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Authentication) GetExpireTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireTime
	}
	return nil
}

func (x *Authentication) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *Authentication) GetRequestedAssuranceLevel() AuthenticationAssuranceLevel {
	if x != nil {
		return x.RequestedAssuranceLevel
	}
	return AuthenticationAssuranceLevel_AUTHENTICATION_ASSURANCE_LEVEL_UNSPECIFIED
}

func (x *Authentication) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type AuthenticationInteraction struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AuthenticationId string                 `protobuf:"bytes,1,opt,name=authentication_id,json=authenticationId,proto3" json:"authentication_id,omitempty"`
	InteractionToken string                 `protobuf:"bytes,2,opt,name=interaction_token,json=interactionToken,proto3" json:"interaction_token,omitempty"`
	ExpireTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthenticationInteraction) Reset() {
	*x = AuthenticationInteraction{}
	mi := &file_m8_platform_iam_v1_authentication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationInteraction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationInteraction) ProtoMessage() {}

func (x *AuthenticationInteraction) ProtoReflect() protoreflect.Message {
	mi := &file_m8_platform_iam_v1_authentication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationInteraction.ProtoReflect.Descriptor instead.
func (*AuthenticationInteraction) Descriptor() ([]byte, []int) {
	return file_m8_platform_iam_v1_authentication_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticationInteraction) GetAuthenticationId() string {
	if x != nil {
		return x.AuthenticationId
	}
	return ""
}

func (x *AuthenticationInteraction) GetInteractionToken() string {
	if x != nil {
		return x.InteractionToken
	}
	return ""
}

func (x *AuthenticationInteraction) GetExpireTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireTime
	}
	return nil
}

type AuthenticationResult struct {
	state                  protoimpl.MessageState       `protogen:"open.v1"`
	AuthTime               *timestamppb.Timestamp       `protobuf:"bytes,1,opt,name=auth_time,json=authTime,proto3" json:"auth_time,omitempty"`
	AchievedAssuranceLevel AuthenticationAssuranceLevel `protobuf:"varint,2,opt,name=achieved_assurance_level,json=achievedAssuranceLevel,proto3,enum=m8.platform.iam.v1.AuthenticationAssuranceLevel" json:"achieved_assurance_level,omitempty"`
	AuthenticationMethods  []AuthenticationMethod       `protobuf:"varint,3,rep,packed,name=authentication_methods,json=authenticationMethods,proto3,enum=m8.platform.iam.v1.AuthenticationMethod" json:"authentication_methods,omitempty"`
	MethodIds              []string                     `protobuf:"bytes,4,rep,name=method_ids,json=methodIds,proto3" json:"method_ids,omitempty"`
	Amr                    []string                     `protobuf:"bytes,5,rep,name=amr,proto3" json:"amr,omitempty"`
	Acr                    string                       `protobuf:"bytes,6,opt,name=acr,proto3" json:"acr,omitempty"`
	Handoff                *AuthenticationHandoff       `protobuf:"bytes,7,opt,name=handoff,proto3" json:"handoff,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AuthenticationResult) Reset() {
	*x = AuthenticationResult{}
	mi := &file_m8_platform_iam_v1_authentication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationResult) ProtoMessage() {}

func (x *AuthenticationResult) ProtoReflect() protoreflect.Message {
	mi := &file_m8_platform_iam_v1_authentication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationResult.ProtoReflect.Descriptor instead.
func (*AuthenticationResult) Descriptor() ([]byte, []int) {
	return file_m8_platform_iam_v1_authentication_proto_rawDescGZIP(), []int{2}
}

func (x *AuthenticationResult) GetAuthTime() *timestamppb.Timestamp {
	if x != nil {
		return x.AuthTime
	}
	return nil
}

func (x *AuthenticationResult) GetAchievedAssuranceLevel() AuthenticationAssuranceLevel {
	if x != nil {
		return x.AchievedAssuranceLevel
	}
	return AuthenticationAssuranceLevel_AUTHENTICATION_ASSURANCE_LEVEL_UNSPECIFIED
}

func (x *AuthenticationResult) GetAuthenticationMethods() []AuthenticationMethod {
	if x != nil {
		return x.AuthenticationMethods
	}
	return nil
}

func (x *AuthenticationResult) GetMethodIds() []string {
	if x != nil {
		return x.MethodIds
	}
	return nil
}

func (x *AuthenticationResult) GetAmr() []string {
	if x != nil {
		return x.Amr
	}
	return nil
}

func (x *AuthenticationResult) GetAcr() string {
	if x != nil {
		return x.Acr
	}
	return ""
}

func (x *AuthenticationResult) GetHandoff() *AuthenticationHandoff {
	if x != nil {
		return x.Handoff
	}
	return nil
}

type AuthenticationHandoff struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Type          AuthenticationHandoff_Type `protobuf:"varint,1,opt,name=type,proto3,enum=m8.platform.iam.v1.AuthenticationHandoff_Type" json:"type,omitempty"`
	HandoffId     string                     `protobuf:"bytes,2,opt,name=handoff_id,json=handoffId,proto3" json:"handoff_id,omitempty"`
	ExpireTime    *timestamppb.Timestamp     `protobuf:"bytes,3,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticationHandoff) Reset() {
	*x = AuthenticationHandoff{}
	mi := &file_m8_platform_iam_v1_authentication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationHandoff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationHandoff) ProtoMessage() {}

func (x *AuthenticationHandoff) ProtoReflect() protoreflect.Message {
	mi := &file_m8_platform_iam_v1_authentication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationHandoff.ProtoReflect.Descriptor instead.
func (*AuthenticationHandoff) Descriptor() ([]byte, []int) {
	return file_m8_platform_iam_v1_authentication_proto_rawDescGZIP(), []int{3}
}

func (x *AuthenticationHandoff) GetType() AuthenticationHandoff_Type {
	if x != nil {
		return x.Type
	}
	return AuthenticationHandoff_TYPE_UNSPECIFIED
}

func (x *AuthenticationHandoff) GetHandoffId() string {
	if x != nil {
		return x.HandoffId
	}
	return ""
}

func (x *AuthenticationHandoff) GetExpireTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireTime
	}
	return nil
}

var File_m8_platform_iam_v1_authentication_proto protoreflect.FileDescriptor

const file_m8_platform_iam_v1_authentication_proto_rawDesc = "" +
	"\n" +
	"'m8/platform/iam/v1/authentication.proto\x12\x12m8.platform.iam.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a(m8/platform/extension/v1/extension.proto\x1a1m8/platform/iam/v1/authentication_challenge.proto\x1a.m8/platform/iam/v1/authentication_common.proto\x1a/m8/platform/iam/v1/authentication_context.proto\x1a-m8/platform/iam/v1/authentication_error.proto\x1a/m8/platform/iam/v1/authentication_subject.proto\"\x8c\n" +
	"\n" +
	"\x0eAuthentication\x12\x1e\n" +
	"\x02id\x18\x01 \x01(\tB\x0e\xe0A\b\xe0A\x03\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12+\n" +
	"\tclient_id\x18\x02 \x01(\tB\x0e\xe0A\x03\xe0A\x05\xbaH\x05r\x03\xb0\x01\x01R\bclientId\x12P\n" +
	"\asubject\x18\x03 \x01(\v21.m8.platform.iam.v1.AuthenticationSubjectSnapshotB\x03\xe0A\x03R\asubject\x12P\n" +
	"\apurpose\x18\x04 \x01(\x0e2).m8.platform.iam.v1.AuthenticationPurposeB\v\xe0A\x03\xbaH\x05\x82\x01\x02\x10\x01R\apurpose\x12L\n" +
	"\x05state\x18\x05 \x01(\x0e2'.m8.platform.iam.v1.AuthenticationStateB\r\xe0A\x03\xbaH\a\x82\x01\x04\x10\x01 \x00R\x05state\x12]\n" +
	"\fstate_reason\x18\x06 \x01(\x0e2-.m8.platform.iam.v1.AuthenticationStateReasonB\v\xe0A\x03\xbaH\x05\x82\x01\x02\x10\x01R\vstateReason\x12a\n" +
	"\x11current_challenge\x18\a \x01(\v2/.m8.platform.iam.v1.AuthenticationChallengeInfoB\x03\xe0A\x03R\x10currentChallenge\x12q\n" +
	"\x14available_challenges\x18\b \x03(\v21.m8.platform.iam.v1.AuthenticationChallengeOptionB\v\xe0A\x03\xbaH\x05\x92\x01\x02\x10 R\x13availableChallenges\x12B\n" +
	"\x05error\x18\t \x01(\v2'.m8.platform.iam.v1.AuthenticationErrorB\x03\xe0A\x03R\x05error\x12E\n" +
	"\x06result\x18\n" +
	" \x01(\v2(.m8.platform.iam.v1.AuthenticationResultB\x03\xe0A\x03R\x06result\x12H\n" +
	"\acontext\x18\v \x01(\v2).m8.platform.iam.v1.AuthenticationContextB\x03\xe0A\x03R\acontext\x12C\n" +
	"\vcreate_time\x18\f \x01(\v2\x1a.google.protobuf.TimestampB\x06\xe0A\x03\xe0A\x05R\n" +
	"createTime\x12@\n" +
	"\vupdate_time\x18\r \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"updateTime\x12@\n" +
	"\vexpire_time\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"expireTime\x12\x1f\n" +
	"\x04etag\x18\x0f \x01(\tB\v\xe0A\x03\xbaH\x05r\x03\x18\x80\x01R\x04etag\x12y\n" +
	"\x19requested_assurance_level\x18\x10 \x01(\x0e20.m8.platform.iam.v1.AuthenticationAssuranceLevelB\v\xe0A\x03\xbaH\x05\x82\x01\x02\x10\x01R\x17requestedAssuranceLevel\x12$\n" +
	"\aversion\x18\x11 \x01(\x03B\n" +
	"\xe0A\x03\xbaH\x04\"\x02(\x00R\aversion:&\x8a\xb5\x18\"m8.platform.iam.authentications.v1\"\xd3\x01\n" +
	"\x19AuthenticationInteraction\x128\n" +
	"\x11authentication_id\x18\x01 \x01(\tB\v\xe0A\x03\xbaH\x05r\x03\xb0\x01\x01R\x10authenticationId\x12:\n" +
	"\x11interaction_token\x18\x02 \x01(\tB\r\xe0A\x03\xbaH\ar\x05\x10\b\x18\x80 R\x10interactionToken\x12@\n" +
	"\vexpire_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"expireTime\"\x89\x04\n" +
	"\x14AuthenticationResult\x12<\n" +
	"\tauth_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\bauthTime\x12w\n" +
	"\x18achieved_assurance_level\x18\x02 \x01(\x0e20.m8.platform.iam.v1.AuthenticationAssuranceLevelB\v\xe0A\x03\xbaH\x05\x82\x01\x02\x10\x01R\x16achievedAssuranceLevel\x12u\n" +
	"\x16authentication_methods\x18\x03 \x03(\x0e2(.m8.platform.iam.v1.AuthenticationMethodB\x14\xe0A\x03\xbaH\x0e\x92\x01\v\x10 \"\a\x82\x01\x04\x10\x01 \x00R\x15authenticationMethods\x123\n" +
	"\n" +
	"method_ids\x18\x04 \x03(\tB\x14\xe0A\x03\xbaH\x0e\x92\x01\v\x10 \"\ar\x05\x10\x01\x18\xff\x01R\tmethodIds\x12%\n" +
	"\x03amr\x18\x05 \x03(\tB\x13\xe0A\x03\xbaH\r\x92\x01\n" +
	"\x10 \"\x06r\x04\x10\x01\x18@R\x03amr\x12\x1d\n" +
	"\x03acr\x18\x06 \x01(\tB\v\xe0A\x03\xbaH\x05r\x03\x18\xff\x01R\x03acr\x12H\n" +
	"\ahandoff\x18\a \x01(\v2).m8.platform.iam.v1.AuthenticationHandoffB\x03\xe0A\x03R\ahandoff\"\xed\x02\n" +
	"\x15AuthenticationHandoff\x12O\n" +
	"\x04type\x18\x01 \x01(\x0e2..m8.platform.iam.v1.AuthenticationHandoff.TypeB\v\xe0A\x03\xbaH\x05\x82\x01\x02\x10\x01R\x04type\x12*\n" +
	"\n" +
	"handoff_id\x18\x02 \x01(\tB\v\xe0A\x03\xbaH\x05r\x03\x18\x80\x04R\thandoffId\x12@\n" +
	"\vexpire_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"expireTime\"\x94\x01\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12AUTHORIZATION_CODE\x10\x01\x12\x14\n" +
	"\x10CIBA_AUTH_REQ_ID\x10\x02\x12\x13\n" +
	"\x0fSESSION_HANDOFF\x10\x03\x12\x18\n" +
	"\x14JWT_BEARER_ASSERTION\x10\x04\x12\x19\n" +
	"\x15KEYCLOAK_LOGIN_ACTION\x10\x05B7Z5github.com/m8-team/go-genproto/m8/platform/iam/v1;iamb\x06proto3"

var (
	file_m8_platform_iam_v1_authentication_proto_rawDescOnce sync.Once
	file_m8_platform_iam_v1_authentication_proto_rawDescData []byte
)

func file_m8_platform_iam_v1_authentication_proto_rawDescGZIP() []byte {
	file_m8_platform_iam_v1_authentication_proto_rawDescOnce.Do(func() {
		file_m8_platform_iam_v1_authentication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_m8_platform_iam_v1_authentication_proto_rawDesc), len(file_m8_platform_iam_v1_authentication_proto_rawDesc)))
	})
	return file_m8_platform_iam_v1_authentication_proto_rawDescData
}

var file_m8_platform_iam_v1_authentication_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_m8_platform_iam_v1_authentication_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_m8_platform_iam_v1_authentication_proto_goTypes = []any{
	(AuthenticationHandoff_Type)(0),       // 0: m8.platform.iam.v1.AuthenticationHandoff.Type
	(*Authentication)(nil),                // 1: m8.platform.iam.v1.Authentication
	(*AuthenticationInteraction)(nil),     // 2: m8.platform.iam.v1.AuthenticationInteraction
	(*AuthenticationResult)(nil),          // 3: m8.platform.iam.v1.AuthenticationResult
	(*AuthenticationHandoff)(nil),         // 4: m8.platform.iam.v1.AuthenticationHandoff
	(*AuthenticationSubjectSnapshot)(nil), // 5: m8.platform.iam.v1.AuthenticationSubjectSnapshot
	(AuthenticationPurpose)(0),            // 6: m8.platform.iam.v1.AuthenticationPurpose
	(AuthenticationState)(0),              // 7: m8.platform.iam.v1.AuthenticationState
	(AuthenticationStateReason)(0),        // 8: m8.platform.iam.v1.AuthenticationStateReason
	(*AuthenticationChallengeInfo)(nil),   // 9: m8.platform.iam.v1.AuthenticationChallengeInfo
	(*AuthenticationChallengeOption)(nil), // 10: m8.platform.iam.v1.AuthenticationChallengeOption
	(*AuthenticationError)(nil),           // 11: m8.platform.iam.v1.AuthenticationError
	(*AuthenticationContext)(nil),         // 12: m8.platform.iam.v1.AuthenticationContext
	(*timestamppb.Timestamp)(nil),         // 13: google.protobuf.Timestamp
	(AuthenticationAssuranceLevel)(0),     // 14: m8.platform.iam.v1.AuthenticationAssuranceLevel
	(AuthenticationMethod)(0),             // 15: m8.platform.iam.v1.AuthenticationMethod
}
var file_m8_platform_iam_v1_authentication_proto_depIdxs = []int32{
	5,  // 0: m8.platform.iam.v1.Authentication.subject:type_name -> m8.platform.iam.v1.AuthenticationSubjectSnapshot
	6,  // 1: m8.platform.iam.v1.Authentication.purpose:type_name -> m8.platform.iam.v1.AuthenticationPurpose
	7,  // 2: m8.platform.iam.v1.Authentication.state:type_name -> m8.platform.iam.v1.AuthenticationState
	8,  // 3: m8.platform.iam.v1.Authentication.state_reason:type_name -> m8.platform.iam.v1.AuthenticationStateReason
	9,  // 4: m8.platform.iam.v1.Authentication.current_challenge:type_name -> m8.platform.iam.v1.AuthenticationChallengeInfo
	10, // 5: m8.platform.iam.v1.Authentication.available_challenges:type_name -> m8.platform.iam.v1.AuthenticationChallengeOption
	11, // 6: m8.platform.iam.v1.Authentication.error:type_name -> m8.platform.iam.v1.AuthenticationError
	3,  // 7: m8.platform.iam.v1.Authentication.result:type_name -> m8.platform.iam.v1.AuthenticationResult
	12, // 8: m8.platform.iam.v1.Authentication.context:type_name -> m8.platform.iam.v1.AuthenticationContext
	13, // 9: m8.platform.iam.v1.Authentication.create_time:type_name -> google.protobuf.Timestamp
	13, // 10: m8.platform.iam.v1.Authentication.update_time:type_name -> google.protobuf.Timestamp
	13, // 11: m8.platform.iam.v1.Authentication.expire_time:type_name -> google.protobuf.Timestamp
	14, // 12: m8.platform.iam.v1.Authentication.requested_assurance_level:type_name -> m8.platform.iam.v1.AuthenticationAssuranceLevel
	13, // 13: m8.platform.iam.v1.AuthenticationInteraction.expire_time:type_name -> google.protobuf.Timestamp
	13, // 14: m8.platform.iam.v1.AuthenticationResult.auth_time:type_name -> google.protobuf.Timestamp
	14, // 15: m8.platform.iam.v1.AuthenticationResult.achieved_assurance_level:type_name -> m8.platform.iam.v1.AuthenticationAssuranceLevel
	15, // 16: m8.platform.iam.v1.AuthenticationResult.authentication_methods:type_name -> m8.platform.iam.v1.AuthenticationMethod
	4,  // 17: m8.platform.iam.v1.AuthenticationResult.handoff:type_name -> m8.platform.iam.v1.AuthenticationHandoff
	0,  // 18: m8.platform.iam.v1.AuthenticationHandoff.type:type_name -> m8.platform.iam.v1.AuthenticationHandoff.Type
	13, // 19: m8.platform.iam.v1.AuthenticationHandoff.expire_time:type_name -> google.protobuf.Timestamp
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_m8_platform_iam_v1_authentication_proto_init() }
func file_m8_platform_iam_v1_authentication_proto_init() {
	if File_m8_platform_iam_v1_authentication_proto != nil {
		return
	}
	file_m8_platform_iam_v1_authentication_challenge_proto_init()
	file_m8_platform_iam_v1_authentication_common_proto_init()
	file_m8_platform_iam_v1_authentication_context_proto_init()
	file_m8_platform_iam_v1_authentication_error_proto_init()
	file_m8_platform_iam_v1_authentication_subject_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_m8_platform_iam_v1_authentication_proto_rawDesc), len(file_m8_platform_iam_v1_authentication_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_m8_platform_iam_v1_authentication_proto_goTypes,
		DependencyIndexes: file_m8_platform_iam_v1_authentication_proto_depIdxs,
		EnumInfos:         file_m8_platform_iam_v1_authentication_proto_enumTypes,
		MessageInfos:      file_m8_platform_iam_v1_authentication_proto_msgTypes,
	}.Build()
	File_m8_platform_iam_v1_authentication_proto = out.File
	file_m8_platform_iam_v1_authentication_proto_goTypes = nil
	file_m8_platform_iam_v1_authentication_proto_depIdxs = nil
}
