// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: m8/platform/iam/v1/authentication_provider_context.proto

package iam

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Provider type selected to execute or delegate authentication.
type ProviderType int32

const (
	// Provider type is not specified.
	ProviderType_PROVIDER_TYPE_UNSPECIFIED ProviderType = 0
	// Provider sends or validates one-time passwords.
	ProviderType_PROVIDER_TYPE_OTP ProviderType = 1
	// Provider handles explicit approval challenges.
	ProviderType_PROVIDER_TYPE_APPROVAL ProviderType = 2
	// Provider delegates authentication to Mobile ID.
	ProviderType_PROVIDER_TYPE_MOBILE_ID ProviderType = 3
	// Provider handles WebAuthn ceremonies.
	ProviderType_PROVIDER_TYPE_WEBAUTHN ProviderType = 4
	// Provider delegates authentication to OpenID Connect.
	ProviderType_PROVIDER_TYPE_OIDC ProviderType = 5
	// Provider delegates authentication to SAML.
	ProviderType_PROVIDER_TYPE_SAML ProviderType = 6
	// Provider validates passwords.
	ProviderType_PROVIDER_TYPE_PASSWORD ProviderType = 7
	// Provider handles notification delivery.
	ProviderType_PROVIDER_TYPE_NOTIFICATION ProviderType = 8
)

// Enum value maps for ProviderType.
var (
	ProviderType_name = map[int32]string{
		0: "PROVIDER_TYPE_UNSPECIFIED",
		1: "PROVIDER_TYPE_OTP",
		2: "PROVIDER_TYPE_APPROVAL",
		3: "PROVIDER_TYPE_MOBILE_ID",
		4: "PROVIDER_TYPE_WEBAUTHN",
		5: "PROVIDER_TYPE_OIDC",
		6: "PROVIDER_TYPE_SAML",
		7: "PROVIDER_TYPE_PASSWORD",
		8: "PROVIDER_TYPE_NOTIFICATION",
	}
	ProviderType_value = map[string]int32{
		"PROVIDER_TYPE_UNSPECIFIED":  0,
		"PROVIDER_TYPE_OTP":          1,
		"PROVIDER_TYPE_APPROVAL":     2,
		"PROVIDER_TYPE_MOBILE_ID":    3,
		"PROVIDER_TYPE_WEBAUTHN":     4,
		"PROVIDER_TYPE_OIDC":         5,
		"PROVIDER_TYPE_SAML":         6,
		"PROVIDER_TYPE_PASSWORD":     7,
		"PROVIDER_TYPE_NOTIFICATION": 8,
	}
)

func (x ProviderType) Enum() *ProviderType {
	p := new(ProviderType)
	*p = x
	return p
}

func (x ProviderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderType) Descriptor() protoreflect.EnumDescriptor {
	return file_m8_platform_iam_v1_authentication_provider_context_proto_enumTypes[0].Descriptor()
}

func (ProviderType) Type() protoreflect.EnumType {
	return &file_m8_platform_iam_v1_authentication_provider_context_proto_enumTypes[0]
}

func (x ProviderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProviderType.Descriptor instead.
func (ProviderType) EnumDescriptor() ([]byte, []int) {
	return file_m8_platform_iam_v1_authentication_provider_context_proto_rawDescGZIP(), []int{0}
}

// Runtime health of an authentication provider.
type ProviderHealth int32

const (
	// Provider health is not specified.
	ProviderHealth_PROVIDER_HEALTH_UNSPECIFIED ProviderHealth = 0
	// Provider health is unknown.
	ProviderHealth_PROVIDER_HEALTH_UNKNOWN ProviderHealth = 1
	// Provider is healthy.
	ProviderHealth_PROVIDER_HEALTH_HEALTHY ProviderHealth = 2
	// Provider is degraded but may still be used.
	ProviderHealth_PROVIDER_HEALTH_DEGRADED ProviderHealth = 3
	// Provider is unavailable.
	ProviderHealth_PROVIDER_HEALTH_UNAVAILABLE ProviderHealth = 4
	// Provider is disabled by configuration or policy.
	ProviderHealth_PROVIDER_HEALTH_DISABLED ProviderHealth = 5
)

// Enum value maps for ProviderHealth.
var (
	ProviderHealth_name = map[int32]string{
		0: "PROVIDER_HEALTH_UNSPECIFIED",
		1: "PROVIDER_HEALTH_UNKNOWN",
		2: "PROVIDER_HEALTH_HEALTHY",
		3: "PROVIDER_HEALTH_DEGRADED",
		4: "PROVIDER_HEALTH_UNAVAILABLE",
		5: "PROVIDER_HEALTH_DISABLED",
	}
	ProviderHealth_value = map[string]int32{
		"PROVIDER_HEALTH_UNSPECIFIED": 0,
		"PROVIDER_HEALTH_UNKNOWN":     1,
		"PROVIDER_HEALTH_HEALTHY":     2,
		"PROVIDER_HEALTH_DEGRADED":    3,
		"PROVIDER_HEALTH_UNAVAILABLE": 4,
		"PROVIDER_HEALTH_DISABLED":    5,
	}
)

func (x ProviderHealth) Enum() *ProviderHealth {
	p := new(ProviderHealth)
	*p = x
	return p
}

func (x ProviderHealth) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderHealth) Descriptor() protoreflect.EnumDescriptor {
	return file_m8_platform_iam_v1_authentication_provider_context_proto_enumTypes[1].Descriptor()
}

func (ProviderHealth) Type() protoreflect.EnumType {
	return &file_m8_platform_iam_v1_authentication_provider_context_proto_enumTypes[1]
}

func (x ProviderHealth) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProviderHealth.Descriptor instead.
func (ProviderHealth) EnumDescriptor() ([]byte, []int) {
	return file_m8_platform_iam_v1_authentication_provider_context_proto_rawDescGZIP(), []int{1}
}

// Mobile ID execution mode selected for the provider.
type MobileIdMode int32

const (
	// Mobile ID mode is not specified.
	MobileIdMode_MOBILE_ID_MODE_UNSPECIFIED MobileIdMode = 0
	// Provider may choose the best supported Mobile ID mode.
	MobileIdMode_MOBILE_ID_MODE_AUTO MobileIdMode = 1
	// Mobile ID uses operator SIM-push approval.
	MobileIdMode_MOBILE_ID_MODE_SIM_PUSH MobileIdMode = 2
	// Mobile ID uses SMS OTP fallback.
	MobileIdMode_MOBILE_ID_MODE_SMS_OTP MobileIdMode = 3
	// Mobile ID uses silent operator verification when supported.
	MobileIdMode_MOBILE_ID_MODE_SILENT MobileIdMode = 4
	// Mobile ID is not supported for the current subject or operator.
	MobileIdMode_MOBILE_ID_MODE_UNSUPPORTED MobileIdMode = 5
)

// Enum value maps for MobileIdMode.
var (
	MobileIdMode_name = map[int32]string{
		0: "MOBILE_ID_MODE_UNSPECIFIED",
		1: "MOBILE_ID_MODE_AUTO",
		2: "MOBILE_ID_MODE_SIM_PUSH",
		3: "MOBILE_ID_MODE_SMS_OTP",
		4: "MOBILE_ID_MODE_SILENT",
		5: "MOBILE_ID_MODE_UNSUPPORTED",
	}
	MobileIdMode_value = map[string]int32{
		"MOBILE_ID_MODE_UNSPECIFIED": 0,
		"MOBILE_ID_MODE_AUTO":        1,
		"MOBILE_ID_MODE_SIM_PUSH":    2,
		"MOBILE_ID_MODE_SMS_OTP":     3,
		"MOBILE_ID_MODE_SILENT":      4,
		"MOBILE_ID_MODE_UNSUPPORTED": 5,
	}
)

func (x MobileIdMode) Enum() *MobileIdMode {
	p := new(MobileIdMode)
	*p = x
	return p
}

func (x MobileIdMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MobileIdMode) Descriptor() protoreflect.EnumDescriptor {
	return file_m8_platform_iam_v1_authentication_provider_context_proto_enumTypes[2].Descriptor()
}

func (MobileIdMode) Type() protoreflect.EnumType {
	return &file_m8_platform_iam_v1_authentication_provider_context_proto_enumTypes[2]
}

func (x MobileIdMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MobileIdMode.Descriptor instead.
func (MobileIdMode) EnumDescriptor() ([]byte, []int) {
	return file_m8_platform_iam_v1_authentication_provider_context_proto_rawDescGZIP(), []int{2}
}

// ProviderDecisionContext captures provider selection and execution health.
//
// Example:
// - Mobile ID provider selected in SIM-push mode
// - SMS OTP fallback selected after Mobile ID degradation
// - provider transaction id is stored for correlation
type ProviderDecisionContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Channel identifier used by the authentication configuration.
	ChannelId string `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// Provider identifier selected for the current challenge.
	ProviderId string `protobuf:"bytes,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	// Type of selected provider.
	ProviderType ProviderType `protobuf:"varint,3,opt,name=provider_type,json=providerType,proto3,enum=m8.platform.iam.v1.ProviderType" json:"provider_type,omitempty"`
	// Current provider health.
	Health ProviderHealth `protobuf:"varint,4,opt,name=health,proto3,enum=m8.platform.iam.v1.ProviderHealth" json:"health,omitempty"`
	// Provider transaction identifier for correlation; not a secret.
	ProviderTransactionId string `protobuf:"bytes,5,opt,name=provider_transaction_id,json=providerTransactionId,proto3" json:"provider_transaction_id,omitempty"`
	// Mobile ID execution mode when provider_type is Mobile ID.
	MobileIdMode MobileIdMode `protobuf:"varint,6,opt,name=mobile_id_mode,json=mobileIdMode,proto3,enum=m8.platform.iam.v1.MobileIdMode" json:"mobile_id_mode,omitempty"`
	// Mobile network context for Mobile ID decisions.
	MobileNetwork *MobileNetworkContext `protobuf:"bytes,7,opt,name=mobile_network,json=mobileNetwork,proto3" json:"mobile_network,omitempty"`
	// Provider metrics used during selection.
	Metrics *ProviderMetrics `protobuf:"bytes,8,opt,name=metrics,proto3" json:"metrics,omitempty"`
	// Additional non-sensitive provider attributes.
	Attributes    map[string]string `protobuf:"bytes,9,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderDecisionContext) Reset() {
	*x = ProviderDecisionContext{}
	mi := &file_m8_platform_iam_v1_authentication_provider_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderDecisionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderDecisionContext) ProtoMessage() {}

func (x *ProviderDecisionContext) ProtoReflect() protoreflect.Message {
	mi := &file_m8_platform_iam_v1_authentication_provider_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderDecisionContext.ProtoReflect.Descriptor instead.
func (*ProviderDecisionContext) Descriptor() ([]byte, []int) {
	return file_m8_platform_iam_v1_authentication_provider_context_proto_rawDescGZIP(), []int{0}
}

func (x *ProviderDecisionContext) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ProviderDecisionContext) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *ProviderDecisionContext) GetProviderType() ProviderType {
	if x != nil {
		return x.ProviderType
	}
	return ProviderType_PROVIDER_TYPE_UNSPECIFIED
}

func (x *ProviderDecisionContext) GetHealth() ProviderHealth {
	if x != nil {
		return x.Health
	}
	return ProviderHealth_PROVIDER_HEALTH_UNSPECIFIED
}

func (x *ProviderDecisionContext) GetProviderTransactionId() string {
	if x != nil {
		return x.ProviderTransactionId
	}
	return ""
}

func (x *ProviderDecisionContext) GetMobileIdMode() MobileIdMode {
	if x != nil {
		return x.MobileIdMode
	}
	return MobileIdMode_MOBILE_ID_MODE_UNSPECIFIED
}

func (x *ProviderDecisionContext) GetMobileNetwork() *MobileNetworkContext {
	if x != nil {
		return x.MobileNetwork
	}
	return nil
}

func (x *ProviderDecisionContext) GetMetrics() *ProviderMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *ProviderDecisionContext) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// MobileNetworkContext captures operator-level Mobile ID signals without raw PII.
type MobileNetworkContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Mobile country code.
	Mcc string `protobuf:"bytes,1,opt,name=mcc,proto3" json:"mcc,omitempty"`
	// Mobile network code.
	Mnc string `protobuf:"bytes,2,opt,name=mnc,proto3" json:"mnc,omitempty"`
	// Operator display name.
	OperatorName string `protobuf:"bytes,3,opt,name=operator_name,json=operatorName,proto3" json:"operator_name,omitempty"`
	// ISO 3166 country code for the mobile network.
	CountryCode string `protobuf:"bytes,4,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	// Hash of MSISDN or phone number; raw number must not be stored here.
	MsisdnHash string `protobuf:"bytes,5,opt,name=msisdn_hash,json=msisdnHash,proto3" json:"msisdn_hash,omitempty"`
	// Whether the subscriber appears to be roaming.
	Roaming bool `protobuf:"varint,6,opt,name=roaming,proto3" json:"roaming,omitempty"`
	// Age of SIM swap signal in seconds when known.
	SimSwapAgeSeconds int64 `protobuf:"varint,7,opt,name=sim_swap_age_seconds,json=simSwapAgeSeconds,proto3" json:"sim_swap_age_seconds,omitempty"`
	// Additional non-sensitive mobile network attributes.
	Attributes    map[string]string `protobuf:"bytes,8,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MobileNetworkContext) Reset() {
	*x = MobileNetworkContext{}
	mi := &file_m8_platform_iam_v1_authentication_provider_context_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MobileNetworkContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MobileNetworkContext) ProtoMessage() {}

func (x *MobileNetworkContext) ProtoReflect() protoreflect.Message {
	mi := &file_m8_platform_iam_v1_authentication_provider_context_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MobileNetworkContext.ProtoReflect.Descriptor instead.
func (*MobileNetworkContext) Descriptor() ([]byte, []int) {
	return file_m8_platform_iam_v1_authentication_provider_context_proto_rawDescGZIP(), []int{1}
}

func (x *MobileNetworkContext) GetMcc() string {
	if x != nil {
		return x.Mcc
	}
	return ""
}

func (x *MobileNetworkContext) GetMnc() string {
	if x != nil {
		return x.Mnc
	}
	return ""
}

func (x *MobileNetworkContext) GetOperatorName() string {
	if x != nil {
		return x.OperatorName
	}
	return ""
}

func (x *MobileNetworkContext) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *MobileNetworkContext) GetMsisdnHash() string {
	if x != nil {
		return x.MsisdnHash
	}
	return ""
}

func (x *MobileNetworkContext) GetRoaming() bool {
	if x != nil {
		return x.Roaming
	}
	return false
}

func (x *MobileNetworkContext) GetSimSwapAgeSeconds() int64 {
	if x != nil {
		return x.SimSwapAgeSeconds
	}
	return 0
}

func (x *MobileNetworkContext) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// ProviderMetrics captures operational signals used for provider selection.
type ProviderMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Last observed provider latency in milliseconds.
	LatencyMs int64 `protobuf:"varint,1,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	// Recent provider error rate.
	ErrorRate float64 `protobuf:"fixed64,2,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	// Recent provider success rate.
	SuccessRate float64 `protobuf:"fixed64,3,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	// Time of last successful provider interaction.
	LastSuccessAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_success_at,json=lastSuccessAt,proto3" json:"last_success_at,omitempty"`
	// Time of last failed provider interaction.
	LastFailureAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_failure_at,json=lastFailureAt,proto3" json:"last_failure_at,omitempty"`
	// Consecutive provider failures observed before decision.
	ConsecutiveFailures int32 `protobuf:"varint,6,opt,name=consecutive_failures,json=consecutiveFailures,proto3" json:"consecutive_failures,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProviderMetrics) Reset() {
	*x = ProviderMetrics{}
	mi := &file_m8_platform_iam_v1_authentication_provider_context_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderMetrics) ProtoMessage() {}

func (x *ProviderMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_m8_platform_iam_v1_authentication_provider_context_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderMetrics.ProtoReflect.Descriptor instead.
func (*ProviderMetrics) Descriptor() ([]byte, []int) {
	return file_m8_platform_iam_v1_authentication_provider_context_proto_rawDescGZIP(), []int{2}
}

func (x *ProviderMetrics) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *ProviderMetrics) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

func (x *ProviderMetrics) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *ProviderMetrics) GetLastSuccessAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSuccessAt
	}
	return nil
}

func (x *ProviderMetrics) GetLastFailureAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastFailureAt
	}
	return nil
}

func (x *ProviderMetrics) GetConsecutiveFailures() int32 {
	if x != nil {
		return x.ConsecutiveFailures
	}
	return 0
}

var File_m8_platform_iam_v1_authentication_provider_context_proto protoreflect.FileDescriptor

const file_m8_platform_iam_v1_authentication_provider_context_proto_rawDesc = "" +
	"\n" +
	"8m8/platform/iam/v1/authentication_provider_context.proto\x12\x12m8.platform.iam.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x88\x05\n" +
	"\x17ProviderDecisionContext\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x1f\n" +
	"\vprovider_id\x18\x02 \x01(\tR\n" +
	"providerId\x12E\n" +
	"\rprovider_type\x18\x03 \x01(\x0e2 .m8.platform.iam.v1.ProviderTypeR\fproviderType\x12:\n" +
	"\x06health\x18\x04 \x01(\x0e2\".m8.platform.iam.v1.ProviderHealthR\x06health\x126\n" +
	"\x17provider_transaction_id\x18\x05 \x01(\tR\x15providerTransactionId\x12F\n" +
	"\x0emobile_id_mode\x18\x06 \x01(\x0e2 .m8.platform.iam.v1.MobileIdModeR\fmobileIdMode\x12O\n" +
	"\x0emobile_network\x18\a \x01(\v2(.m8.platform.iam.v1.MobileNetworkContextR\rmobileNetwork\x12=\n" +
	"\ametrics\x18\b \x01(\v2#.m8.platform.iam.v1.ProviderMetricsR\ametrics\x12[\n" +
	"\n" +
	"attributes\x18\t \x03(\v2;.m8.platform.iam.v1.ProviderDecisionContext.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x03\n" +
	"\x14MobileNetworkContext\x12\x10\n" +
	"\x03mcc\x18\x01 \x01(\tR\x03mcc\x12\x10\n" +
	"\x03mnc\x18\x02 \x01(\tR\x03mnc\x12#\n" +
	"\roperator_name\x18\x03 \x01(\tR\foperatorName\x12!\n" +
	"\fcountry_code\x18\x04 \x01(\tR\vcountryCode\x12\x1f\n" +
	"\vmsisdn_hash\x18\x05 \x01(\tR\n" +
	"msisdnHash\x12\x18\n" +
	"\aroaming\x18\x06 \x01(\bR\aroaming\x12/\n" +
	"\x14sim_swap_age_seconds\x18\a \x01(\x03R\x11simSwapAgeSeconds\x12X\n" +
	"\n" +
	"attributes\x18\b \x03(\v28.m8.platform.iam.v1.MobileNetworkContext.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xad\x02\n" +
	"\x0fProviderMetrics\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x01 \x01(\x03R\tlatencyMs\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x02 \x01(\x01R\terrorRate\x12!\n" +
	"\fsuccess_rate\x18\x03 \x01(\x01R\vsuccessRate\x12B\n" +
	"\x0flast_success_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rlastSuccessAt\x12B\n" +
	"\x0flast_failure_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rlastFailureAt\x121\n" +
	"\x14consecutive_failures\x18\x06 \x01(\x05R\x13consecutiveFailures*\x85\x02\n" +
	"\fProviderType\x12\x1d\n" +
	"\x19PROVIDER_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PROVIDER_TYPE_OTP\x10\x01\x12\x1a\n" +
	"\x16PROVIDER_TYPE_APPROVAL\x10\x02\x12\x1b\n" +
	"\x17PROVIDER_TYPE_MOBILE_ID\x10\x03\x12\x1a\n" +
	"\x16PROVIDER_TYPE_WEBAUTHN\x10\x04\x12\x16\n" +
	"\x12PROVIDER_TYPE_OIDC\x10\x05\x12\x16\n" +
	"\x12PROVIDER_TYPE_SAML\x10\x06\x12\x1a\n" +
	"\x16PROVIDER_TYPE_PASSWORD\x10\a\x12\x1e\n" +
	"\x1aPROVIDER_TYPE_NOTIFICATION\x10\b*\xc8\x01\n" +
	"\x0eProviderHealth\x12\x1f\n" +
	"\x1bPROVIDER_HEALTH_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PROVIDER_HEALTH_UNKNOWN\x10\x01\x12\x1b\n" +
	"\x17PROVIDER_HEALTH_HEALTHY\x10\x02\x12\x1c\n" +
	"\x18PROVIDER_HEALTH_DEGRADED\x10\x03\x12\x1f\n" +
	"\x1bPROVIDER_HEALTH_UNAVAILABLE\x10\x04\x12\x1c\n" +
	"\x18PROVIDER_HEALTH_DISABLED\x10\x05*\xbb\x01\n" +
	"\fMobileIdMode\x12\x1e\n" +
	"\x1aMOBILE_ID_MODE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13MOBILE_ID_MODE_AUTO\x10\x01\x12\x1b\n" +
	"\x17MOBILE_ID_MODE_SIM_PUSH\x10\x02\x12\x1a\n" +
	"\x16MOBILE_ID_MODE_SMS_OTP\x10\x03\x12\x19\n" +
	"\x15MOBILE_ID_MODE_SILENT\x10\x04\x12\x1e\n" +
	"\x1aMOBILE_ID_MODE_UNSUPPORTED\x10\x05B7Z5github.com/m8-team/go-genproto/m8/platform/iam/v1;iamb\x06proto3"

var (
	file_m8_platform_iam_v1_authentication_provider_context_proto_rawDescOnce sync.Once
	file_m8_platform_iam_v1_authentication_provider_context_proto_rawDescData []byte
)

func file_m8_platform_iam_v1_authentication_provider_context_proto_rawDescGZIP() []byte {
	file_m8_platform_iam_v1_authentication_provider_context_proto_rawDescOnce.Do(func() {
		file_m8_platform_iam_v1_authentication_provider_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_m8_platform_iam_v1_authentication_provider_context_proto_rawDesc), len(file_m8_platform_iam_v1_authentication_provider_context_proto_rawDesc)))
	})
	return file_m8_platform_iam_v1_authentication_provider_context_proto_rawDescData
}

var file_m8_platform_iam_v1_authentication_provider_context_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_m8_platform_iam_v1_authentication_provider_context_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_m8_platform_iam_v1_authentication_provider_context_proto_goTypes = []any{
	(ProviderType)(0),               // 0: m8.platform.iam.v1.ProviderType
	(ProviderHealth)(0),             // 1: m8.platform.iam.v1.ProviderHealth
	(MobileIdMode)(0),               // 2: m8.platform.iam.v1.MobileIdMode
	(*ProviderDecisionContext)(nil), // 3: m8.platform.iam.v1.ProviderDecisionContext
	(*MobileNetworkContext)(nil),    // 4: m8.platform.iam.v1.MobileNetworkContext
	(*ProviderMetrics)(nil),         // 5: m8.platform.iam.v1.ProviderMetrics
	nil,                             // 6: m8.platform.iam.v1.ProviderDecisionContext.AttributesEntry
	nil,                             // 7: m8.platform.iam.v1.MobileNetworkContext.AttributesEntry
	(*timestamppb.Timestamp)(nil),   // 8: google.protobuf.Timestamp
}
var file_m8_platform_iam_v1_authentication_provider_context_proto_depIdxs = []int32{
	0, // 0: m8.platform.iam.v1.ProviderDecisionContext.provider_type:type_name -> m8.platform.iam.v1.ProviderType
	1, // 1: m8.platform.iam.v1.ProviderDecisionContext.health:type_name -> m8.platform.iam.v1.ProviderHealth
	2, // 2: m8.platform.iam.v1.ProviderDecisionContext.mobile_id_mode:type_name -> m8.platform.iam.v1.MobileIdMode
	4, // 3: m8.platform.iam.v1.ProviderDecisionContext.mobile_network:type_name -> m8.platform.iam.v1.MobileNetworkContext
	5, // 4: m8.platform.iam.v1.ProviderDecisionContext.metrics:type_name -> m8.platform.iam.v1.ProviderMetrics
	6, // 5: m8.platform.iam.v1.ProviderDecisionContext.attributes:type_name -> m8.platform.iam.v1.ProviderDecisionContext.AttributesEntry
	7, // 6: m8.platform.iam.v1.MobileNetworkContext.attributes:type_name -> m8.platform.iam.v1.MobileNetworkContext.AttributesEntry
	8, // 7: m8.platform.iam.v1.ProviderMetrics.last_success_at:type_name -> google.protobuf.Timestamp
	8, // 8: m8.platform.iam.v1.ProviderMetrics.last_failure_at:type_name -> google.protobuf.Timestamp
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_m8_platform_iam_v1_authentication_provider_context_proto_init() }
func file_m8_platform_iam_v1_authentication_provider_context_proto_init() {
	if File_m8_platform_iam_v1_authentication_provider_context_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_m8_platform_iam_v1_authentication_provider_context_proto_rawDesc), len(file_m8_platform_iam_v1_authentication_provider_context_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_m8_platform_iam_v1_authentication_provider_context_proto_goTypes,
		DependencyIndexes: file_m8_platform_iam_v1_authentication_provider_context_proto_depIdxs,
		EnumInfos:         file_m8_platform_iam_v1_authentication_provider_context_proto_enumTypes,
		MessageInfos:      file_m8_platform_iam_v1_authentication_provider_context_proto_msgTypes,
	}.Build()
	File_m8_platform_iam_v1_authentication_provider_context_proto = out.File
	file_m8_platform_iam_v1_authentication_provider_context_proto_goTypes = nil
	file_m8_platform_iam_v1_authentication_provider_context_proto_depIdxs = nil
}
