// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: m8/platform/iam/v1/authentication_service.proto

package iam

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	_ "github.com/google/gnostic/openapiv3"
	_ "github.com/m8-team/go-genproto/m8/platform/extension/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to start an authentication operation.
type StartAuthenticationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Public client application identifier that initiates authentication.
	// The value must be a UUID.
	//
	// The server resolves this value to ClientConfig, project_id, user_pool_id,
	// allowed providers, allowed methods, and authentication policies.
	// Clients must not send project_id or user_pool_id in StartAuthenticationRequest.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Optional. Subject identifier or hint used to resolve the authenticating user.
	Subject *AuthenticationSubject `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	// Optional. Additional authentication context used for policy and challenge selection.
	Context *AuthenticationContext `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	// Optional. Client preferences that influence authentication workflow selection.
	Options *AuthenticationStartOptions `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	// Optional. Idempotency key for StartAuthentication retries.
	//
	// The same client_id and request_id must resolve to the same Authentication
	// operation. When omitted, retries are not guaranteed to be idempotent.
	RequestId     string `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartAuthenticationRequest) Reset() {
	*x = StartAuthenticationRequest{}
	mi := &file_m8_platform_iam_v1_authentication_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAuthenticationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAuthenticationRequest) ProtoMessage() {}

func (x *StartAuthenticationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_m8_platform_iam_v1_authentication_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAuthenticationRequest.ProtoReflect.Descriptor instead.
func (*StartAuthenticationRequest) Descriptor() ([]byte, []int) {
	return file_m8_platform_iam_v1_authentication_service_proto_rawDescGZIP(), []int{0}
}

func (x *StartAuthenticationRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *StartAuthenticationRequest) GetSubject() *AuthenticationSubject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *StartAuthenticationRequest) GetContext() *AuthenticationContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *StartAuthenticationRequest) GetOptions() *AuthenticationStartOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *StartAuthenticationRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Request to read the latest authentication operation snapshot.
type GetAuthenticationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Stable unique identifier of the authentication operation to read.
	// The value must be a valid UUID string.
	//
	// The server returns the latest known aggregate snapshot. This request does
	// not change authentication state and is safe for client or BFF polling.
	//
	// Example:
	//
	//	{
	//	  "authentication_id": "7b0b93f5-6f4a-4c5b-9a9d-2b58a67e1c34"
	//	}
	AuthenticationId string `protobuf:"bytes,1,opt,name=authentication_id,json=authenticationId,proto3" json:"authentication_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetAuthenticationRequest) Reset() {
	*x = GetAuthenticationRequest{}
	mi := &file_m8_platform_iam_v1_authentication_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthenticationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthenticationRequest) ProtoMessage() {}

func (x *GetAuthenticationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_m8_platform_iam_v1_authentication_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthenticationRequest.ProtoReflect.Descriptor instead.
func (*GetAuthenticationRequest) Descriptor() ([]byte, []int) {
	return file_m8_platform_iam_v1_authentication_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetAuthenticationRequest) GetAuthenticationId() string {
	if x != nil {
		return x.AuthenticationId
	}
	return ""
}

// Request to cancel an active authentication operation.
type CancelAuthenticationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Stable unique identifier of the authentication operation to cancel.
	// The value must be a valid UUID string.
	AuthenticationId string `protobuf:"bytes,1,opt,name=authentication_id,json=authenticationId,proto3" json:"authentication_id,omitempty"`
	// Optional. Human-readable or machine-readable reason for cancellation.
	//
	// Example:
	// - "user_closed_login_window"
	// - "client_restarted_flow"
	// - "session_replaced"
	// - "admin_requested"
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// Optional. Idempotency key for retrying cancellation.
	//
	// CancelAuthentication is naturally idempotent for terminal states, but
	// request_id allows the server to deduplicate concurrent cancellation attempts.
	// The same authentication_id and request_id must resolve to the same
	// cancellation result.
	//
	// Example:
	//
	//	{
	//	  "authentication_id": "7b0b93f5-6f4a-4c5b-9a9d-2b58a67e1c34",
	//	  "reason": "user_closed_login_window",
	//	  "request_id": "0d8b7e3e-7e1c-4b7e-8a8f-1f3c2c4f9d11"
	//	}
	RequestId     string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelAuthenticationRequest) Reset() {
	*x = CancelAuthenticationRequest{}
	mi := &file_m8_platform_iam_v1_authentication_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelAuthenticationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAuthenticationRequest) ProtoMessage() {}

func (x *CancelAuthenticationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_m8_platform_iam_v1_authentication_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAuthenticationRequest.ProtoReflect.Descriptor instead.
func (*CancelAuthenticationRequest) Descriptor() ([]byte, []int) {
	return file_m8_platform_iam_v1_authentication_service_proto_rawDescGZIP(), []int{2}
}

func (x *CancelAuthenticationRequest) GetAuthenticationId() string {
	if x != nil {
		return x.AuthenticationId
	}
	return ""
}

func (x *CancelAuthenticationRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CancelAuthenticationRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Request to resend the current authentication challenge.
type ResendAuthenticationChallengeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Identifier of the authentication operation.
	AuthenticationId string `protobuf:"bytes,1,opt,name=authentication_id,json=authenticationId,proto3" json:"authentication_id,omitempty"`
	// Required. Identifier of the challenge to resend.
	//
	// The value must match Authentication.current_challenge.challenge_id.
	ChallengeId string `protobuf:"bytes,2,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	// Optional. Idempotency key for retrying resend safely.
	//
	// The same authentication_id, challenge_id, and request_id must resolve to the
	// same resend result.
	RequestId     string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResendAuthenticationChallengeRequest) Reset() {
	*x = ResendAuthenticationChallengeRequest{}
	mi := &file_m8_platform_iam_v1_authentication_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResendAuthenticationChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResendAuthenticationChallengeRequest) ProtoMessage() {}

func (x *ResendAuthenticationChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_m8_platform_iam_v1_authentication_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResendAuthenticationChallengeRequest.ProtoReflect.Descriptor instead.
func (*ResendAuthenticationChallengeRequest) Descriptor() ([]byte, []int) {
	return file_m8_platform_iam_v1_authentication_service_proto_rawDescGZIP(), []int{3}
}

func (x *ResendAuthenticationChallengeRequest) GetAuthenticationId() string {
	if x != nil {
		return x.AuthenticationId
	}
	return ""
}

func (x *ResendAuthenticationChallengeRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *ResendAuthenticationChallengeRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Request to select another authentication method or provider.
type SelectAuthenticationChallengeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Identifier of the authentication operation.
	AuthenticationId string `protobuf:"bytes,1,opt,name=authentication_id,json=authenticationId,proto3" json:"authentication_id,omitempty"`
	// Required. Authentication method selected by the client or user.
	Method AuthenticationMethod `protobuf:"varint,2,opt,name=method,proto3,enum=m8.platform.iam.v1.AuthenticationMethod" json:"method,omitempty"`
	// Optional. Provider identifier for provider-based methods.
	//
	// Example:
	// - "google"
	// - "saml-corp"
	// - "mobile-id-at"
	// - "m8-sms"
	ProviderId string `protobuf:"bytes,3,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	// Optional. Idempotency key for retrying selection safely.
	//
	// The same authentication_id, method, provider_id, and request_id must resolve
	// to the same selection result.
	RequestId     string `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectAuthenticationChallengeRequest) Reset() {
	*x = SelectAuthenticationChallengeRequest{}
	mi := &file_m8_platform_iam_v1_authentication_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectAuthenticationChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectAuthenticationChallengeRequest) ProtoMessage() {}

func (x *SelectAuthenticationChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_m8_platform_iam_v1_authentication_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectAuthenticationChallengeRequest.ProtoReflect.Descriptor instead.
func (*SelectAuthenticationChallengeRequest) Descriptor() ([]byte, []int) {
	return file_m8_platform_iam_v1_authentication_service_proto_rawDescGZIP(), []int{4}
}

func (x *SelectAuthenticationChallengeRequest) GetAuthenticationId() string {
	if x != nil {
		return x.AuthenticationId
	}
	return ""
}

func (x *SelectAuthenticationChallengeRequest) GetMethod() AuthenticationMethod {
	if x != nil {
		return x.Method
	}
	return AuthenticationMethod_AUTHENTICATION_METHOD_UNSPECIFIED
}

func (x *SelectAuthenticationChallengeRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *SelectAuthenticationChallengeRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Request to submit the current authentication challenge response.
type SubmitAuthenticationChallengeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Stable unique identifier of the authentication operation.
	AuthenticationId string `protobuf:"bytes,1,opt,name=authentication_id,json=authenticationId,proto3" json:"authentication_id,omitempty"`
	// Required. Identifier of the current challenge being answered.
	//
	// The value must match Authentication.current_challenge.challenge_id.
	ChallengeId string `protobuf:"bytes,2,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	// Required. Response or proof for the current challenge. Raw passwords and
	// OTP codes are accepted only in this request and must never be returned in
	// Authentication, AuthenticationContext, AuthenticationChallengeInfo, or
	// AuthenticationError.
	//
	// Types that are valid to be assigned to Response:
	//
	//	*SubmitAuthenticationChallengeRequest_Otp
	//	*SubmitAuthenticationChallengeRequest_Password
	//	*SubmitAuthenticationChallengeRequest_Webauthn
	//	*SubmitAuthenticationChallengeRequest_Approval
	Response isSubmitAuthenticationChallengeRequest_Response `protobuf_oneof:"response"`
	// Optional. Idempotency key for retrying challenge submission safely.
	RequestId     string `protobuf:"bytes,100,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAuthenticationChallengeRequest) Reset() {
	*x = SubmitAuthenticationChallengeRequest{}
	mi := &file_m8_platform_iam_v1_authentication_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAuthenticationChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAuthenticationChallengeRequest) ProtoMessage() {}

func (x *SubmitAuthenticationChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_m8_platform_iam_v1_authentication_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAuthenticationChallengeRequest.ProtoReflect.Descriptor instead.
func (*SubmitAuthenticationChallengeRequest) Descriptor() ([]byte, []int) {
	return file_m8_platform_iam_v1_authentication_service_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitAuthenticationChallengeRequest) GetAuthenticationId() string {
	if x != nil {
		return x.AuthenticationId
	}
	return ""
}

func (x *SubmitAuthenticationChallengeRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *SubmitAuthenticationChallengeRequest) GetResponse() isSubmitAuthenticationChallengeRequest_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *SubmitAuthenticationChallengeRequest) GetOtp() *OtpChallengeResponse {
	if x != nil {
		if x, ok := x.Response.(*SubmitAuthenticationChallengeRequest_Otp); ok {
			return x.Otp
		}
	}
	return nil
}

func (x *SubmitAuthenticationChallengeRequest) GetPassword() *PasswordChallengeResponse {
	if x != nil {
		if x, ok := x.Response.(*SubmitAuthenticationChallengeRequest_Password); ok {
			return x.Password
		}
	}
	return nil
}

func (x *SubmitAuthenticationChallengeRequest) GetWebauthn() *WebAuthnAssertionResponse {
	if x != nil {
		if x, ok := x.Response.(*SubmitAuthenticationChallengeRequest_Webauthn); ok {
			return x.Webauthn
		}
	}
	return nil
}

func (x *SubmitAuthenticationChallengeRequest) GetApproval() *ApprovalChallengeResponse {
	if x != nil {
		if x, ok := x.Response.(*SubmitAuthenticationChallengeRequest_Approval); ok {
			return x.Approval
		}
	}
	return nil
}

func (x *SubmitAuthenticationChallengeRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type isSubmitAuthenticationChallengeRequest_Response interface {
	isSubmitAuthenticationChallengeRequest_Response()
}

type SubmitAuthenticationChallengeRequest_Otp struct {
	// OTP code submitted by the user.
	Otp *OtpChallengeResponse `protobuf:"bytes,10,opt,name=otp,proto3,oneof"`
}

type SubmitAuthenticationChallengeRequest_Password struct {
	// Password submitted by the user.
	Password *PasswordChallengeResponse `protobuf:"bytes,11,opt,name=password,proto3,oneof"`
}

type SubmitAuthenticationChallengeRequest_Webauthn struct {
	// WebAuthn assertion produced by the browser or platform authenticator.
	Webauthn *WebAuthnAssertionResponse `protobuf:"bytes,12,opt,name=webauthn,proto3,oneof"`
}

type SubmitAuthenticationChallengeRequest_Approval struct {
	// Approval result submitted by an approval-capable client.
	Approval *ApprovalChallengeResponse `protobuf:"bytes,13,opt,name=approval,proto3,oneof"`
}

func (*SubmitAuthenticationChallengeRequest_Otp) isSubmitAuthenticationChallengeRequest_Response() {}

func (*SubmitAuthenticationChallengeRequest_Password) isSubmitAuthenticationChallengeRequest_Response() {
}

func (*SubmitAuthenticationChallengeRequest_Webauthn) isSubmitAuthenticationChallengeRequest_Response() {
}

func (*SubmitAuthenticationChallengeRequest_Approval) isSubmitAuthenticationChallengeRequest_Response() {
}

// OtpChallengeResponse contains an OTP code submitted by the user.
//
// It is request-only data and must never be returned in public snapshots.
type OtpChallengeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. One-time password code submitted for verification.
	Code          string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OtpChallengeResponse) Reset() {
	*x = OtpChallengeResponse{}
	mi := &file_m8_platform_iam_v1_authentication_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtpChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtpChallengeResponse) ProtoMessage() {}

func (x *OtpChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_m8_platform_iam_v1_authentication_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtpChallengeResponse.ProtoReflect.Descriptor instead.
func (*OtpChallengeResponse) Descriptor() ([]byte, []int) {
	return file_m8_platform_iam_v1_authentication_service_proto_rawDescGZIP(), []int{6}
}

func (x *OtpChallengeResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// PasswordChallengeResponse contains a password submitted by the user.
//
// It is request-only data and must never be returned, logged, or stored in the
// public authentication snapshot.
type PasswordChallengeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Password submitted for verification.
	Password      string `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordChallengeResponse) Reset() {
	*x = PasswordChallengeResponse{}
	mi := &file_m8_platform_iam_v1_authentication_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordChallengeResponse) ProtoMessage() {}

func (x *PasswordChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_m8_platform_iam_v1_authentication_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordChallengeResponse.ProtoReflect.Descriptor instead.
func (*PasswordChallengeResponse) Descriptor() ([]byte, []int) {
	return file_m8_platform_iam_v1_authentication_service_proto_rawDescGZIP(), []int{7}
}

func (x *PasswordChallengeResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// WebAuthnAssertionResponse contains the browser assertion response for a
// WebAuthn/passkey challenge.
type WebAuthnAssertionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Base64url-encoded credential identifier.
	CredentialId string `protobuf:"bytes,1,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	// Required. Base64url-encoded clientDataJSON.
	ClientDataJson string `protobuf:"bytes,2,opt,name=client_data_json,json=clientDataJson,proto3" json:"client_data_json,omitempty"`
	// Required. Base64url-encoded authenticatorData.
	AuthenticatorData string `protobuf:"bytes,3,opt,name=authenticator_data,json=authenticatorData,proto3" json:"authenticator_data,omitempty"`
	// Required. Base64url-encoded assertion signature.
	Signature string `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	// Optional. Base64url-encoded WebAuthn user handle, when supplied by the authenticator.
	UserHandle    string `protobuf:"bytes,5,opt,name=user_handle,json=userHandle,proto3" json:"user_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebAuthnAssertionResponse) Reset() {
	*x = WebAuthnAssertionResponse{}
	mi := &file_m8_platform_iam_v1_authentication_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebAuthnAssertionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebAuthnAssertionResponse) ProtoMessage() {}

func (x *WebAuthnAssertionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_m8_platform_iam_v1_authentication_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebAuthnAssertionResponse.ProtoReflect.Descriptor instead.
func (*WebAuthnAssertionResponse) Descriptor() ([]byte, []int) {
	return file_m8_platform_iam_v1_authentication_service_proto_rawDescGZIP(), []int{8}
}

func (x *WebAuthnAssertionResponse) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

func (x *WebAuthnAssertionResponse) GetClientDataJson() string {
	if x != nil {
		return x.ClientDataJson
	}
	return ""
}

func (x *WebAuthnAssertionResponse) GetAuthenticatorData() string {
	if x != nil {
		return x.AuthenticatorData
	}
	return ""
}

func (x *WebAuthnAssertionResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *WebAuthnAssertionResponse) GetUserHandle() string {
	if x != nil {
		return x.UserHandle
	}
	return ""
}

// ApprovalChallengeResponse contains an approval or denial result.
type ApprovalChallengeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. True when the user approved the challenge, false when denied.
	Approved      bool `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalChallengeResponse) Reset() {
	*x = ApprovalChallengeResponse{}
	mi := &file_m8_platform_iam_v1_authentication_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalChallengeResponse) ProtoMessage() {}

func (x *ApprovalChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_m8_platform_iam_v1_authentication_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalChallengeResponse.ProtoReflect.Descriptor instead.
func (*ApprovalChallengeResponse) Descriptor() ([]byte, []int) {
	return file_m8_platform_iam_v1_authentication_service_proto_rawDescGZIP(), []int{9}
}

func (x *ApprovalChallengeResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

// Request to process a callback from an external identity provider.
type HandleAuthenticationCallbackRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Provider identifier that produced the callback.
	//
	// Example:
	// - "google"
	// - "saml-corp"
	// - "mobile-id-at"
	ProviderId string `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	// Optional. Authentication operation identifier.
	//
	// Some providers allow resolving the authentication operation from state,
	// RelayState, or provider-specific transaction identifiers instead.
	AuthenticationId string `protobuf:"bytes,2,opt,name=authentication_id,json=authenticationId,proto3" json:"authentication_id,omitempty"`
	// Optional. OIDC or OAuth authorization code.
	//
	// The server exchanges this value internally if needed. It must not be
	// returned in public responses.
	Code string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	// Optional. OIDC or OAuth state value.
	//
	// The server validates this value internally for callback correlation and
	// anti-CSRF protection. It must not expose secrets.
	State string `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	// Optional. SAML response payload.
	//
	// This field may contain a large base64-encoded SAMLResponse. The server must
	// validate the assertion internally and must not return raw assertions in
	// public responses.
	SamlResponse string `protobuf:"bytes,5,opt,name=saml_response,json=samlResponse,proto3" json:"saml_response,omitempty"`
	// Optional. SAML RelayState value.
	RelayState string `protobuf:"bytes,6,opt,name=relay_state,json=relayState,proto3" json:"relay_state,omitempty"`
	// Optional. Raw query parameters received from the provider callback.
	//
	// This is useful for provider-specific integrations. Do not store or expose
	// secrets from this map in public responses.
	RawQuery map[string]string `protobuf:"bytes,7,rep,name=raw_query,json=rawQuery,proto3" json:"raw_query,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional. Raw form parameters received from the provider callback.
	//
	// This is useful for SAML POST binding and provider-specific callbacks. Do not
	// store or expose secrets from this map in public responses.
	RawForm map[string]string `protobuf:"bytes,8,rep,name=raw_form,json=rawForm,proto3" json:"raw_form,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional. Idempotency key for retrying callback handling safely.
	//
	// The same provider_id, callback state, code, relay_state, and request_id must
	// resolve to the same callback result.
	RequestId     string `protobuf:"bytes,9,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleAuthenticationCallbackRequest) Reset() {
	*x = HandleAuthenticationCallbackRequest{}
	mi := &file_m8_platform_iam_v1_authentication_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleAuthenticationCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleAuthenticationCallbackRequest) ProtoMessage() {}

func (x *HandleAuthenticationCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_m8_platform_iam_v1_authentication_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleAuthenticationCallbackRequest.ProtoReflect.Descriptor instead.
func (*HandleAuthenticationCallbackRequest) Descriptor() ([]byte, []int) {
	return file_m8_platform_iam_v1_authentication_service_proto_rawDescGZIP(), []int{10}
}

func (x *HandleAuthenticationCallbackRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *HandleAuthenticationCallbackRequest) GetAuthenticationId() string {
	if x != nil {
		return x.AuthenticationId
	}
	return ""
}

func (x *HandleAuthenticationCallbackRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *HandleAuthenticationCallbackRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *HandleAuthenticationCallbackRequest) GetSamlResponse() string {
	if x != nil {
		return x.SamlResponse
	}
	return ""
}

func (x *HandleAuthenticationCallbackRequest) GetRelayState() string {
	if x != nil {
		return x.RelayState
	}
	return ""
}

func (x *HandleAuthenticationCallbackRequest) GetRawQuery() map[string]string {
	if x != nil {
		return x.RawQuery
	}
	return nil
}

func (x *HandleAuthenticationCallbackRequest) GetRawForm() map[string]string {
	if x != nil {
		return x.RawForm
	}
	return nil
}

func (x *HandleAuthenticationCallbackRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Response returned after processing an external provider callback.
type HandleAuthenticationCallbackResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output only. Updated authentication snapshot.
	//
	// The snapshot must not contain provider tokens, raw assertions, client
	// secrets, internal callback secrets, OTP codes, or passwords.
	Authentication *Authentication `protobuf:"bytes,1,opt,name=authentication,proto3" json:"authentication,omitempty"`
	// Output only. Optional redirect URI where the browser should be redirected
	// after callback handling.
	//
	// This URI must be validated by the server against the original client
	// configuration and callback state.
	RedirectUri string `protobuf:"bytes,2,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	// Output only. Indicates whether the provider callback completed the
	// authentication operation.
	Completed     bool `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleAuthenticationCallbackResponse) Reset() {
	*x = HandleAuthenticationCallbackResponse{}
	mi := &file_m8_platform_iam_v1_authentication_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleAuthenticationCallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleAuthenticationCallbackResponse) ProtoMessage() {}

func (x *HandleAuthenticationCallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_m8_platform_iam_v1_authentication_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleAuthenticationCallbackResponse.ProtoReflect.Descriptor instead.
func (*HandleAuthenticationCallbackResponse) Descriptor() ([]byte, []int) {
	return file_m8_platform_iam_v1_authentication_service_proto_rawDescGZIP(), []int{11}
}

func (x *HandleAuthenticationCallbackResponse) GetAuthentication() *Authentication {
	if x != nil {
		return x.Authentication
	}
	return nil
}

func (x *HandleAuthenticationCallbackResponse) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *HandleAuthenticationCallbackResponse) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

// Metadata for the StartAuthentication long-running operation.
type StartAuthenticationOperationMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output only. Current snapshot of the authentication operation.
	//
	// The value is updated as the workflow advances through state transitions and
	// can be used by clients to poll progress before the operation completes.
	Authentication *Authentication `protobuf:"bytes,1,opt,name=authentication,proto3" json:"authentication,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartAuthenticationOperationMetadata) Reset() {
	*x = StartAuthenticationOperationMetadata{}
	mi := &file_m8_platform_iam_v1_authentication_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAuthenticationOperationMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAuthenticationOperationMetadata) ProtoMessage() {}

func (x *StartAuthenticationOperationMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_m8_platform_iam_v1_authentication_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAuthenticationOperationMetadata.ProtoReflect.Descriptor instead.
func (*StartAuthenticationOperationMetadata) Descriptor() ([]byte, []int) {
	return file_m8_platform_iam_v1_authentication_service_proto_rawDescGZIP(), []int{12}
}

func (x *StartAuthenticationOperationMetadata) GetAuthentication() *Authentication {
	if x != nil {
		return x.Authentication
	}
	return nil
}

// AuthenticationStartOptions contains optional client preferences for starting authentication.
//
// The server may use these values to select login experience, provider, method,
// and assurance requirements, but policy can override unsupported or disallowed
// preferences.
//
// Example:
//   - passkey-first login requests requested_authentication_method =
//     AUTHENTICATION_METHOD_WEBAUTHN_PASSKEY
//   - tenant-specific UI flow sends `login_experience_version`
//   - OIDC request passes acr_values requested by the relying party
type AuthenticationStartOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. Login experience version requested by the client.
	//
	// Example:
	// - "default"
	// - "passkey-first"
	// - "passwordless-v2"
	LoginExperienceVersion string `protobuf:"bytes,1,opt,name=login_experience_version,json=loginExperienceVersion,proto3" json:"login_experience_version,omitempty"`
	// Optional. Preferred standard authentication method requested by the client.
	//
	// Use requested_method_id for custom, provider, or plugin methods not modeled
	// by AuthenticationMethod.
	RequestedAuthenticationMethod AuthenticationMethod `protobuf:"varint,5,opt,name=requested_authentication_method,json=requestedAuthenticationMethod,proto3,enum=m8.platform.iam.v1.AuthenticationMethod" json:"requested_authentication_method,omitempty"`
	// Optional. Preferred custom, provider, or plugin method identifier.
	//
	// This complements requested_authentication_method and must be interpreted
	// against server-side client, provider, and policy configuration.
	RequestedMethodId string `protobuf:"bytes,6,opt,name=requested_method_id,json=requestedMethodId,proto3" json:"requested_method_id,omitempty"`
	// Optional. Preferred authentication provider identifier.
	// This selects a provider, channel, or provider integration for the requested
	// method. AuthenticationSubject.provider_id scopes subject identifiers and
	// must not be used to select the login provider.
	//
	// Example:
	// - WebAuthn provider id for passkey authentication
	// - OIDC provider id for external identity provider login
	// - Mobile ID provider id for mobile operator authentication
	RequestedProviderId string `protobuf:"bytes,2,opt,name=requested_provider_id,json=requestedProviderId,proto3" json:"requested_provider_id,omitempty"`
	// Optional. Requested Authentication Context Class Reference values.
	//
	// Example:
	// - "AAL1" for normal login
	// - "AAL2" for multi-factor authentication
	// - "AAL3" for hardware-backed phishing-resistant authentication
	AcrValues     []string `protobuf:"bytes,4,rep,name=acr_values,json=acrValues,proto3" json:"acr_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticationStartOptions) Reset() {
	*x = AuthenticationStartOptions{}
	mi := &file_m8_platform_iam_v1_authentication_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationStartOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationStartOptions) ProtoMessage() {}

func (x *AuthenticationStartOptions) ProtoReflect() protoreflect.Message {
	mi := &file_m8_platform_iam_v1_authentication_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationStartOptions.ProtoReflect.Descriptor instead.
func (*AuthenticationStartOptions) Descriptor() ([]byte, []int) {
	return file_m8_platform_iam_v1_authentication_service_proto_rawDescGZIP(), []int{13}
}

func (x *AuthenticationStartOptions) GetLoginExperienceVersion() string {
	if x != nil {
		return x.LoginExperienceVersion
	}
	return ""
}

func (x *AuthenticationStartOptions) GetRequestedAuthenticationMethod() AuthenticationMethod {
	if x != nil {
		return x.RequestedAuthenticationMethod
	}
	return AuthenticationMethod_AUTHENTICATION_METHOD_UNSPECIFIED
}

func (x *AuthenticationStartOptions) GetRequestedMethodId() string {
	if x != nil {
		return x.RequestedMethodId
	}
	return ""
}

func (x *AuthenticationStartOptions) GetRequestedProviderId() string {
	if x != nil {
		return x.RequestedProviderId
	}
	return ""
}

func (x *AuthenticationStartOptions) GetAcrValues() []string {
	if x != nil {
		return x.AcrValues
	}
	return nil
}

var File_m8_platform_iam_v1_authentication_service_proto protoreflect.FileDescriptor

const file_m8_platform_iam_v1_authentication_service_proto_rawDesc = "" +
	"\n" +
	"/m8/platform/iam/v1/authentication_service.proto\x12\x12m8.platform.iam.v1\x1a\x1bbuf/validate/validate.proto\x1a$gnostic/openapi/v3/annotations.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a#google/longrunning/operations.proto\x1a(m8/platform/extension/v1/extension.proto\x1a'm8/platform/iam/v1/authentication.proto\x1a1m8/platform/iam/v1/authentication_challenge.proto\x1a/m8/platform/iam/v1/authentication_context.proto\x1a/m8/platform/iam/v1/authentication_subject.proto\"\xdb\x02\n" +
	"\x1aStartAuthenticationRequest\x12+\n" +
	"\tclient_id\x18\x01 \x01(\tB\x0e\xe0A\x02\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\bclientId\x12H\n" +
	"\asubject\x18\x02 \x01(\v2).m8.platform.iam.v1.AuthenticationSubjectB\x03\xe0A\x01R\asubject\x12H\n" +
	"\acontext\x18\x03 \x01(\v2).m8.platform.iam.v1.AuthenticationContextB\x03\xe0A\x01R\acontext\x12M\n" +
	"\aoptions\x18\x04 \x01(\v2..m8.platform.iam.v1.AuthenticationStartOptionsB\x03\xe0A\x01R\aoptions\x12-\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tB\x0e\xe0A\x01\xbaH\b\xd8\x01\x01r\x03\xb0\x01\x01R\trequestId\"\\\n" +
	"\x18GetAuthenticationRequest\x12@\n" +
	"\x11authentication_id\x18\x01 \x01(\tB\x13\xe0A\x02\xbaH\r\xc8\x01\x01r\b\x10\x01\x18\xff\x01\xb0\x01\x01R\x10authenticationId\"\xb3\x01\n" +
	"\x1bCancelAuthenticationRequest\x12@\n" +
	"\x11authentication_id\x18\x01 \x01(\tB\x13\xe0A\x02\xbaH\r\xc8\x01\x01r\b\x10\x01\x18\xff\x01\xb0\x01\x01R\x10authenticationId\x12#\n" +
	"\x06reason\x18\x02 \x01(\tB\v\xe0A\x01\xbaH\x05r\x03\x18\x80\x04R\x06reason\x12-\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tB\x0e\xe0A\x01\xbaH\b\xd8\x01\x01r\x03\xb0\x01\x01R\trequestId\"\xcc\x01\n" +
	"$ResendAuthenticationChallengeRequest\x12@\n" +
	"\x11authentication_id\x18\x01 \x01(\tB\x13\xe0A\x02\xbaH\r\xc8\x01\x01r\b\x10\x01\x18\xff\x01\xb0\x01\x01R\x10authenticationId\x123\n" +
	"\fchallenge_id\x18\x02 \x01(\tB\x10\xe0A\x02\xbaH\n" +
	"\xc8\x01\x01r\x05\x10\x01\x18\xff\x01R\vchallengeId\x12-\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tB\x0e\xe0A\x01\xbaH\b\xd8\x01\x01r\x03\xb0\x01\x01R\trequestId\"\x96\x02\n" +
	"$SelectAuthenticationChallengeRequest\x12@\n" +
	"\x11authentication_id\x18\x01 \x01(\tB\x13\xe0A\x02\xbaH\r\xc8\x01\x01r\b\x10\x01\x18\xff\x01\xb0\x01\x01R\x10authenticationId\x12O\n" +
	"\x06method\x18\x02 \x01(\x0e2(.m8.platform.iam.v1.AuthenticationMethodB\r\xe0A\x02\xbaH\a\x82\x01\x04\x10\x01 \x00R\x06method\x12,\n" +
	"\vprovider_id\x18\x03 \x01(\tB\v\xe0A\x01\xbaH\x05r\x03\x18\xff\x01R\n" +
	"providerId\x12-\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tB\x0e\xe0A\x01\xbaH\b\xd8\x01\x01r\x03\xb0\x01\x01R\trequestId\"\x84\x04\n" +
	"$SubmitAuthenticationChallengeRequest\x12@\n" +
	"\x11authentication_id\x18\x01 \x01(\tB\x13\xe0A\x02\xbaH\r\xc8\x01\x01r\b\x10\x01\x18\xff\x01\xb0\x01\x01R\x10authenticationId\x123\n" +
	"\fchallenge_id\x18\x02 \x01(\tB\x10\xe0A\x02\xbaH\n" +
	"\xc8\x01\x01r\x05\x10\x01\x18\xff\x01R\vchallengeId\x12<\n" +
	"\x03otp\x18\n" +
	" \x01(\v2(.m8.platform.iam.v1.OtpChallengeResponseH\x00R\x03otp\x12K\n" +
	"\bpassword\x18\v \x01(\v2-.m8.platform.iam.v1.PasswordChallengeResponseH\x00R\bpassword\x12K\n" +
	"\bwebauthn\x18\f \x01(\v2-.m8.platform.iam.v1.WebAuthnAssertionResponseH\x00R\bwebauthn\x12K\n" +
	"\bapproval\x18\r \x01(\v2-.m8.platform.iam.v1.ApprovalChallengeResponseH\x00R\bapproval\x12-\n" +
	"\n" +
	"request_id\x18d \x01(\tB\x0e\xe0A\x01\xbaH\b\xd8\x01\x01r\x03\xb0\x01\x01R\trequestIdB\x11\n" +
	"\bresponse\x12\x05\xbaH\x02\b\x01\";\n" +
	"\x14OtpChallengeResponse\x12#\n" +
	"\x04code\x18\x01 \x01(\tB\x0f\xe0A\x02\xbaH\t\xc8\x01\x01r\x04\x10\x04\x18\fR\x04code\"I\n" +
	"\x19PasswordChallengeResponse\x12,\n" +
	"\bpassword\x18\x01 \x01(\tB\x10\xe0A\x02\xbaH\n" +
	"\xc8\x01\x01r\x05\x10\x01\x18\x80 R\bpassword\"\xa8\x02\n" +
	"\x19WebAuthnAssertionResponse\x123\n" +
	"\rcredential_id\x18\x01 \x01(\tB\x0e\xe0A\x02\xbaH\b\xc8\x01\x01r\x03\x18\x80 R\fcredentialId\x129\n" +
	"\x10client_data_json\x18\x02 \x01(\tB\x0f\xe0A\x02\xbaH\t\xc8\x01\x01r\x04\x18\x80\x80\x04R\x0eclientDataJson\x12>\n" +
	"\x12authenticator_data\x18\x03 \x01(\tB\x0f\xe0A\x02\xbaH\t\xc8\x01\x01r\x04\x18\x80\x80\x04R\x11authenticatorData\x12-\n" +
	"\tsignature\x18\x04 \x01(\tB\x0f\xe0A\x02\xbaH\t\xc8\x01\x01r\x04\x18\x80\x80\x04R\tsignature\x12,\n" +
	"\vuser_handle\x18\x05 \x01(\tB\v\xe0A\x01\xbaH\x05r\x03\x18\x80 R\n" +
	"userHandle\"<\n" +
	"\x19ApprovalChallengeResponse\x12\x1f\n" +
	"\bapproved\x18\x01 \x01(\bB\x03\xe0A\x02R\bapproved\"\xde\x05\n" +
	"#HandleAuthenticationCallbackRequest\x12.\n" +
	"\vprovider_id\x18\x01 \x01(\tB\r\xe0A\x02\xbaH\ar\x05\x10\x01\x18\xff\x01R\n" +
	"providerId\x128\n" +
	"\x11authentication_id\x18\x02 \x01(\tB\v\xe0A\x01\xbaH\x05r\x03\x18\xff\x01R\x10authenticationId\x12\x1f\n" +
	"\x04code\x18\x03 \x01(\tB\v\xe0A\x01\xbaH\x05r\x03\x18\x80 R\x04code\x12!\n" +
	"\x05state\x18\x04 \x01(\tB\v\xe0A\x01\xbaH\x05r\x03\x18\x80 R\x05state\x121\n" +
	"\rsaml_response\x18\x05 \x01(\tB\f\xe0A\x01\xbaH\x06r\x04\x18\x80\x80\x10R\fsamlResponse\x12,\n" +
	"\vrelay_state\x18\x06 \x01(\tB\v\xe0A\x01\xbaH\x05r\x03\x18\x80 R\n" +
	"relayState\x12\x80\x01\n" +
	"\traw_query\x18\a \x03(\v2E.m8.platform.iam.v1.HandleAuthenticationCallbackRequest.RawQueryEntryB\x1c\xe0A\x01\xbaH\x16\x9a\x01\x13\x10d\"\ar\x05\x10\x01\x18\x80\x01*\x06r\x04\x18\x80\x80\x10R\brawQuery\x12}\n" +
	"\braw_form\x18\b \x03(\v2D.m8.platform.iam.v1.HandleAuthenticationCallbackRequest.RawFormEntryB\x1c\xe0A\x01\xbaH\x16\x9a\x01\x13\x10d\"\ar\x05\x10\x01\x18\x80\x01*\x06r\x04\x18\x80\x80\x10R\arawForm\x12-\n" +
	"\n" +
	"request_id\x18\t \x01(\tB\x0e\xe0A\x01\xbaH\b\xd8\x01\x01r\x03\xb0\x01\x01R\trequestId\x1a;\n" +
	"\rRawQueryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fRawFormEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xca\x01\n" +
	"$HandleAuthenticationCallbackResponse\x12O\n" +
	"\x0eauthentication\x18\x01 \x01(\v2\".m8.platform.iam.v1.AuthenticationB\x03\xe0A\x03R\x0eauthentication\x12.\n" +
	"\fredirect_uri\x18\x02 \x01(\tB\v\xe0A\x03\xbaH\x05r\x03\x18\x80 R\vredirectUri\x12!\n" +
	"\tcompleted\x18\x03 \x01(\bB\x03\xe0A\x03R\tcompleted\"w\n" +
	"$StartAuthenticationOperationMetadata\x12O\n" +
	"\x0eauthentication\x18\x01 \x01(\v2\".m8.platform.iam.v1.AuthenticationB\x03\xe0A\x03R\x0eauthentication\"\x82\x03\n" +
	"\x1aAuthenticationStartOptions\x12=\n" +
	"\x18login_experience_version\x18\x01 \x01(\tB\x03\xe0A\x01R\x16loginExperienceVersion\x12}\n" +
	"\x1frequested_authentication_method\x18\x05 \x01(\x0e2(.m8.platform.iam.v1.AuthenticationMethodB\v\xe0A\x01\xbaH\x05\x82\x01\x02\x10\x01R\x1drequestedAuthenticationMethod\x12;\n" +
	"\x13requested_method_id\x18\x06 \x01(\tB\v\xe0A\x01\xbaH\x05r\x03\x18\xff\x01R\x11requestedMethodId\x12?\n" +
	"\x15requested_provider_id\x18\x02 \x01(\tB\v\xe0A\x01\xbaH\x05r\x03\x18\xff\x01R\x13requestedProviderId\x12\"\n" +
	"\n" +
	"acr_values\x18\x04 \x03(\tB\x03\xe0A\x01R\tacrValuesJ\x04\b\x03\x10\x042\xea\x17\n" +
	"\x15AuthenticationService\x12\xeb\x02\n" +
	"\x13StartAuthentication\x12..m8.platform.iam.v1.StartAuthenticationRequest\x1a\x1d.google.longrunning.Operation\"\x84\x02\xcaA6\n" +
	"\x0eAuthentication\x12$StartAuthenticationOperationMetadata\xdaA\x1cclient_id,subject,request_id\xbaG~\x12\x05Start\x1a`Starts a new authentication workflow and returns a long-running operation for tracking progress.*\x13StartAuthentication\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/iam/authentications:start\x90\x02\x02\x12\xcc\x02\n" +
	"\x11GetAuthentication\x12,.m8.platform.iam.v1.GetAuthenticationRequest\x1a\".m8.platform.iam.v1.Authentication\"\xe4\x01\xdaA\x11authentication_id\xbaG\x96\x01\x12\x03Get\x1a|Returns the latest snapshot of an authentication operation. Safe for polling and never includes sensitive challenge secrets.*\x11GetAuthentication\x82\xd3\xe4\x93\x02-\x12+/v1/iam/authentications/{authentication_id}\x90\x02\x01\x12\xe9\x02\n" +
	"\x14CancelAuthentication\x12/.m8.platform.iam.v1.CancelAuthenticationRequest\x1a\".m8.platform.iam.v1.Authentication\"\xfb\x01\xdaA\x1cauthentication_id,request_id\xbaG\x98\x01\x12\x06Cancel\x1axCancels an active authentication operation and returns the updated snapshot. Terminal operations are returned unchanged.*\x14CancelAuthentication\x82\xd3\xe4\x93\x027:\x01*\"2/v1/iam/authentications/{authentication_id}:cancel\x90\x02\x02\x12\xd4\x03\n" +
	"\x1dResendAuthenticationChallenge\x128.m8.platform.iam.v1.ResendAuthenticationChallengeRequest\x1a\".m8.platform.iam.v1.Authentication\"\xd4\x02\xdaA)authentication_id,challenge_id,request_id\xbaG\xca\x01\x12\x10Resend challenge\x1a\x96\x01Resends the current challenge when the selected method supports resend. It does not create a new authentication operation or expose challenge secrets.*\x1dResendAuthenticationChallenge\x82\xd3\xe4\x93\x02Q:\x01*\"L/v1/iam/authentications/{authentication_id}/challenges/{challenge_id}:resend\x90\x02\x02\x12\xb9\x03\n" +
	"\x1dSelectAuthenticationChallenge\x128.m8.platform.iam.v1.SelectAuthenticationChallengeRequest\x1a\".m8.platform.iam.v1.Authentication\"\xb9\x02\xdaA/authentication_id,method,provider_id,request_id\xbaG\xba\x01\x12\x10Select challenge\x1a\x86\x01Selects an allowed authentication method or provider and prepares a new public-safe current challenge without verifying user identity.*\x1dSelectAuthenticationChallenge\x82\xd3\xe4\x93\x02@:\x01*\";/v1/iam/authentications/{authentication_id}:selectChallenge\x90\x02\x02\x12\xd0\x03\n" +
	"\x1dSubmitAuthenticationChallenge\x128.m8.platform.iam.v1.SubmitAuthenticationChallengeRequest\x1a\".m8.platform.iam.v1.Authentication\"\xd0\x02\xdaA)authentication_id,challenge_id,request_id\xbaG\xc6\x01\x12\x10Submit challenge\x1a\x92\x01Accepts the user or client response to the current challenge and returns a public-safe authentication snapshot without exposing challenge secrets.*\x1dSubmitAuthenticationChallenge\x82\xd3\xe4\x93\x02Q:\x01*\"L/v1/iam/authentications/{authentication_id}/challenges/{challenge_id}:submit\x90\x02\x02\x12\xdf\x03\n" +
	"\x1cHandleAuthenticationCallback\x127.m8.platform.iam.v1.HandleAuthenticationCallbackRequest\x1a8.m8.platform.iam.v1.HandleAuthenticationCallbackResponse\"\xcb\x02\xdaA\x16provider_id,request_id\xbaG\xc2\x01\x12\x0fHandle callback\x1a\x90\x01Processes callbacks from external identity providers and returns an updated authentication snapshot without exposing provider secrets or tokens.*\x1cHandleAuthenticationCallback\x82\xd3\xe4\x93\x02c:\x01*Z/\x12-/v1/iam/authenticationCallbacks/{provider_id}\"-/v1/iam/authenticationCallbacks/{provider_id}\x90\x02\x02\x1a`\x92\xb5\x18\\Use this API to start authentication workflows and track their long-running operation state.B7Z5github.com/m8-team/go-genproto/m8/platform/iam/v1;iamb\x06proto3"

var (
	file_m8_platform_iam_v1_authentication_service_proto_rawDescOnce sync.Once
	file_m8_platform_iam_v1_authentication_service_proto_rawDescData []byte
)

func file_m8_platform_iam_v1_authentication_service_proto_rawDescGZIP() []byte {
	file_m8_platform_iam_v1_authentication_service_proto_rawDescOnce.Do(func() {
		file_m8_platform_iam_v1_authentication_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_m8_platform_iam_v1_authentication_service_proto_rawDesc), len(file_m8_platform_iam_v1_authentication_service_proto_rawDesc)))
	})
	return file_m8_platform_iam_v1_authentication_service_proto_rawDescData
}

var file_m8_platform_iam_v1_authentication_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_m8_platform_iam_v1_authentication_service_proto_goTypes = []any{
	(*StartAuthenticationRequest)(nil),           // 0: m8.platform.iam.v1.StartAuthenticationRequest
	(*GetAuthenticationRequest)(nil),             // 1: m8.platform.iam.v1.GetAuthenticationRequest
	(*CancelAuthenticationRequest)(nil),          // 2: m8.platform.iam.v1.CancelAuthenticationRequest
	(*ResendAuthenticationChallengeRequest)(nil), // 3: m8.platform.iam.v1.ResendAuthenticationChallengeRequest
	(*SelectAuthenticationChallengeRequest)(nil), // 4: m8.platform.iam.v1.SelectAuthenticationChallengeRequest
	(*SubmitAuthenticationChallengeRequest)(nil), // 5: m8.platform.iam.v1.SubmitAuthenticationChallengeRequest
	(*OtpChallengeResponse)(nil),                 // 6: m8.platform.iam.v1.OtpChallengeResponse
	(*PasswordChallengeResponse)(nil),            // 7: m8.platform.iam.v1.PasswordChallengeResponse
	(*WebAuthnAssertionResponse)(nil),            // 8: m8.platform.iam.v1.WebAuthnAssertionResponse
	(*ApprovalChallengeResponse)(nil),            // 9: m8.platform.iam.v1.ApprovalChallengeResponse
	(*HandleAuthenticationCallbackRequest)(nil),  // 10: m8.platform.iam.v1.HandleAuthenticationCallbackRequest
	(*HandleAuthenticationCallbackResponse)(nil), // 11: m8.platform.iam.v1.HandleAuthenticationCallbackResponse
	(*StartAuthenticationOperationMetadata)(nil), // 12: m8.platform.iam.v1.StartAuthenticationOperationMetadata
	(*AuthenticationStartOptions)(nil),           // 13: m8.platform.iam.v1.AuthenticationStartOptions
	nil,                                          // 14: m8.platform.iam.v1.HandleAuthenticationCallbackRequest.RawQueryEntry
	nil,                                          // 15: m8.platform.iam.v1.HandleAuthenticationCallbackRequest.RawFormEntry
	(*AuthenticationSubject)(nil),                // 16: m8.platform.iam.v1.AuthenticationSubject
	(*AuthenticationContext)(nil),                // 17: m8.platform.iam.v1.AuthenticationContext
	(AuthenticationMethod)(0),                    // 18: m8.platform.iam.v1.AuthenticationMethod
	(*Authentication)(nil),                       // 19: m8.platform.iam.v1.Authentication
	(*longrunningpb.Operation)(nil),              // 20: google.longrunning.Operation
}
var file_m8_platform_iam_v1_authentication_service_proto_depIdxs = []int32{
	16, // 0: m8.platform.iam.v1.StartAuthenticationRequest.subject:type_name -> m8.platform.iam.v1.AuthenticationSubject
	17, // 1: m8.platform.iam.v1.StartAuthenticationRequest.context:type_name -> m8.platform.iam.v1.AuthenticationContext
	13, // 2: m8.platform.iam.v1.StartAuthenticationRequest.options:type_name -> m8.platform.iam.v1.AuthenticationStartOptions
	18, // 3: m8.platform.iam.v1.SelectAuthenticationChallengeRequest.method:type_name -> m8.platform.iam.v1.AuthenticationMethod
	6,  // 4: m8.platform.iam.v1.SubmitAuthenticationChallengeRequest.otp:type_name -> m8.platform.iam.v1.OtpChallengeResponse
	7,  // 5: m8.platform.iam.v1.SubmitAuthenticationChallengeRequest.password:type_name -> m8.platform.iam.v1.PasswordChallengeResponse
	8,  // 6: m8.platform.iam.v1.SubmitAuthenticationChallengeRequest.webauthn:type_name -> m8.platform.iam.v1.WebAuthnAssertionResponse
	9,  // 7: m8.platform.iam.v1.SubmitAuthenticationChallengeRequest.approval:type_name -> m8.platform.iam.v1.ApprovalChallengeResponse
	14, // 8: m8.platform.iam.v1.HandleAuthenticationCallbackRequest.raw_query:type_name -> m8.platform.iam.v1.HandleAuthenticationCallbackRequest.RawQueryEntry
	15, // 9: m8.platform.iam.v1.HandleAuthenticationCallbackRequest.raw_form:type_name -> m8.platform.iam.v1.HandleAuthenticationCallbackRequest.RawFormEntry
	19, // 10: m8.platform.iam.v1.HandleAuthenticationCallbackResponse.authentication:type_name -> m8.platform.iam.v1.Authentication
	19, // 11: m8.platform.iam.v1.StartAuthenticationOperationMetadata.authentication:type_name -> m8.platform.iam.v1.Authentication
	18, // 12: m8.platform.iam.v1.AuthenticationStartOptions.requested_authentication_method:type_name -> m8.platform.iam.v1.AuthenticationMethod
	0,  // 13: m8.platform.iam.v1.AuthenticationService.StartAuthentication:input_type -> m8.platform.iam.v1.StartAuthenticationRequest
	1,  // 14: m8.platform.iam.v1.AuthenticationService.GetAuthentication:input_type -> m8.platform.iam.v1.GetAuthenticationRequest
	2,  // 15: m8.platform.iam.v1.AuthenticationService.CancelAuthentication:input_type -> m8.platform.iam.v1.CancelAuthenticationRequest
	3,  // 16: m8.platform.iam.v1.AuthenticationService.ResendAuthenticationChallenge:input_type -> m8.platform.iam.v1.ResendAuthenticationChallengeRequest
	4,  // 17: m8.platform.iam.v1.AuthenticationService.SelectAuthenticationChallenge:input_type -> m8.platform.iam.v1.SelectAuthenticationChallengeRequest
	5,  // 18: m8.platform.iam.v1.AuthenticationService.SubmitAuthenticationChallenge:input_type -> m8.platform.iam.v1.SubmitAuthenticationChallengeRequest
	10, // 19: m8.platform.iam.v1.AuthenticationService.HandleAuthenticationCallback:input_type -> m8.platform.iam.v1.HandleAuthenticationCallbackRequest
	20, // 20: m8.platform.iam.v1.AuthenticationService.StartAuthentication:output_type -> google.longrunning.Operation
	19, // 21: m8.platform.iam.v1.AuthenticationService.GetAuthentication:output_type -> m8.platform.iam.v1.Authentication
	19, // 22: m8.platform.iam.v1.AuthenticationService.CancelAuthentication:output_type -> m8.platform.iam.v1.Authentication
	19, // 23: m8.platform.iam.v1.AuthenticationService.ResendAuthenticationChallenge:output_type -> m8.platform.iam.v1.Authentication
	19, // 24: m8.platform.iam.v1.AuthenticationService.SelectAuthenticationChallenge:output_type -> m8.platform.iam.v1.Authentication
	19, // 25: m8.platform.iam.v1.AuthenticationService.SubmitAuthenticationChallenge:output_type -> m8.platform.iam.v1.Authentication
	11, // 26: m8.platform.iam.v1.AuthenticationService.HandleAuthenticationCallback:output_type -> m8.platform.iam.v1.HandleAuthenticationCallbackResponse
	20, // [20:27] is the sub-list for method output_type
	13, // [13:20] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_m8_platform_iam_v1_authentication_service_proto_init() }
func file_m8_platform_iam_v1_authentication_service_proto_init() {
	if File_m8_platform_iam_v1_authentication_service_proto != nil {
		return
	}
	file_m8_platform_iam_v1_authentication_proto_init()
	file_m8_platform_iam_v1_authentication_challenge_proto_init()
	file_m8_platform_iam_v1_authentication_context_proto_init()
	file_m8_platform_iam_v1_authentication_subject_proto_init()
	file_m8_platform_iam_v1_authentication_service_proto_msgTypes[5].OneofWrappers = []any{
		(*SubmitAuthenticationChallengeRequest_Otp)(nil),
		(*SubmitAuthenticationChallengeRequest_Password)(nil),
		(*SubmitAuthenticationChallengeRequest_Webauthn)(nil),
		(*SubmitAuthenticationChallengeRequest_Approval)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_m8_platform_iam_v1_authentication_service_proto_rawDesc), len(file_m8_platform_iam_v1_authentication_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_m8_platform_iam_v1_authentication_service_proto_goTypes,
		DependencyIndexes: file_m8_platform_iam_v1_authentication_service_proto_depIdxs,
		MessageInfos:      file_m8_platform_iam_v1_authentication_service_proto_msgTypes,
	}.Build()
	File_m8_platform_iam_v1_authentication_service_proto = out.File
	file_m8_platform_iam_v1_authentication_service_proto_goTypes = nil
	file_m8_platform_iam_v1_authentication_service_proto_depIdxs = nil
}
