// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: m8/platform/iam/v1/authentication_environment_context.proto

package iam

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type of device observed during authentication.
type DeviceType int32

const (
	// Device type is not specified.
	DeviceType_DEVICE_TYPE_UNSPECIFIED DeviceType = 0
	// Device type is unknown.
	DeviceType_DEVICE_TYPE_UNKNOWN DeviceType = 1
	// Desktop or laptop device.
	DeviceType_DEVICE_TYPE_DESKTOP DeviceType = 2
	// Mobile phone device.
	DeviceType_DEVICE_TYPE_MOBILE DeviceType = 3
	// Tablet device.
	DeviceType_DEVICE_TYPE_TABLET DeviceType = 4
	// Server-side device or workload.
	DeviceType_DEVICE_TYPE_SERVER DeviceType = 5
	// Browser-only device context.
	DeviceType_DEVICE_TYPE_BROWSER DeviceType = 6
	// Embedded or IoT device.
	DeviceType_DEVICE_TYPE_IOT DeviceType = 7
)

// Enum value maps for DeviceType.
var (
	DeviceType_name = map[int32]string{
		0: "DEVICE_TYPE_UNSPECIFIED",
		1: "DEVICE_TYPE_UNKNOWN",
		2: "DEVICE_TYPE_DESKTOP",
		3: "DEVICE_TYPE_MOBILE",
		4: "DEVICE_TYPE_TABLET",
		5: "DEVICE_TYPE_SERVER",
		6: "DEVICE_TYPE_BROWSER",
		7: "DEVICE_TYPE_IOT",
	}
	DeviceType_value = map[string]int32{
		"DEVICE_TYPE_UNSPECIFIED": 0,
		"DEVICE_TYPE_UNKNOWN":     1,
		"DEVICE_TYPE_DESKTOP":     2,
		"DEVICE_TYPE_MOBILE":      3,
		"DEVICE_TYPE_TABLET":      4,
		"DEVICE_TYPE_SERVER":      5,
		"DEVICE_TYPE_BROWSER":     6,
		"DEVICE_TYPE_IOT":         7,
	}
)

func (x DeviceType) Enum() *DeviceType {
	p := new(DeviceType)
	*p = x
	return p
}

func (x DeviceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceType) Descriptor() protoreflect.EnumDescriptor {
	return file_m8_platform_iam_v1_authentication_environment_context_proto_enumTypes[0].Descriptor()
}

func (DeviceType) Type() protoreflect.EnumType {
	return &file_m8_platform_iam_v1_authentication_environment_context_proto_enumTypes[0]
}

func (x DeviceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceType.Descriptor instead.
func (DeviceType) EnumDescriptor() ([]byte, []int) {
	return file_m8_platform_iam_v1_authentication_environment_context_proto_rawDescGZIP(), []int{0}
}

// Trust level assigned to the device.
type DeviceTrustLevel int32

const (
	// Device trust level is not specified.
	DeviceTrustLevel_DEVICE_TRUST_LEVEL_UNSPECIFIED DeviceTrustLevel = 0
	// Device trust is unknown.
	DeviceTrustLevel_DEVICE_TRUST_LEVEL_UNKNOWN DeviceTrustLevel = 1
	// Device is not trusted.
	DeviceTrustLevel_DEVICE_TRUST_LEVEL_UNTRUSTED DeviceTrustLevel = 2
	// Device is known but not fully trusted.
	DeviceTrustLevel_DEVICE_TRUST_LEVEL_KNOWN DeviceTrustLevel = 3
	// Device is trusted by the tenant or platform.
	DeviceTrustLevel_DEVICE_TRUST_LEVEL_TRUSTED DeviceTrustLevel = 4
	// Device is managed by an enterprise control plane.
	DeviceTrustLevel_DEVICE_TRUST_LEVEL_MANAGED DeviceTrustLevel = 5
	// Device is suspected or confirmed compromised.
	DeviceTrustLevel_DEVICE_TRUST_LEVEL_COMPROMISED DeviceTrustLevel = 6
)

// Enum value maps for DeviceTrustLevel.
var (
	DeviceTrustLevel_name = map[int32]string{
		0: "DEVICE_TRUST_LEVEL_UNSPECIFIED",
		1: "DEVICE_TRUST_LEVEL_UNKNOWN",
		2: "DEVICE_TRUST_LEVEL_UNTRUSTED",
		3: "DEVICE_TRUST_LEVEL_KNOWN",
		4: "DEVICE_TRUST_LEVEL_TRUSTED",
		5: "DEVICE_TRUST_LEVEL_MANAGED",
		6: "DEVICE_TRUST_LEVEL_COMPROMISED",
	}
	DeviceTrustLevel_value = map[string]int32{
		"DEVICE_TRUST_LEVEL_UNSPECIFIED": 0,
		"DEVICE_TRUST_LEVEL_UNKNOWN":     1,
		"DEVICE_TRUST_LEVEL_UNTRUSTED":   2,
		"DEVICE_TRUST_LEVEL_KNOWN":       3,
		"DEVICE_TRUST_LEVEL_TRUSTED":     4,
		"DEVICE_TRUST_LEVEL_MANAGED":     5,
		"DEVICE_TRUST_LEVEL_COMPROMISED": 6,
	}
)

func (x DeviceTrustLevel) Enum() *DeviceTrustLevel {
	p := new(DeviceTrustLevel)
	*p = x
	return p
}

func (x DeviceTrustLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceTrustLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_m8_platform_iam_v1_authentication_environment_context_proto_enumTypes[1].Descriptor()
}

func (DeviceTrustLevel) Type() protoreflect.EnumType {
	return &file_m8_platform_iam_v1_authentication_environment_context_proto_enumTypes[1]
}

func (x DeviceTrustLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceTrustLevel.Descriptor instead.
func (DeviceTrustLevel) EnumDescriptor() ([]byte, []int) {
	return file_m8_platform_iam_v1_authentication_environment_context_proto_rawDescGZIP(), []int{1}
}

// DeviceContext describes the device involved in authentication.
//
// Example:
// - known managed laptop
// - new mobile device with a hashed fingerprint
// - browser context with a device key reference
type DeviceContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable device identifier or opaque device reference.
	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Device type.
	Type DeviceType `protobuf:"varint,2,opt,name=type,proto3,enum=m8.platform.iam.v1.DeviceType" json:"type,omitempty"`
	// Trust level assigned to the device.
	TrustLevel DeviceTrustLevel `protobuf:"varint,3,opt,name=trust_level,json=trustLevel,proto3,enum=m8.platform.iam.v1.DeviceTrustLevel" json:"trust_level,omitempty"`
	// Hash of the device fingerprint.
	FingerprintHash string `protobuf:"bytes,4,opt,name=fingerprint_hash,json=fingerprintHash,proto3" json:"fingerprint_hash,omitempty"`
	// Hash of the user agent.
	UserAgentHash string `protobuf:"bytes,5,opt,name=user_agent_hash,json=userAgentHash,proto3" json:"user_agent_hash,omitempty"`
	// Platform name such as iOS, Android, macOS, Windows, or Linux.
	Platform string `protobuf:"bytes,6,opt,name=platform,proto3" json:"platform,omitempty"`
	// Operating system family.
	OsFamily string `protobuf:"bytes,7,opt,name=os_family,json=osFamily,proto3" json:"os_family,omitempty"`
	// Browser family.
	BrowserFamily string `protobuf:"bytes,8,opt,name=browser_family,json=browserFamily,proto3" json:"browser_family,omitempty"`
	// Whether the device is enterprise-managed.
	Managed bool `protobuf:"varint,9,opt,name=managed,proto3" json:"managed,omitempty"`
	// Whether the device is trusted.
	Trusted bool `protobuf:"varint,10,opt,name=trusted,proto3" json:"trusted,omitempty"`
	// Whether the device is suspected or confirmed compromised.
	Compromised bool `protobuf:"varint,11,opt,name=compromised,proto3" json:"compromised,omitempty"`
	// Additional non-sensitive device attributes.
	Attributes    map[string]string `protobuf:"bytes,12,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceContext) Reset() {
	*x = DeviceContext{}
	mi := &file_m8_platform_iam_v1_authentication_environment_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceContext) ProtoMessage() {}

func (x *DeviceContext) ProtoReflect() protoreflect.Message {
	mi := &file_m8_platform_iam_v1_authentication_environment_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceContext.ProtoReflect.Descriptor instead.
func (*DeviceContext) Descriptor() ([]byte, []int) {
	return file_m8_platform_iam_v1_authentication_environment_context_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceContext) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceContext) GetType() DeviceType {
	if x != nil {
		return x.Type
	}
	return DeviceType_DEVICE_TYPE_UNSPECIFIED
}

func (x *DeviceContext) GetTrustLevel() DeviceTrustLevel {
	if x != nil {
		return x.TrustLevel
	}
	return DeviceTrustLevel_DEVICE_TRUST_LEVEL_UNSPECIFIED
}

func (x *DeviceContext) GetFingerprintHash() string {
	if x != nil {
		return x.FingerprintHash
	}
	return ""
}

func (x *DeviceContext) GetUserAgentHash() string {
	if x != nil {
		return x.UserAgentHash
	}
	return ""
}

func (x *DeviceContext) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *DeviceContext) GetOsFamily() string {
	if x != nil {
		return x.OsFamily
	}
	return ""
}

func (x *DeviceContext) GetBrowserFamily() string {
	if x != nil {
		return x.BrowserFamily
	}
	return ""
}

func (x *DeviceContext) GetManaged() bool {
	if x != nil {
		return x.Managed
	}
	return false
}

func (x *DeviceContext) GetTrusted() bool {
	if x != nil {
		return x.Trusted
	}
	return false
}

func (x *DeviceContext) GetCompromised() bool {
	if x != nil {
		return x.Compromised
	}
	return false
}

func (x *DeviceContext) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// NetworkContext describes network signals relevant to authentication risk.
//
// Example:
// - hashed IP address with country and ASN
// - proxy or VPN detection
// - network reputation score
type NetworkContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hash of the client IP address.
	IpHash string `protobuf:"bytes,1,opt,name=ip_hash,json=ipHash,proto3" json:"ip_hash,omitempty"`
	// Coarse network prefix when it is safe to store.
	IpPrefix string `protobuf:"bytes,2,opt,name=ip_prefix,json=ipPrefix,proto3" json:"ip_prefix,omitempty"`
	// ISO 3166 country code inferred from the network.
	CountryCode string `protobuf:"bytes,3,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	// Autonomous system number.
	Asn int64 `protobuf:"varint,4,opt,name=asn,proto3" json:"asn,omitempty"`
	// Autonomous system organization name.
	AutonomousSystem string `protobuf:"bytes,5,opt,name=autonomous_system,json=autonomousSystem,proto3" json:"autonomous_system,omitempty"`
	// Whether the request appears to use a VPN.
	Vpn bool `protobuf:"varint,6,opt,name=vpn,proto3" json:"vpn,omitempty"`
	// Whether the request appears to use a proxy.
	Proxy bool `protobuf:"varint,7,opt,name=proxy,proto3" json:"proxy,omitempty"`
	// Whether the request appears to use Tor.
	Tor bool `protobuf:"varint,8,opt,name=tor,proto3" json:"tor,omitempty"`
	// Network reputation score.
	ReputationScore float64 `protobuf:"fixed64,9,opt,name=reputation_score,json=reputationScore,proto3" json:"reputation_score,omitempty"`
	// Additional non-sensitive network attributes.
	Attributes    map[string]string `protobuf:"bytes,10,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkContext) Reset() {
	*x = NetworkContext{}
	mi := &file_m8_platform_iam_v1_authentication_environment_context_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkContext) ProtoMessage() {}

func (x *NetworkContext) ProtoReflect() protoreflect.Message {
	mi := &file_m8_platform_iam_v1_authentication_environment_context_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkContext.ProtoReflect.Descriptor instead.
func (*NetworkContext) Descriptor() ([]byte, []int) {
	return file_m8_platform_iam_v1_authentication_environment_context_proto_rawDescGZIP(), []int{1}
}

func (x *NetworkContext) GetIpHash() string {
	if x != nil {
		return x.IpHash
	}
	return ""
}

func (x *NetworkContext) GetIpPrefix() string {
	if x != nil {
		return x.IpPrefix
	}
	return ""
}

func (x *NetworkContext) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *NetworkContext) GetAsn() int64 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *NetworkContext) GetAutonomousSystem() string {
	if x != nil {
		return x.AutonomousSystem
	}
	return ""
}

func (x *NetworkContext) GetVpn() bool {
	if x != nil {
		return x.Vpn
	}
	return false
}

func (x *NetworkContext) GetProxy() bool {
	if x != nil {
		return x.Proxy
	}
	return false
}

func (x *NetworkContext) GetTor() bool {
	if x != nil {
		return x.Tor
	}
	return false
}

func (x *NetworkContext) GetReputationScore() float64 {
	if x != nil {
		return x.ReputationScore
	}
	return 0
}

func (x *NetworkContext) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// RuntimeContext describes workflow and service execution metadata.
//
// Example:
// - Temporal workflow and run identifiers
// - tracing identifiers for cross-service debugging
// - deadline used by provider calls
type RuntimeContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Workflow identifier.
	WorkflowId string `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	// Workflow run identifier.
	RunId string `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// Distributed trace identifier.
	TraceId string `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Distributed tracing span identifier.
	SpanId string `protobuf:"bytes,4,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	// Service that produced the context.
	ServiceName string `protobuf:"bytes,5,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Service version that produced the context.
	ServiceVersion string `protobuf:"bytes,6,opt,name=service_version,json=serviceVersion,proto3" json:"service_version,omitempty"`
	// Runtime region.
	Region string `protobuf:"bytes,7,opt,name=region,proto3" json:"region,omitempty"`
	// Runtime environment such as prod, stage, or dev.
	Environment string `protobuf:"bytes,8,opt,name=environment,proto3" json:"environment,omitempty"`
	// Time when processing started.
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// Processing deadline for the operation.
	DeadlineAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=deadline_at,json=deadlineAt,proto3" json:"deadline_at,omitempty"`
	// Additional non-sensitive runtime attributes.
	Attributes    map[string]string `protobuf:"bytes,11,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeContext) Reset() {
	*x = RuntimeContext{}
	mi := &file_m8_platform_iam_v1_authentication_environment_context_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeContext) ProtoMessage() {}

func (x *RuntimeContext) ProtoReflect() protoreflect.Message {
	mi := &file_m8_platform_iam_v1_authentication_environment_context_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeContext.ProtoReflect.Descriptor instead.
func (*RuntimeContext) Descriptor() ([]byte, []int) {
	return file_m8_platform_iam_v1_authentication_environment_context_proto_rawDescGZIP(), []int{2}
}

func (x *RuntimeContext) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *RuntimeContext) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RuntimeContext) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *RuntimeContext) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *RuntimeContext) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RuntimeContext) GetServiceVersion() string {
	if x != nil {
		return x.ServiceVersion
	}
	return ""
}

func (x *RuntimeContext) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RuntimeContext) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *RuntimeContext) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *RuntimeContext) GetDeadlineAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeadlineAt
	}
	return nil
}

func (x *RuntimeContext) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_m8_platform_iam_v1_authentication_environment_context_proto protoreflect.FileDescriptor

const file_m8_platform_iam_v1_authentication_environment_context_proto_rawDesc = "" +
	"\n" +
	";m8/platform/iam/v1/authentication_environment_context.proto\x12\x12m8.platform.iam.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc2\x04\n" +
	"\rDeviceContext\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x122\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1e.m8.platform.iam.v1.DeviceTypeR\x04type\x12E\n" +
	"\vtrust_level\x18\x03 \x01(\x0e2$.m8.platform.iam.v1.DeviceTrustLevelR\n" +
	"trustLevel\x12)\n" +
	"\x10fingerprint_hash\x18\x04 \x01(\tR\x0ffingerprintHash\x12&\n" +
	"\x0fuser_agent_hash\x18\x05 \x01(\tR\ruserAgentHash\x12\x1a\n" +
	"\bplatform\x18\x06 \x01(\tR\bplatform\x12\x1b\n" +
	"\tos_family\x18\a \x01(\tR\bosFamily\x12%\n" +
	"\x0ebrowser_family\x18\b \x01(\tR\rbrowserFamily\x12\x18\n" +
	"\amanaged\x18\t \x01(\bR\amanaged\x12\x18\n" +
	"\atrusted\x18\n" +
	" \x01(\bR\atrusted\x12 \n" +
	"\vcompromised\x18\v \x01(\bR\vcompromised\x12Q\n" +
	"\n" +
	"attributes\x18\f \x03(\v21.m8.platform.iam.v1.DeviceContext.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa0\x03\n" +
	"\x0eNetworkContext\x12\x17\n" +
	"\aip_hash\x18\x01 \x01(\tR\x06ipHash\x12\x1b\n" +
	"\tip_prefix\x18\x02 \x01(\tR\bipPrefix\x12!\n" +
	"\fcountry_code\x18\x03 \x01(\tR\vcountryCode\x12\x10\n" +
	"\x03asn\x18\x04 \x01(\x03R\x03asn\x12+\n" +
	"\x11autonomous_system\x18\x05 \x01(\tR\x10autonomousSystem\x12\x10\n" +
	"\x03vpn\x18\x06 \x01(\bR\x03vpn\x12\x14\n" +
	"\x05proxy\x18\a \x01(\bR\x05proxy\x12\x10\n" +
	"\x03tor\x18\b \x01(\bR\x03tor\x12)\n" +
	"\x10reputation_score\x18\t \x01(\x01R\x0freputationScore\x12R\n" +
	"\n" +
	"attributes\x18\n" +
	" \x03(\v22.m8.platform.iam.v1.NetworkContext.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\x04\n" +
	"\x0eRuntimeContext\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x04 \x01(\tR\x06spanId\x12!\n" +
	"\fservice_name\x18\x05 \x01(\tR\vserviceName\x12'\n" +
	"\x0fservice_version\x18\x06 \x01(\tR\x0eserviceVersion\x12\x16\n" +
	"\x06region\x18\a \x01(\tR\x06region\x12 \n" +
	"\venvironment\x18\b \x01(\tR\venvironment\x129\n" +
	"\n" +
	"started_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vdeadline_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"deadlineAt\x12R\n" +
	"\n" +
	"attributes\x18\v \x03(\v22.m8.platform.iam.v1.RuntimeContext.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xd1\x01\n" +
	"\n" +
	"DeviceType\x12\x1b\n" +
	"\x17DEVICE_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13DEVICE_TYPE_UNKNOWN\x10\x01\x12\x17\n" +
	"\x13DEVICE_TYPE_DESKTOP\x10\x02\x12\x16\n" +
	"\x12DEVICE_TYPE_MOBILE\x10\x03\x12\x16\n" +
	"\x12DEVICE_TYPE_TABLET\x10\x04\x12\x16\n" +
	"\x12DEVICE_TYPE_SERVER\x10\x05\x12\x17\n" +
	"\x13DEVICE_TYPE_BROWSER\x10\x06\x12\x13\n" +
	"\x0fDEVICE_TYPE_IOT\x10\a*\xfa\x01\n" +
	"\x10DeviceTrustLevel\x12\"\n" +
	"\x1eDEVICE_TRUST_LEVEL_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aDEVICE_TRUST_LEVEL_UNKNOWN\x10\x01\x12 \n" +
	"\x1cDEVICE_TRUST_LEVEL_UNTRUSTED\x10\x02\x12\x1c\n" +
	"\x18DEVICE_TRUST_LEVEL_KNOWN\x10\x03\x12\x1e\n" +
	"\x1aDEVICE_TRUST_LEVEL_TRUSTED\x10\x04\x12\x1e\n" +
	"\x1aDEVICE_TRUST_LEVEL_MANAGED\x10\x05\x12\"\n" +
	"\x1eDEVICE_TRUST_LEVEL_COMPROMISED\x10\x06B7Z5github.com/m8-team/go-genproto/m8/platform/iam/v1;iamb\x06proto3"

var (
	file_m8_platform_iam_v1_authentication_environment_context_proto_rawDescOnce sync.Once
	file_m8_platform_iam_v1_authentication_environment_context_proto_rawDescData []byte
)

func file_m8_platform_iam_v1_authentication_environment_context_proto_rawDescGZIP() []byte {
	file_m8_platform_iam_v1_authentication_environment_context_proto_rawDescOnce.Do(func() {
		file_m8_platform_iam_v1_authentication_environment_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_m8_platform_iam_v1_authentication_environment_context_proto_rawDesc), len(file_m8_platform_iam_v1_authentication_environment_context_proto_rawDesc)))
	})
	return file_m8_platform_iam_v1_authentication_environment_context_proto_rawDescData
}

var file_m8_platform_iam_v1_authentication_environment_context_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_m8_platform_iam_v1_authentication_environment_context_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_m8_platform_iam_v1_authentication_environment_context_proto_goTypes = []any{
	(DeviceType)(0),               // 0: m8.platform.iam.v1.DeviceType
	(DeviceTrustLevel)(0),         // 1: m8.platform.iam.v1.DeviceTrustLevel
	(*DeviceContext)(nil),         // 2: m8.platform.iam.v1.DeviceContext
	(*NetworkContext)(nil),        // 3: m8.platform.iam.v1.NetworkContext
	(*RuntimeContext)(nil),        // 4: m8.platform.iam.v1.RuntimeContext
	nil,                           // 5: m8.platform.iam.v1.DeviceContext.AttributesEntry
	nil,                           // 6: m8.platform.iam.v1.NetworkContext.AttributesEntry
	nil,                           // 7: m8.platform.iam.v1.RuntimeContext.AttributesEntry
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_m8_platform_iam_v1_authentication_environment_context_proto_depIdxs = []int32{
	0, // 0: m8.platform.iam.v1.DeviceContext.type:type_name -> m8.platform.iam.v1.DeviceType
	1, // 1: m8.platform.iam.v1.DeviceContext.trust_level:type_name -> m8.platform.iam.v1.DeviceTrustLevel
	5, // 2: m8.platform.iam.v1.DeviceContext.attributes:type_name -> m8.platform.iam.v1.DeviceContext.AttributesEntry
	6, // 3: m8.platform.iam.v1.NetworkContext.attributes:type_name -> m8.platform.iam.v1.NetworkContext.AttributesEntry
	8, // 4: m8.platform.iam.v1.RuntimeContext.started_at:type_name -> google.protobuf.Timestamp
	8, // 5: m8.platform.iam.v1.RuntimeContext.deadline_at:type_name -> google.protobuf.Timestamp
	7, // 6: m8.platform.iam.v1.RuntimeContext.attributes:type_name -> m8.platform.iam.v1.RuntimeContext.AttributesEntry
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_m8_platform_iam_v1_authentication_environment_context_proto_init() }
func file_m8_platform_iam_v1_authentication_environment_context_proto_init() {
	if File_m8_platform_iam_v1_authentication_environment_context_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_m8_platform_iam_v1_authentication_environment_context_proto_rawDesc), len(file_m8_platform_iam_v1_authentication_environment_context_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_m8_platform_iam_v1_authentication_environment_context_proto_goTypes,
		DependencyIndexes: file_m8_platform_iam_v1_authentication_environment_context_proto_depIdxs,
		EnumInfos:         file_m8_platform_iam_v1_authentication_environment_context_proto_enumTypes,
		MessageInfos:      file_m8_platform_iam_v1_authentication_environment_context_proto_msgTypes,
	}.Build()
	File_m8_platform_iam_v1_authentication_environment_context_proto = out.File
	file_m8_platform_iam_v1_authentication_environment_context_proto_goTypes = nil
	file_m8_platform_iam_v1_authentication_environment_context_proto_depIdxs = nil
}
