// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: m8/platform/iam/v1/authentication_identity_context.proto

package iam

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status of the subject in the identity system.
type UserStatus int32

const (
	// User status is not specified.
	UserStatus_USER_STATUS_UNSPECIFIED UserStatus = 0
	// User is active.
	UserStatus_USER_STATUS_ACTIVE UserStatus = 1
	// User is locked.
	UserStatus_USER_STATUS_LOCKED UserStatus = 2
	// User is disabled.
	UserStatus_USER_STATUS_DISABLED UserStatus = 3
	// User is pending activation or enrollment.
	UserStatus_USER_STATUS_PENDING UserStatus = 4
	// User is suspended by identity configuration or administration.
	UserStatus_USER_STATUS_SUSPENDED UserStatus = 5
	// User has been deleted.
	UserStatus_USER_STATUS_DELETED UserStatus = 6
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "USER_STATUS_UNSPECIFIED",
		1: "USER_STATUS_ACTIVE",
		2: "USER_STATUS_LOCKED",
		3: "USER_STATUS_DISABLED",
		4: "USER_STATUS_PENDING",
		5: "USER_STATUS_SUSPENDED",
		6: "USER_STATUS_DELETED",
	}
	UserStatus_value = map[string]int32{
		"USER_STATUS_UNSPECIFIED": 0,
		"USER_STATUS_ACTIVE":      1,
		"USER_STATUS_LOCKED":      2,
		"USER_STATUS_DISABLED":    3,
		"USER_STATUS_PENDING":     4,
		"USER_STATUS_SUSPENDED":   5,
		"USER_STATUS_DELETED":     6,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_m8_platform_iam_v1_authentication_identity_context_proto_enumTypes[0].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_m8_platform_iam_v1_authentication_identity_context_proto_enumTypes[0]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_m8_platform_iam_v1_authentication_identity_context_proto_rawDescGZIP(), []int{0}
}

// SubjectContext describes the user or workload being authenticated without raw sensitive PII.
// M8 Identity remains the source of truth for users, identity links, authenticators, and user status.
//
// Example:
// - internal subject id
// - masked email and masked phone for audit display
// - hash or reference values instead of raw identifiers
type SubjectContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable platform subject identifier.
	SubjectId string `protobuf:"bytes,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	// External subject reference or pairwise subject identifier.
	ExternalSubjectRef string `protobuf:"bytes,2,opt,name=external_subject_ref,json=externalSubjectRef,proto3" json:"external_subject_ref,omitempty"`
	// Hash of the login hint when raw login hint must not be stored.
	LoginHintHash string `protobuf:"bytes,3,opt,name=login_hint_hash,json=loginHintHash,proto3" json:"login_hint_hash,omitempty"`
	// Masked email address for safe audit display.
	EmailMasked string `protobuf:"bytes,4,opt,name=email_masked,json=emailMasked,proto3" json:"email_masked,omitempty"`
	// Masked phone number for safe audit display.
	PhoneMasked string `protobuf:"bytes,5,opt,name=phone_masked,json=phoneMasked,proto3" json:"phone_masked,omitempty"`
	// Subject status from the identity system.
	Status UserStatus `protobuf:"varint,6,opt,name=status,proto3,enum=m8.platform.iam.v1.UserStatus" json:"status,omitempty"`
	// Identity-owned subject segment or reference used as safe decision input.
	IdentitySegmentRef string `protobuf:"bytes,7,opt,name=identity_segment_ref,json=identitySegmentRef,proto3" json:"identity_segment_ref,omitempty"`
	// Reference to a tenant-local user record.
	TenantUserRef string `protobuf:"bytes,8,opt,name=tenant_user_ref,json=tenantUserRef,proto3" json:"tenant_user_ref,omitempty"`
	// Additional non-sensitive subject attributes.
	Attributes    map[string]string `protobuf:"bytes,9,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectContext) Reset() {
	*x = SubjectContext{}
	mi := &file_m8_platform_iam_v1_authentication_identity_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectContext) ProtoMessage() {}

func (x *SubjectContext) ProtoReflect() protoreflect.Message {
	mi := &file_m8_platform_iam_v1_authentication_identity_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectContext.ProtoReflect.Descriptor instead.
func (*SubjectContext) Descriptor() ([]byte, []int) {
	return file_m8_platform_iam_v1_authentication_identity_context_proto_rawDescGZIP(), []int{0}
}

func (x *SubjectContext) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *SubjectContext) GetExternalSubjectRef() string {
	if x != nil {
		return x.ExternalSubjectRef
	}
	return ""
}

func (x *SubjectContext) GetLoginHintHash() string {
	if x != nil {
		return x.LoginHintHash
	}
	return ""
}

func (x *SubjectContext) GetEmailMasked() string {
	if x != nil {
		return x.EmailMasked
	}
	return ""
}

func (x *SubjectContext) GetPhoneMasked() string {
	if x != nil {
		return x.PhoneMasked
	}
	return ""
}

func (x *SubjectContext) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_USER_STATUS_UNSPECIFIED
}

func (x *SubjectContext) GetIdentitySegmentRef() string {
	if x != nil {
		return x.IdentitySegmentRef
	}
	return ""
}

func (x *SubjectContext) GetTenantUserRef() string {
	if x != nil {
		return x.TenantUserRef
	}
	return ""
}

func (x *SubjectContext) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// SessionContext describes an existing session that may satisfy or constrain authentication.
//
// Example:
// - previous authentication is fresh enough for max_age
// - current session has AAL1 and needs AAL3 step-up
// - remembered device participates in assurance evaluation
type SessionContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current session identifier or reference.
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Previous session identifier or reference if session rotation occurred.
	PreviousSessionId string `protobuf:"bytes,2,opt,name=previous_session_id,json=previousSessionId,proto3" json:"previous_session_id,omitempty"`
	// Time when the current session was authenticated.
	AuthTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=auth_time,json=authTime,proto3" json:"auth_time,omitempty"`
	// Last authentication operation that established the session.
	LastAuthenticationId string `protobuf:"bytes,4,opt,name=last_authentication_id,json=lastAuthenticationId,proto3" json:"last_authentication_id,omitempty"`
	// Current OIDC-compatible acr value of the session.
	CurrentAcr string `protobuf:"bytes,5,opt,name=current_acr,json=currentAcr,proto3" json:"current_acr,omitempty"`
	// Current OIDC-compatible amr values of the session.
	CurrentAmr []string `protobuf:"bytes,6,rep,name=current_amr,json=currentAmr,proto3" json:"current_amr,omitempty"`
	// Normalized method references used by the session.
	CurrentMethodReferences []AuthenticationMethodReference `protobuf:"varint,7,rep,packed,name=current_method_references,json=currentMethodReferences,proto3,enum=m8.platform.iam.v1.AuthenticationMethodReference" json:"current_method_references,omitempty"`
	// Whether the session is already authenticated.
	Authenticated bool `protobuf:"varint,8,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	// Whether the device was remembered for this session.
	RememberDevice bool `protobuf:"varint,9,opt,name=remember_device,json=rememberDevice,proto3" json:"remember_device,omitempty"`
	// Session age in seconds at decision time.
	AgeSeconds int64 `protobuf:"varint,10,opt,name=age_seconds,json=ageSeconds,proto3" json:"age_seconds,omitempty"`
	// Additional non-sensitive session attributes.
	Attributes    map[string]string `protobuf:"bytes,11,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionContext) Reset() {
	*x = SessionContext{}
	mi := &file_m8_platform_iam_v1_authentication_identity_context_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionContext) ProtoMessage() {}

func (x *SessionContext) ProtoReflect() protoreflect.Message {
	mi := &file_m8_platform_iam_v1_authentication_identity_context_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionContext.ProtoReflect.Descriptor instead.
func (*SessionContext) Descriptor() ([]byte, []int) {
	return file_m8_platform_iam_v1_authentication_identity_context_proto_rawDescGZIP(), []int{1}
}

func (x *SessionContext) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionContext) GetPreviousSessionId() string {
	if x != nil {
		return x.PreviousSessionId
	}
	return ""
}

func (x *SessionContext) GetAuthTime() *timestamppb.Timestamp {
	if x != nil {
		return x.AuthTime
	}
	return nil
}

func (x *SessionContext) GetLastAuthenticationId() string {
	if x != nil {
		return x.LastAuthenticationId
	}
	return ""
}

func (x *SessionContext) GetCurrentAcr() string {
	if x != nil {
		return x.CurrentAcr
	}
	return ""
}

func (x *SessionContext) GetCurrentAmr() []string {
	if x != nil {
		return x.CurrentAmr
	}
	return nil
}

func (x *SessionContext) GetCurrentMethodReferences() []AuthenticationMethodReference {
	if x != nil {
		return x.CurrentMethodReferences
	}
	return nil
}

func (x *SessionContext) GetAuthenticated() bool {
	if x != nil {
		return x.Authenticated
	}
	return false
}

func (x *SessionContext) GetRememberDevice() bool {
	if x != nil {
		return x.RememberDevice
	}
	return false
}

func (x *SessionContext) GetAgeSeconds() int64 {
	if x != nil {
		return x.AgeSeconds
	}
	return 0
}

func (x *SessionContext) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_m8_platform_iam_v1_authentication_identity_context_proto protoreflect.FileDescriptor

const file_m8_platform_iam_v1_authentication_identity_context_proto_rawDesc = "" +
	"\n" +
	"8m8/platform/iam/v1/authentication_identity_context.proto\x12\x12m8.platform.iam.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a9m8/platform/iam/v1/authentication_assurance_context.proto\"\xf4\x03\n" +
	"\x0eSubjectContext\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x01 \x01(\tR\tsubjectId\x120\n" +
	"\x14external_subject_ref\x18\x02 \x01(\tR\x12externalSubjectRef\x12&\n" +
	"\x0flogin_hint_hash\x18\x03 \x01(\tR\rloginHintHash\x12!\n" +
	"\femail_masked\x18\x04 \x01(\tR\vemailMasked\x12!\n" +
	"\fphone_masked\x18\x05 \x01(\tR\vphoneMasked\x126\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1e.m8.platform.iam.v1.UserStatusR\x06status\x120\n" +
	"\x14identity_segment_ref\x18\a \x01(\tR\x12identitySegmentRef\x12&\n" +
	"\x0ftenant_user_ref\x18\b \x01(\tR\rtenantUserRef\x12R\n" +
	"\n" +
	"attributes\x18\t \x03(\v22.m8.platform.iam.v1.SubjectContext.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x05\n" +
	"\x0eSessionContext\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12.\n" +
	"\x13previous_session_id\x18\x02 \x01(\tR\x11previousSessionId\x127\n" +
	"\tauth_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bauthTime\x124\n" +
	"\x16last_authentication_id\x18\x04 \x01(\tR\x14lastAuthenticationId\x12\x1f\n" +
	"\vcurrent_acr\x18\x05 \x01(\tR\n" +
	"currentAcr\x12\x1f\n" +
	"\vcurrent_amr\x18\x06 \x03(\tR\n" +
	"currentAmr\x12m\n" +
	"\x19current_method_references\x18\a \x03(\x0e21.m8.platform.iam.v1.AuthenticationMethodReferenceR\x17currentMethodReferences\x12$\n" +
	"\rauthenticated\x18\b \x01(\bR\rauthenticated\x12'\n" +
	"\x0fremember_device\x18\t \x01(\bR\x0erememberDevice\x12\x1f\n" +
	"\vage_seconds\x18\n" +
	" \x01(\x03R\n" +
	"ageSeconds\x12R\n" +
	"\n" +
	"attributes\x18\v \x03(\v22.m8.platform.iam.v1.SessionContext.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xc0\x01\n" +
	"\n" +
	"UserStatus\x12\x1b\n" +
	"\x17USER_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12USER_STATUS_ACTIVE\x10\x01\x12\x16\n" +
	"\x12USER_STATUS_LOCKED\x10\x02\x12\x18\n" +
	"\x14USER_STATUS_DISABLED\x10\x03\x12\x17\n" +
	"\x13USER_STATUS_PENDING\x10\x04\x12\x19\n" +
	"\x15USER_STATUS_SUSPENDED\x10\x05\x12\x17\n" +
	"\x13USER_STATUS_DELETED\x10\x06B7Z5github.com/m8-team/go-genproto/m8/platform/iam/v1;iamb\x06proto3"

var (
	file_m8_platform_iam_v1_authentication_identity_context_proto_rawDescOnce sync.Once
	file_m8_platform_iam_v1_authentication_identity_context_proto_rawDescData []byte
)

func file_m8_platform_iam_v1_authentication_identity_context_proto_rawDescGZIP() []byte {
	file_m8_platform_iam_v1_authentication_identity_context_proto_rawDescOnce.Do(func() {
		file_m8_platform_iam_v1_authentication_identity_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_m8_platform_iam_v1_authentication_identity_context_proto_rawDesc), len(file_m8_platform_iam_v1_authentication_identity_context_proto_rawDesc)))
	})
	return file_m8_platform_iam_v1_authentication_identity_context_proto_rawDescData
}

var file_m8_platform_iam_v1_authentication_identity_context_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_m8_platform_iam_v1_authentication_identity_context_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_m8_platform_iam_v1_authentication_identity_context_proto_goTypes = []any{
	(UserStatus)(0),                    // 0: m8.platform.iam.v1.UserStatus
	(*SubjectContext)(nil),             // 1: m8.platform.iam.v1.SubjectContext
	(*SessionContext)(nil),             // 2: m8.platform.iam.v1.SessionContext
	nil,                                // 3: m8.platform.iam.v1.SubjectContext.AttributesEntry
	nil,                                // 4: m8.platform.iam.v1.SessionContext.AttributesEntry
	(*timestamppb.Timestamp)(nil),      // 5: google.protobuf.Timestamp
	(AuthenticationMethodReference)(0), // 6: m8.platform.iam.v1.AuthenticationMethodReference
}
var file_m8_platform_iam_v1_authentication_identity_context_proto_depIdxs = []int32{
	0, // 0: m8.platform.iam.v1.SubjectContext.status:type_name -> m8.platform.iam.v1.UserStatus
	3, // 1: m8.platform.iam.v1.SubjectContext.attributes:type_name -> m8.platform.iam.v1.SubjectContext.AttributesEntry
	5, // 2: m8.platform.iam.v1.SessionContext.auth_time:type_name -> google.protobuf.Timestamp
	6, // 3: m8.platform.iam.v1.SessionContext.current_method_references:type_name -> m8.platform.iam.v1.AuthenticationMethodReference
	4, // 4: m8.platform.iam.v1.SessionContext.attributes:type_name -> m8.platform.iam.v1.SessionContext.AttributesEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_m8_platform_iam_v1_authentication_identity_context_proto_init() }
func file_m8_platform_iam_v1_authentication_identity_context_proto_init() {
	if File_m8_platform_iam_v1_authentication_identity_context_proto != nil {
		return
	}
	file_m8_platform_iam_v1_authentication_assurance_context_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_m8_platform_iam_v1_authentication_identity_context_proto_rawDesc), len(file_m8_platform_iam_v1_authentication_identity_context_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_m8_platform_iam_v1_authentication_identity_context_proto_goTypes,
		DependencyIndexes: file_m8_platform_iam_v1_authentication_identity_context_proto_depIdxs,
		EnumInfos:         file_m8_platform_iam_v1_authentication_identity_context_proto_enumTypes,
		MessageInfos:      file_m8_platform_iam_v1_authentication_identity_context_proto_msgTypes,
	}.Build()
	File_m8_platform_iam_v1_authentication_identity_context_proto = out.File
	file_m8_platform_iam_v1_authentication_identity_context_proto_goTypes = nil
	file_m8_platform_iam_v1_authentication_identity_context_proto_depIdxs = nil
}
