// @generated by protoc-gen-es v2.11.0
// @generated from file m8/platform/resourcemanager/v1/organization.proto (package m8.platform.resourcemanager.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file m8/platform/resourcemanager/v1/organization.proto.
 */
export declare const file_m8_platform_resourcemanager_v1_organization: GenFile;

/**
 * Organization stores canonical metadata for a top-level organization resource.
 *
 * @generated from message m8.platform.resourcemanager.v1.Organization
 */
export declare type Organization = Message<"m8.platform.resourcemanager.v1.Organization"> & {
  /**
   * Identifier. Stable unique identifier of the organization.
   * The value is generated by the server and is returned as a UUID string.
   * The value is immutable after creation.
   * Clients must not provide this field when creating an organization.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Output only. Server-computed lifecycle state of the organization.
   * The value is always one of the defined non-zero enum values.
   *
   * @generated from field: m8.platform.resourcemanager.v1.Organization.State state = 2;
   */
  state: Organization_State;

  /**
   * Optional. Human-readable name of the organization.
   * The value may be updated by clients and must not exceed 256 characters.
   *
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * Optional. Free-form description of the organization.
   * The value may be updated by clients and must not exceed 1024 characters.
   *
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * Output only. Time when the organization was created.
   *
   * @generated from field: google.protobuf.Timestamp create_time = 5;
   */
  createTime?: Timestamp;

  /**
   * Output only. Time when the organization was most recently updated.
   *
   * @generated from field: google.protobuf.Timestamp update_time = 6;
   */
  updateTime?: Timestamp;

  /**
   * Output only. Time when the organization was soft-deleted.
   *
   * @generated from field: google.protobuf.Timestamp delete_time = 7;
   */
  deleteTime?: Timestamp;

  /**
   * Output only. Time when the soft-deleted organization is scheduled to be purged.
   *
   * @generated from field: google.protobuf.Timestamp purge_time = 8;
   */
  purgeTime?: Timestamp;

  /**
   * Optional. Opaque concurrency token for the organization.
   * If this value is provided on update or delete, it must exactly match the
   * current server-side etag or the request is rejected. Clients must not set
   * this field when creating an organization.
   *
   * @generated from field: string etag = 9;
   */
  etag: string;

  /**
   * Optional. Client-provided metadata for tooling and integrations.
   * Use namespaced keys such as "example.com/key" to avoid collisions between
   * independent producers of annotations.
   *
   * @generated from field: map<string, string> annotations = 10;
   */
  annotations: { [key: string]: string };
};

/**
 * Describes the message m8.platform.resourcemanager.v1.Organization.
 * Use `create(OrganizationSchema)` to create a new message.
 */
export declare const OrganizationSchema: GenMessage<Organization>;

/**
 * State describes the lifecycle state of an organization resource.
 *
 * @generated from enum m8.platform.resourcemanager.v1.Organization.State
 */
export enum Organization_State {
  /**
   * Invalid value. Stored resources and API responses must not use this state.
   *
   * @generated from enum value: STATE_UNSPECIFIED = 0;
   */
  STATE_UNSPECIFIED = 0,

  /**
   * The organization is being created.
   *
   * @generated from enum value: CREATING = 1;
   */
  CREATING = 1,

  /**
   * The organization is active and available for use.
   *
   * @generated from enum value: ACTIVE = 2;
   */
  ACTIVE = 2,

  /**
   * The organization is suspended and normal operations are restricted.
   *
   * @generated from enum value: SUSPENDED = 3;
   */
  SUSPENDED = 3,

  /**
   * The organization is being deleted.
   *
   * @generated from enum value: DELETING = 4;
   */
  DELETING = 4,

  /**
   * The organization has been soft-deleted.
   *
   * @generated from enum value: DELETED = 5;
   */
  DELETED = 5,

  /**
   * The organization entered a failed state.
   *
   * @generated from enum value: FAILED = 6;
   */
  FAILED = 6,
}

/**
 * Describes the enum m8.platform.resourcemanager.v1.Organization.State.
 */
export declare const Organization_StateSchema: GenEnum<Organization_State>;

