// @generated by protoc-gen-es v2.11.0
// @generated from file m8/platform/resourcemanager/v1/project_service.proto (package m8.platform.resourcemanager.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Project, ProjectSchema } from "./project_pb";
import type { EmptySchema, FieldMask } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file m8/platform/resourcemanager/v1/project_service.proto.
 */
export declare const file_m8_platform_resourcemanager_v1_project_service: GenFile;

/**
 * GetProjectRequest fetches a single project by ID.
 *
 * @generated from message m8.platform.resourcemanager.v1.GetProjectRequest
 */
export declare type GetProjectRequest = Message<"m8.platform.resourcemanager.v1.GetProjectRequest"> & {
  /**
   * Required. Stable unique identifier of the project to retrieve.
   * The value must be a valid UUID string.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message m8.platform.resourcemanager.v1.GetProjectRequest.
 * Use `create(GetProjectRequestSchema)` to create a new message.
 */
export declare const GetProjectRequestSchema: GenMessage<GetProjectRequest>;

/**
 * ListProjectsRequest lists projects visible under a workspace ID.
 *
 * @generated from message m8.platform.resourcemanager.v1.ListProjectsRequest
 */
export declare type ListProjectsRequest = Message<"m8.platform.resourcemanager.v1.ListProjectsRequest"> & {
  /**
   * Required. Stable unique identifier of the parent workspace.
   * The value must be a valid UUID string.
   * In the HTTP API, pass this field in the query string.
   *
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * Optional. The maximum number of projects to return.
   * Valid values are in the range 0 to 1000.
   * If omitted, the service returns up to 50 projects.
   * The service may return fewer results than requested.
   *
   * @generated from field: int32 page_size = 2;
   */
  pageSize: number;

  /**
   * Optional. A page token returned by a previous `ListProjects` call.
   * Use this field to retrieve the next page of results.
   *
   * When paginating, all other parameters provided to `ListProjects`
   * must match the call that produced the page token.
   * The token must not exceed 1024 characters.
   *
   * @generated from field: string page_token = 3;
   */
  pageToken: string;

  /**
   * Optional. AIP-160 compatible filter expression.
   * The expression must not exceed 1024 characters.
   *
   * @generated from field: string filter = 4;
   */
  filter: string;

  /**
   * Optional. AIP-132 compatible ordering expression.
   * The expression must not exceed 128 characters.
   *
   * @generated from field: string order_by = 5;
   */
  orderBy: string;

  /**
   * Optional. If true, soft-deleted projects are included in the response.
   *
   * @generated from field: bool show_deleted = 6;
   */
  showDeleted: boolean;
};

/**
 * Describes the message m8.platform.resourcemanager.v1.ListProjectsRequest.
 * Use `create(ListProjectsRequestSchema)` to create a new message.
 */
export declare const ListProjectsRequestSchema: GenMessage<ListProjectsRequest>;

/**
 * ListProjectsResponse returns a single page of projects.
 *
 * @generated from message m8.platform.resourcemanager.v1.ListProjectsResponse
 */
export declare type ListProjectsResponse = Message<"m8.platform.resourcemanager.v1.ListProjectsResponse"> & {
  /**
   * Projects returned for the current page.
   *
   * @generated from field: repeated m8.platform.resourcemanager.v1.Project projects = 1;
   */
  projects: Project[];

  /**
   * Token to retrieve the next page.
   * This field is empty when there are no more results.
   *
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;

  /**
   * The total number of projects that match the request.
   *
   * @generated from field: int32 total_size = 3;
   */
  totalSize: number;
};

/**
 * Describes the message m8.platform.resourcemanager.v1.ListProjectsResponse.
 * Use `create(ListProjectsResponseSchema)` to create a new message.
 */
export declare const ListProjectsResponseSchema: GenMessage<ListProjectsResponse>;

/**
 * CreateProjectRequest creates a new project.
 *
 * @generated from message m8.platform.resourcemanager.v1.CreateProjectRequest
 */
export declare type CreateProjectRequest = Message<"m8.platform.resourcemanager.v1.CreateProjectRequest"> & {
  /**
   * Required. Stable unique identifier of the parent workspace.
   * The value must be a valid UUID string.
   * In the HTTP API, pass this field in the query string.
   *
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * Required. The project to create.
   * Client-specified values in `project.id`, `project.workspace_id`,
   * `project.state`, `project.create_time`, `project.update_time`,
   * `project.delete_time`, `project.purge_time`, and `project.etag` must not
   * be set by the client. The server assigns those fields.
   *
   * @generated from field: m8.platform.resourcemanager.v1.Project project = 2;
   */
  project?: Project;
};

/**
 * Describes the message m8.platform.resourcemanager.v1.CreateProjectRequest.
 * Use `create(CreateProjectRequestSchema)` to create a new message.
 */
export declare const CreateProjectRequestSchema: GenMessage<CreateProjectRequest>;

/**
 * UpdateProjectRequest updates mutable fields on an existing project.
 *
 * @generated from message m8.platform.resourcemanager.v1.UpdateProjectRequest
 */
export declare type UpdateProjectRequest = Message<"m8.platform.resourcemanager.v1.UpdateProjectRequest"> & {
  /**
   * Required. The project to update.
   *
   * The `project.id` field identifies the resource to update and must be a
   * valid UUID string. The identifier is immutable and cannot be changed.
   * Output-only fields are ignored except for `etag`, which may be provided for
   * optimistic concurrency control.
   *
   * @generated from field: m8.platform.resourcemanager.v1.Project project = 1;
   */
  project?: Project;

  /**
   * Required. The field mask that selects which mutable fields to update.
   * Paths in the mask should refer only to fields that clients are allowed to modify.
   *
   * @generated from field: google.protobuf.FieldMask update_mask = 2;
   */
  updateMask?: FieldMask;
};

/**
 * Describes the message m8.platform.resourcemanager.v1.UpdateProjectRequest.
 * Use `create(UpdateProjectRequestSchema)` to create a new message.
 */
export declare const UpdateProjectRequestSchema: GenMessage<UpdateProjectRequest>;

/**
 * DeleteProjectRequest soft-deletes a project by ID.
 *
 * @generated from message m8.platform.resourcemanager.v1.DeleteProjectRequest
 */
export declare type DeleteProjectRequest = Message<"m8.platform.resourcemanager.v1.DeleteProjectRequest"> & {
  /**
   * Required. Stable unique identifier of the project to delete.
   * The value must be a valid UUID string.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Optional. The etag of the project.
   * If provided, the value must exactly match the current server-side etag.
   *
   * @generated from field: string etag = 2;
   */
  etag: string;

  /**
   * Optional. If true, the request succeeds even if the project does not
   * exist or has already been soft-deleted.
   *
   * @generated from field: bool allow_missing = 3;
   */
  allowMissing: boolean;
};

/**
 * Describes the message m8.platform.resourcemanager.v1.DeleteProjectRequest.
 * Use `create(DeleteProjectRequestSchema)` to create a new message.
 */
export declare const DeleteProjectRequestSchema: GenMessage<DeleteProjectRequest>;

/**
 * UndeleteProjectRequest restores a soft-deleted project.
 *
 * @generated from message m8.platform.resourcemanager.v1.UndeleteProjectRequest
 */
export declare type UndeleteProjectRequest = Message<"m8.platform.resourcemanager.v1.UndeleteProjectRequest"> & {
  /**
   * Required. Stable unique identifier of the project to restore.
   * The value must be a valid UUID string.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message m8.platform.resourcemanager.v1.UndeleteProjectRequest.
 * Use `create(UndeleteProjectRequestSchema)` to create a new message.
 */
export declare const UndeleteProjectRequestSchema: GenMessage<UndeleteProjectRequest>;

/**
 * ProjectService provides standard create, read, list, update, soft-delete,
 * and undelete operations for projects.
 *
 * @generated from service m8.platform.resourcemanager.v1.ProjectService
 */
export declare const ProjectService: GenService<{
  /**
   * GetProject returns a single project by ID.
   *
   * @generated from rpc m8.platform.resourcemanager.v1.ProjectService.GetProject
   */
  getProject: {
    methodKind: "unary";
    input: typeof GetProjectRequestSchema;
    output: typeof ProjectSchema;
  },
  /**
   * ListProjects returns a paginated list of projects under a workspace ID. In
   * the HTTP API, the parent workspace UUID is provided as a query parameter.
   *
   * @generated from rpc m8.platform.resourcemanager.v1.ProjectService.ListProjects
   */
  listProjects: {
    methodKind: "unary";
    input: typeof ListProjectsRequestSchema;
    output: typeof ListProjectsResponseSchema;
  },
  /**
   * CreateProject creates a new project under a workspace ID.
   * In the HTTP API, the parent workspace UUID is provided as a query parameter.
   *
   * @generated from rpc m8.platform.resourcemanager.v1.ProjectService.CreateProject
   */
  createProject: {
    methodKind: "unary";
    input: typeof CreateProjectRequestSchema;
    output: typeof ProjectSchema;
  },
  /**
   * UpdateProject updates mutable fields on an existing project.
   *
   * @generated from rpc m8.platform.resourcemanager.v1.ProjectService.UpdateProject
   */
  updateProject: {
    methodKind: "unary";
    input: typeof UpdateProjectRequestSchema;
    output: typeof ProjectSchema;
  },
  /**
   * DeleteProject soft-deletes a project by ID.
   *
   * @generated from rpc m8.platform.resourcemanager.v1.ProjectService.DeleteProject
   */
  deleteProject: {
    methodKind: "unary";
    input: typeof DeleteProjectRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * UndeleteProject restores a previously soft-deleted project.
   *
   * @generated from rpc m8.platform.resourcemanager.v1.ProjectService.UndeleteProject
   */
  undeleteProject: {
    methodKind: "unary";
    input: typeof UndeleteProjectRequestSchema;
    output: typeof ProjectSchema;
  },
}>;

