// @generated by protoc-gen-es v2.11.0
// @generated from file m8/platform/resourcemanager/v1/project.proto (package m8.platform.resourcemanager.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../../buf/validate/validate_pb";
import { file_google_api_field_behavior } from "../../../../google/api/field_behavior_pb";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_m8_platform_extension_v1_extension } from "../../extension/v1/extension_pb";

/**
 * Describes the file m8/platform/resourcemanager/v1/project.proto.
 */
export const file_m8_platform_resourcemanager_v1_project = /*@__PURE__*/
  fileDesc("CixtOC9wbGF0Zm9ybS9yZXNvdXJjZW1hbmFnZXIvdjEvcHJvamVjdC5wcm90bxIebTgucGxhdGZvcm0ucmVzb3VyY2VtYW5hZ2VyLnYxIuAFCgdQcm9qZWN0EhoKAmlkGAEgASgJQg7gQQjgQQW6SAVyA7ABARIhCgx3b3Jrc3BhY2VfaWQYAiABKAlCC+BBA7pIBXIDsAEBEksKBXN0YXRlGAMgASgOMi0ubTgucGxhdGZvcm0ucmVzb3VyY2VtYW5hZ2VyLnYxLlByb2plY3QuU3RhdGVCDeBBA7pIB4IBBBABIAASGQoEbmFtZRgEIAEoCUIL4EEBukgFcgMYgAISIAoLZGVzY3JpcHRpb24YBSABKAlCC+BBAbpIBXIDGIAIEjQKC2NyZWF0ZV90aW1lGAYgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEID4EEDEjQKC3VwZGF0ZV90aW1lGAcgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEID4EEDEjQKC2RlbGV0ZV90aW1lGAggASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEID4EEDEjMKCnB1cmdlX3RpbWUYCSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wQgPgQQMSEQoEZXRhZxgKIAEoCUID4EEBElIKC2Fubm90YXRpb25zGAsgAygLMjgubTgucGxhdGZvcm0ucmVzb3VyY2VtYW5hZ2VyLnYxLlByb2plY3QuQW5ub3RhdGlvbnNFbnRyeUID4EEBGjIKEEFubm90YXRpb25zRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASJtCgVTdGF0ZRIVChFTVEFURV9VTlNQRUNJRklFRBAAEgwKCENSRUFUSU5HEAESCgoGQUNUSVZFEAISDAoIQVJDSElWRUQQAxIMCghERUxFVElORxAEEgsKB0RFTEVURUQQBRIKCgZGQUlMRUQQBjorirUYJ204LnBsYXRmb3JtLnJlc291cmNlbWFuYWdlci5wcm9qZWN0cy52MUJPWk1naXRodWIuY29tL204LXRlYW0vZ28tZ2VucHJvdG8vbTgvcGxhdGZvcm0vcmVzb3VyY2VtYW5hZ2VyL3YxO3Jlc291cmNlbWFuYWdlcmIGcHJvdG8z", [file_buf_validate_validate, file_google_api_field_behavior, file_google_protobuf_timestamp, file_m8_platform_extension_v1_extension]);

/**
 * Describes the message m8.platform.resourcemanager.v1.Project.
 * Use `create(ProjectSchema)` to create a new message.
 */
export const ProjectSchema = /*@__PURE__*/
  messageDesc(file_m8_platform_resourcemanager_v1_project, 0);

/**
 * Describes the enum m8.platform.resourcemanager.v1.Project.State.
 */
export const Project_StateSchema = /*@__PURE__*/
  enumDesc(file_m8_platform_resourcemanager_v1_project, 0, 0);

/**
 * State describes the lifecycle state of a project resource.
 *
 * @generated from enum m8.platform.resourcemanager.v1.Project.State
 */
export const Project_State = /*@__PURE__*/
  tsEnum(Project_StateSchema);

