// @generated by protoc-gen-es v2.11.0
// @generated from file m8/platform/riskdecision/v1/authentication_decision_context.proto (package m8.platform.riskdecision.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_m8_platform_iam_v1_authentication_context } from "../../iam/v1/authentication_context_pb";
import { file_m8_platform_riskdecision_v1_authentication_policy_context } from "./authentication_policy_context_pb";
import { file_m8_platform_riskdecision_v1_authentication_risk_context } from "./authentication_risk_context_pb";

/**
 * Describes the file m8/platform/riskdecision/v1/authentication_decision_context.proto.
 */
export const file_m8_platform_riskdecision_v1_authentication_decision_context = /*@__PURE__*/
  fileDesc("CkFtOC9wbGF0Zm9ybS9yaXNrZGVjaXNpb24vdjEvYXV0aGVudGljYXRpb25fZGVjaXNpb25fY29udGV4dC5wcm90bxIbbTgucGxhdGZvcm0ucmlza2RlY2lzaW9uLnYxIv8CCiFBdXRoZW50aWNhdGlvblJpc2tEZWNpc2lvbkNvbnRleHQSSQoOYXV0aGVudGljYXRpb24YASABKAsyMS5tOC5wbGF0Zm9ybS5pYW0udjEuQXV0aGVudGljYXRpb25EZWNpc2lvbkNvbnRleHQSPAoEcmlzaxgCIAEoCzIuLm04LnBsYXRmb3JtLnJpc2tkZWNpc2lvbi52MS5SaXNrU2lnbmFsQ29udGV4dBI6CgZwb2xpY3kYAyABKAsyKi5tOC5wbGF0Zm9ybS5yaXNrZGVjaXNpb24udjEuUG9saWN5Q29udGV4dBJiCgphdHRyaWJ1dGVzGAQgAygLMk4ubTgucGxhdGZvcm0ucmlza2RlY2lzaW9uLnYxLkF1dGhlbnRpY2F0aW9uUmlza0RlY2lzaW9uQ29udGV4dC5BdHRyaWJ1dGVzRW50cnkaMQoPQXR0cmlidXRlc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAFCSVpHZ2l0aHViLmNvbS9tOC10ZWFtL2dvLWdlbnByb3RvL204L3BsYXRmb3JtL3Jpc2tkZWNpc2lvbi92MTtyaXNrZGVjaXNpb25iBnByb3RvMw", [file_m8_platform_iam_v1_authentication_context, file_m8_platform_riskdecision_v1_authentication_policy_context, file_m8_platform_riskdecision_v1_authentication_risk_context]);

/**
 * Describes the message m8.platform.riskdecision.v1.AuthenticationRiskDecisionContext.
 * Use `create(AuthenticationRiskDecisionContextSchema)` to create a new message.
 */
export const AuthenticationRiskDecisionContextSchema = /*@__PURE__*/
  messageDesc(file_m8_platform_riskdecision_v1_authentication_decision_context, 0);

