-- The normalized output topic must be provisioned before this job is submitted.
CREATE TABLE price_types_sink (
  id STRING,
  version STRING,
  marked BOOLEAN,
  predefined_id STRING,
  parent_id STRING,
  is_folder BOOLEAN,
  code STRING,
  name STRING,
  currency_id STRING,
  base_price_type_id STRING,
  calculated BOOLEAN,
  markup_discount_percent STRING,
  vat_included BOOLEAN,
  rounding_rule_id STRING,
  round_up BOOLEAN,
  `comment` STRING,
  department_id STRING,
  inactive BOOLEAN,
  price_group BOOLEAN,
  property_gender_id STRING,
  PRIMARY KEY (id) NOT ENFORCED
) WITH (
  'connector' = 'upsert-kafka',
  'topic' = 'flink-1c.price-types.normalized.v1',
  'properties.bootstrap.servers' = 'rc1a-an3ivliisaqgs0nb.mdb.yandexcloud.net:9091,rc1d-93nrmjafghmd0gct.mdb.yandexcloud.net:9091,rc1e-vrheh76ndbah9ciu.mdb.yandexcloud.net:9091',
  'properties.security.protocol' = 'SASL_SSL',
  'properties.sasl.mechanism' = 'SCRAM-SHA-512',
  'properties.allow.auto.create.topics' = 'false',
  'key.format' = 'json',
  'key.json.fail-on-missing-field' = 'true',
  'key.json.ignore-parse-errors' = 'false',
  'value.format' = 'json',
  'value.fields-include' = 'ALL',
  'value.json.fail-on-missing-field' = 'false',
  'value.json.ignore-parse-errors' = 'false',
  'sink.delivery-guarantee' = 'at-least-once'
);
