// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: m8/platform/resourcemanager/v1/organization.proto

package resourcemanager

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	_ "m8/platform/extension/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// State describes the lifecycle state of an organization resource.
type Organization_State int32

const (
	// Invalid value. Stored resources and API responses must not use this state.
	Organization_STATE_UNSPECIFIED Organization_State = 0
	// The organization is being created.
	Organization_CREATING Organization_State = 1
	// The organization is active and available for use.
	Organization_ACTIVE Organization_State = 2
	// The organization is suspended and normal operations are restricted.
	Organization_SUSPENDED Organization_State = 3
	// The organization is being deleted.
	Organization_DELETING Organization_State = 4
	// The organization has been soft-deleted.
	Organization_DELETED Organization_State = 5
	// The organization entered a failed state.
	Organization_FAILED Organization_State = 6
)

// Enum value maps for Organization_State.
var (
	Organization_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "CREATING",
		2: "ACTIVE",
		3: "SUSPENDED",
		4: "DELETING",
		5: "DELETED",
		6: "FAILED",
	}
	Organization_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"CREATING":          1,
		"ACTIVE":            2,
		"SUSPENDED":         3,
		"DELETING":          4,
		"DELETED":           5,
		"FAILED":            6,
	}
)

func (x Organization_State) Enum() *Organization_State {
	p := new(Organization_State)
	*p = x
	return p
}

func (x Organization_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Organization_State) Descriptor() protoreflect.EnumDescriptor {
	return file_m8_platform_resourcemanager_v1_organization_proto_enumTypes[0].Descriptor()
}

func (Organization_State) Type() protoreflect.EnumType {
	return &file_m8_platform_resourcemanager_v1_organization_proto_enumTypes[0]
}

func (x Organization_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Organization_State.Descriptor instead.
func (Organization_State) EnumDescriptor() ([]byte, []int) {
	return file_m8_platform_resourcemanager_v1_organization_proto_rawDescGZIP(), []int{0, 0}
}

// Organization stores canonical metadata for a top-level organization resource.
type Organization struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier. The resource name of the organization.
	// Format: organizations/{organization}
	// The {organization} segment must be 3 to 63 characters long, start with a
	// lowercase letter, and contain only lowercase letters, digits, and hyphens.
	// Examples: organizations/acme, organizations/acme-eu, organizations/platform123.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Output only. System-assigned stable unique identifier for the organization.
	// The value is generated by the server and is returned as a UUID4 string.
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// Output only. Server-computed lifecycle state of the organization.
	// The value is always one of the defined non-zero enum values.
	State Organization_State `protobuf:"varint,3,opt,name=state,proto3,enum=m8.platform.resourcemanager.v1.Organization_State" json:"state,omitempty"`
	// Optional. Human-readable display name of the organization.
	// The value may be updated by clients and must not exceed 256 characters.
	DisplayName string `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Optional. Free-form description of the organization.
	// The value may be updated by clients and must not exceed 256 characters.
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// Output only. Time when the organization was created.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// Output only. Time when the organization was most recently updated.
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// Output only. Time when the organization was soft-deleted.
	DeleteTime *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=delete_time,json=deleteTime,proto3" json:"delete_time,omitempty"`
	// Output only. Time when the soft-deleted organization is scheduled to be purged.
	PurgeTime *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=purge_time,json=purgeTime,proto3" json:"purge_time,omitempty"`
	// Optional. Opaque concurrency token for the organization.
	// If this value is provided on update or delete, it must exactly match the
	// current server-side etag or the request is rejected.
	Etag string `protobuf:"bytes,10,opt,name=etag,proto3" json:"etag,omitempty"`
	// Optional. Client-provided metadata for tooling and integrations.
	// Use namespaced keys such as "example.com/key" to avoid collisions between
	// independent producers of annotations.
	Annotations   map[string]string `protobuf:"bytes,11,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Organization) Reset() {
	*x = Organization{}
	mi := &file_m8_platform_resourcemanager_v1_organization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_m8_platform_resourcemanager_v1_organization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_m8_platform_resourcemanager_v1_organization_proto_rawDescGZIP(), []int{0}
}

func (x *Organization) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Organization) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Organization) GetState() Organization_State {
	if x != nil {
		return x.State
	}
	return Organization_STATE_UNSPECIFIED
}

func (x *Organization) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Organization) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Organization) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Organization) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Organization) GetDeleteTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DeleteTime
	}
	return nil
}

func (x *Organization) GetPurgeTime() *timestamppb.Timestamp {
	if x != nil {
		return x.PurgeTime
	}
	return nil
}

func (x *Organization) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *Organization) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

var File_m8_platform_resourcemanager_v1_organization_proto protoreflect.FileDescriptor

const file_m8_platform_resourcemanager_v1_organization_proto_rawDesc = "" +
	"\n" +
	"1m8/platform/resourcemanager/v1/organization.proto\x12\x1em8.platform.resourcemanager.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/api/field_info.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a(m8/platform/extension/v1/extension.proto\"\xd9\a\n" +
	"\fOrganization\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tB\x03\xe0A\bR\x04name\x12%\n" +
	"\x03uid\x18\x01 \x01(\tB\x13\xe0A\x03\xbaH\x05r\x03\xb0\x01\x01\xe2\x8c\xcf\xd7\b\x02\b\x01R\x03uid\x12W\n" +
	"\x05state\x18\x03 \x01(\x0e22.m8.platform.resourcemanager.v1.Organization.StateB\r\xe0A\x03\xbaH\a\x82\x01\x04\x10\x01 \x00R\x05state\x12.\n" +
	"\fdisplay_name\x18\x04 \x01(\tB\v\xe0A\x01\xbaH\x05r\x03\x18\x80\x02R\vdisplayName\x12-\n" +
	"\vdescription\x18\x05 \x01(\tB\v\xe0A\x01\xbaH\x05r\x03\x18\x80\x02R\vdescription\x12@\n" +
	"\vcreate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12@\n" +
	"\vupdate_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"updateTime\x12@\n" +
	"\vdelete_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"deleteTime\x12>\n" +
	"\n" +
	"purge_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\tpurgeTime\x12\x17\n" +
	"\x04etag\x18\n" +
	" \x01(\tB\x03\xe0A\x01R\x04etag\x12d\n" +
	"\vannotations\x18\v \x03(\v2=.m8.platform.resourcemanager.v1.Organization.AnnotationsEntryB\x03\xe0A\x01R\vannotations\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"n\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bCREATING\x10\x01\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x02\x12\r\n" +
	"\tSUSPENDED\x10\x03\x12\f\n" +
	"\bDELETING\x10\x04\x12\v\n" +
	"\aDELETED\x10\x05\x12\n" +
	"\n" +
	"\x06FAILED\x10\x06:\x9b\x01\xeaAh\n" +
	"+m8.platform.resourcemanager.v1/Organization\x12\x1corganizations/{organization}*\rorganizations2\forganization\x8a\xb5\x18,m8.platform.resourcemanager.organizations.v1B0Z.m8/platform/resourcemanager/v1;resourcemanagerb\x06proto3"

var (
	file_m8_platform_resourcemanager_v1_organization_proto_rawDescOnce sync.Once
	file_m8_platform_resourcemanager_v1_organization_proto_rawDescData []byte
)

func file_m8_platform_resourcemanager_v1_organization_proto_rawDescGZIP() []byte {
	file_m8_platform_resourcemanager_v1_organization_proto_rawDescOnce.Do(func() {
		file_m8_platform_resourcemanager_v1_organization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_m8_platform_resourcemanager_v1_organization_proto_rawDesc), len(file_m8_platform_resourcemanager_v1_organization_proto_rawDesc)))
	})
	return file_m8_platform_resourcemanager_v1_organization_proto_rawDescData
}

var file_m8_platform_resourcemanager_v1_organization_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_m8_platform_resourcemanager_v1_organization_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_m8_platform_resourcemanager_v1_organization_proto_goTypes = []any{
	(Organization_State)(0),       // 0: m8.platform.resourcemanager.v1.Organization.State
	(*Organization)(nil),          // 1: m8.platform.resourcemanager.v1.Organization
	nil,                           // 2: m8.platform.resourcemanager.v1.Organization.AnnotationsEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_m8_platform_resourcemanager_v1_organization_proto_depIdxs = []int32{
	0, // 0: m8.platform.resourcemanager.v1.Organization.state:type_name -> m8.platform.resourcemanager.v1.Organization.State
	3, // 1: m8.platform.resourcemanager.v1.Organization.create_time:type_name -> google.protobuf.Timestamp
	3, // 2: m8.platform.resourcemanager.v1.Organization.update_time:type_name -> google.protobuf.Timestamp
	3, // 3: m8.platform.resourcemanager.v1.Organization.delete_time:type_name -> google.protobuf.Timestamp
	3, // 4: m8.platform.resourcemanager.v1.Organization.purge_time:type_name -> google.protobuf.Timestamp
	2, // 5: m8.platform.resourcemanager.v1.Organization.annotations:type_name -> m8.platform.resourcemanager.v1.Organization.AnnotationsEntry
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_m8_platform_resourcemanager_v1_organization_proto_init() }
func file_m8_platform_resourcemanager_v1_organization_proto_init() {
	if File_m8_platform_resourcemanager_v1_organization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_m8_platform_resourcemanager_v1_organization_proto_rawDesc), len(file_m8_platform_resourcemanager_v1_organization_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_m8_platform_resourcemanager_v1_organization_proto_goTypes,
		DependencyIndexes: file_m8_platform_resourcemanager_v1_organization_proto_depIdxs,
		EnumInfos:         file_m8_platform_resourcemanager_v1_organization_proto_enumTypes,
		MessageInfos:      file_m8_platform_resourcemanager_v1_organization_proto_msgTypes,
	}.Build()
	File_m8_platform_resourcemanager_v1_organization_proto = out.File
	file_m8_platform_resourcemanager_v1_organization_proto_goTypes = nil
	file_m8_platform_resourcemanager_v1_organization_proto_depIdxs = nil
}
