// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: m8/platform/resourcemanager/v1/project_service.proto

package resourcemanager

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetProjectRequest fetches a single project by resource name.
type GetProjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The name of the project to retrieve.
	// Format: organizations/{organization}/workspaces/{workspace}/projects/{project}
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectRequest) Reset() {
	*x = GetProjectRequest{}
	mi := &file_m8_platform_resourcemanager_v1_project_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectRequest) ProtoMessage() {}

func (x *GetProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_m8_platform_resourcemanager_v1_project_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectRequest.ProtoReflect.Descriptor instead.
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return file_m8_platform_resourcemanager_v1_project_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ListProjectsRequest lists projects visible under a workspace.
type ListProjectsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The parent workspace resource name.
	// Format: organizations/{organization}/workspaces/{workspace}
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Optional. The maximum number of projects to return.
	// The service may return fewer than this value.
	// If unspecified, at most 50 projects are returned.
	// The maximum value is 1000; values above 1000 are coerced to 1000.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. A page token, received from a previous `ListProjects` call.
	// Provide this to retrieve the subsequent page.
	//
	// When paginating, all other parameters provided to `ListProjects`
	// must match the call that provided the page token.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional. AIP-160 compatible filter expression.
	Filter string `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	// Optional. AIP-132 compatible ordering expression.
	OrderBy       string `protobuf:"bytes,5,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_m8_platform_resourcemanager_v1_project_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_m8_platform_resourcemanager_v1_project_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_m8_platform_resourcemanager_v1_project_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListProjectsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListProjectsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProjectsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListProjectsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListProjectsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

// ListProjectsResponse returns a single page of projects.
type ListProjectsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Projects returned for the current page.
	Projects []*Project `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	// Token to retrieve the next page. Empty when there are no more results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// The total number of projects that match the request.
	TotalSize     int32 `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_m8_platform_resourcemanager_v1_project_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_m8_platform_resourcemanager_v1_project_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_m8_platform_resourcemanager_v1_project_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *ListProjectsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListProjectsResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

// CreateProjectRequest creates a new project.
type CreateProjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The parent workspace resource name.
	// Format: organizations/{organization}/workspaces/{workspace}
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Optional. The ID to use for the project, which becomes the final
	// component of the project resource name.
	ProjectId string `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Required. The project to create.
	// The `project.name` and `project.uid` fields are ignored on create.
	Project *Project `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	// Optional. A unique request ID for idempotent create requests.
	RequestId     string `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_m8_platform_resourcemanager_v1_project_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_m8_platform_resourcemanager_v1_project_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_m8_platform_resourcemanager_v1_project_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateProjectRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateProjectRequest) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *CreateProjectRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// UpdateProjectRequest updates mutable fields on an existing project.
type UpdateProjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The project to update.
	//
	// The project's `name` field is used to identify the project to update.
	// Format: organizations/{organization}/workspaces/{workspace}/projects/{project}
	Project *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	// Required. The list of fields to update.
	UpdateMask *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	// Optional. A unique request ID for idempotent update requests.
	RequestId     string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectRequest) Reset() {
	*x = UpdateProjectRequest{}
	mi := &file_m8_platform_resourcemanager_v1_project_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectRequest) ProtoMessage() {}

func (x *UpdateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_m8_platform_resourcemanager_v1_project_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectRequest.ProtoReflect.Descriptor instead.
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) {
	return file_m8_platform_resourcemanager_v1_project_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProjectRequest) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *UpdateProjectRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *UpdateProjectRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// DeleteProjectRequest deletes a project by resource name.
type DeleteProjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The name of the project to delete.
	// Format: organizations/{organization}/workspaces/{workspace}/projects/{project}
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional. A unique request ID for idempotent delete requests.
	RequestId     string `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectRequest) Reset() {
	*x = DeleteProjectRequest{}
	mi := &file_m8_platform_resourcemanager_v1_project_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectRequest) ProtoMessage() {}

func (x *DeleteProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_m8_platform_resourcemanager_v1_project_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteProjectRequest) Descriptor() ([]byte, []int) {
	return file_m8_platform_resourcemanager_v1_project_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteProjectRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_m8_platform_resourcemanager_v1_project_service_proto protoreflect.FileDescriptor

const file_m8_platform_resourcemanager_v1_project_service_proto_rawDesc = "" +
	"\n" +
	"4m8/platform/resourcemanager/v1/project_service.proto\x12\x1em8.platform.resourcemanager.v1\x1a\x1bbuf/validate/validate.proto\x1a$gnostic/openapi/v3/annotations.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a,m8/platform/resourcemanager/v1/project.proto\"\xb0\x01\n" +
	"\x11GetProjectRequest\x12\x9a\x01\n" +
	"\x04name\x18\x01 \x01(\tB\x85\x01\xe0A\x02\xfaA\x11\n" +
	"\x0fm8.team/Project\xbaHkri\x10-\x18\xe1\x012b^organizations/[a-z][a-z0-9-]{2,62}/workspaces/[a-z][a-z0-9-]{2,62}/projects/[a-z][a-z0-9-]{2,62}$R\x04name\"\xbe\x02\n" +
	"\x13ListProjectsRequest\x12\x81\x01\n" +
	"\x06parent\x18\x01 \x01(\tBi\xe0A\x02\xfaA\x13\n" +
	"\x11m8.team/Workspace\xbaHMrK\x10 \x18\x98\x012D^organizations/[a-z][a-z0-9-]{2,62}/workspaces/[a-z][a-z0-9-]{2,62}$R\x06parent\x12*\n" +
	"\tpage_size\x18\x02 \x01(\x05B\r\xe0A\x01\xbaH\a\x1a\x05\x18\xe8\a(\x00R\bpageSize\x12*\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tB\v\xe0A\x01\xbaH\x05r\x03\x18\x80\bR\tpageToken\x12#\n" +
	"\x06filter\x18\x04 \x01(\tB\v\xe0A\x01\xbaH\x05r\x03\x18\x80\bR\x06filter\x12&\n" +
	"\border_by\x18\x05 \x01(\tB\v\xe0A\x01\xbaH\x05r\x03\x18\x80\x01R\aorderBy\"\xa2\x01\n" +
	"\x14ListProjectsResponse\x12C\n" +
	"\bprojects\x18\x01 \x03(\v2'.m8.platform.resourcemanager.v1.ProjectR\bprojects\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x05R\ttotalSize\"\xd1\x02\n" +
	"\x14CreateProjectRequest\x12\x81\x01\n" +
	"\x06parent\x18\x01 \x01(\tBi\xe0A\x02\xfaA\x13\n" +
	"\x11m8.team/Workspace\xbaHMrK\x10 \x18\x98\x012D^organizations/[a-z][a-z0-9-]{2,62}/workspaces/[a-z][a-z0-9-]{2,62}$R\x06parent\x12C\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tB$\xe0A\x01\xbaH\x1er\x1c\x10\x03\x18?2\x16^[a-z][a-z0-9-]{2,62}$R\tprojectId\x12L\n" +
	"\aproject\x18\x03 \x01(\v2'.m8.platform.resourcemanager.v1.ProjectB\t\xe0A\x02\xbaH\x03\xc8\x01\x01R\aproject\x12\"\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tB\x03\xe0A\x01R\trequestId\"\xd0\x01\n" +
	"\x14UpdateProjectRequest\x12L\n" +
	"\aproject\x18\x01 \x01(\v2'.m8.platform.resourcemanager.v1.ProjectB\t\xe0A\x02\xbaH\x03\xc8\x01\x01R\aproject\x12F\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\t\xe0A\x02\xbaH\x03\xc8\x01\x01R\n" +
	"updateMask\x12\"\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tB\x03\xe0A\x01R\trequestId\"\xd7\x01\n" +
	"\x14DeleteProjectRequest\x12\x9a\x01\n" +
	"\x04name\x18\x01 \x01(\tB\x85\x01\xe0A\x02\xfaA\x11\n" +
	"\x0fm8.team/Project\xbaHkri\x10-\x18\xe1\x012b^organizations/[a-z][a-z0-9-]{2,62}/workspaces/[a-z][a-z0-9-]{2,62}/projects/[a-z][a-z0-9-]{2,62}$R\x04name\x12\"\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tB\x03\xe0A\x01R\trequestId2\xa4\n" +
	"\n" +
	"\x0eProjectService\x12\xe8\x01\n" +
	"\n" +
	"GetProject\x121.m8.platform.resourcemanager.v1.GetProjectRequest\x1a'.m8.platform.resourcemanager.v1.Project\"~\xdaA\x04name\xbaG:\x12\x03Get\x1a.Returns a single project by its resource name.*\x03get\x82\xd3\xe4\x93\x024\x122/v1/{name=organizations/*/workspaces/*/projects/*}\x12\x93\x02\n" +
	"\fListProjects\x123.m8.platform.resourcemanager.v1.ListProjectsRequest\x1a4.m8.platform.resourcemanager.v1.ListProjectsResponse\"\x97\x01\xdaA\x06parent\xbaGQ\x12\x04List\x1aCReturns a paginated list of projects under the specified workspace.*\x04list\x82\xd3\xe4\x93\x024\x122/v1/{parent=organizations/*/workspaces/*}/projects\x12\x99\x02\n" +
	"\rCreateProject\x124.m8.platform.resourcemanager.v1.CreateProjectRequest\x1a'.m8.platform.resourcemanager.v1.Project\"\xa8\x01\xdaA\x19parent,project,project_id\xbaGF\x12\x06Create\x1a4Creates a new project under the specified workspace.*\x06create\x82\xd3\xe4\x93\x02=:\aproject\"2/v1/{parent=organizations/*/workspaces/*}/projects\x12\x95\x02\n" +
	"\rUpdateProject\x124.m8.platform.resourcemanager.v1.UpdateProjectRequest\x1a'.m8.platform.resourcemanager.v1.Project\"\xa4\x01\xdaA\x13project,update_mask\xbaG@\x12\x06Update\x1a.Updates mutable fields of an existing project.*\x06update\x82\xd3\xe4\x93\x02E:\aproject2:/v1/{project.name=organizations/*/workspaces/*/projects/*}\x12\xdc\x01\n" +
	"\rDeleteProject\x124.m8.platform.resourcemanager.v1.DeleteProjectRequest\x1a\x16.google.protobuf.Empty\"}\xdaA\x04name\xbaG9\x12\x06Delete\x1a'Deletes a project by its resource name.*\x06delete\x82\xd3\xe4\x93\x024*2/v1/{name=organizations/*/workspaces/*/projects/*}B0Z.m8/platform/resourcemanager/v1;resourcemanagerb\x06proto3"

var (
	file_m8_platform_resourcemanager_v1_project_service_proto_rawDescOnce sync.Once
	file_m8_platform_resourcemanager_v1_project_service_proto_rawDescData []byte
)

func file_m8_platform_resourcemanager_v1_project_service_proto_rawDescGZIP() []byte {
	file_m8_platform_resourcemanager_v1_project_service_proto_rawDescOnce.Do(func() {
		file_m8_platform_resourcemanager_v1_project_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_m8_platform_resourcemanager_v1_project_service_proto_rawDesc), len(file_m8_platform_resourcemanager_v1_project_service_proto_rawDesc)))
	})
	return file_m8_platform_resourcemanager_v1_project_service_proto_rawDescData
}

var file_m8_platform_resourcemanager_v1_project_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_m8_platform_resourcemanager_v1_project_service_proto_goTypes = []any{
	(*GetProjectRequest)(nil),     // 0: m8.platform.resourcemanager.v1.GetProjectRequest
	(*ListProjectsRequest)(nil),   // 1: m8.platform.resourcemanager.v1.ListProjectsRequest
	(*ListProjectsResponse)(nil),  // 2: m8.platform.resourcemanager.v1.ListProjectsResponse
	(*CreateProjectRequest)(nil),  // 3: m8.platform.resourcemanager.v1.CreateProjectRequest
	(*UpdateProjectRequest)(nil),  // 4: m8.platform.resourcemanager.v1.UpdateProjectRequest
	(*DeleteProjectRequest)(nil),  // 5: m8.platform.resourcemanager.v1.DeleteProjectRequest
	(*Project)(nil),               // 6: m8.platform.resourcemanager.v1.Project
	(*fieldmaskpb.FieldMask)(nil), // 7: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_m8_platform_resourcemanager_v1_project_service_proto_depIdxs = []int32{
	6, // 0: m8.platform.resourcemanager.v1.ListProjectsResponse.projects:type_name -> m8.platform.resourcemanager.v1.Project
	6, // 1: m8.platform.resourcemanager.v1.CreateProjectRequest.project:type_name -> m8.platform.resourcemanager.v1.Project
	6, // 2: m8.platform.resourcemanager.v1.UpdateProjectRequest.project:type_name -> m8.platform.resourcemanager.v1.Project
	7, // 3: m8.platform.resourcemanager.v1.UpdateProjectRequest.update_mask:type_name -> google.protobuf.FieldMask
	0, // 4: m8.platform.resourcemanager.v1.ProjectService.GetProject:input_type -> m8.platform.resourcemanager.v1.GetProjectRequest
	1, // 5: m8.platform.resourcemanager.v1.ProjectService.ListProjects:input_type -> m8.platform.resourcemanager.v1.ListProjectsRequest
	3, // 6: m8.platform.resourcemanager.v1.ProjectService.CreateProject:input_type -> m8.platform.resourcemanager.v1.CreateProjectRequest
	4, // 7: m8.platform.resourcemanager.v1.ProjectService.UpdateProject:input_type -> m8.platform.resourcemanager.v1.UpdateProjectRequest
	5, // 8: m8.platform.resourcemanager.v1.ProjectService.DeleteProject:input_type -> m8.platform.resourcemanager.v1.DeleteProjectRequest
	6, // 9: m8.platform.resourcemanager.v1.ProjectService.GetProject:output_type -> m8.platform.resourcemanager.v1.Project
	2, // 10: m8.platform.resourcemanager.v1.ProjectService.ListProjects:output_type -> m8.platform.resourcemanager.v1.ListProjectsResponse
	6, // 11: m8.platform.resourcemanager.v1.ProjectService.CreateProject:output_type -> m8.platform.resourcemanager.v1.Project
	6, // 12: m8.platform.resourcemanager.v1.ProjectService.UpdateProject:output_type -> m8.platform.resourcemanager.v1.Project
	8, // 13: m8.platform.resourcemanager.v1.ProjectService.DeleteProject:output_type -> google.protobuf.Empty
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_m8_platform_resourcemanager_v1_project_service_proto_init() }
func file_m8_platform_resourcemanager_v1_project_service_proto_init() {
	if File_m8_platform_resourcemanager_v1_project_service_proto != nil {
		return
	}
	file_m8_platform_resourcemanager_v1_project_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_m8_platform_resourcemanager_v1_project_service_proto_rawDesc), len(file_m8_platform_resourcemanager_v1_project_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_m8_platform_resourcemanager_v1_project_service_proto_goTypes,
		DependencyIndexes: file_m8_platform_resourcemanager_v1_project_service_proto_depIdxs,
		MessageInfos:      file_m8_platform_resourcemanager_v1_project_service_proto_msgTypes,
	}.Build()
	File_m8_platform_resourcemanager_v1_project_service_proto = out.File
	file_m8_platform_resourcemanager_v1_project_service_proto_goTypes = nil
	file_m8_platform_resourcemanager_v1_project_service_proto_depIdxs = nil
}
