apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: iamd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["./iamd"]
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: IAM_GRPC_ADDRESS
              value: {{ .Values.env.IAM_GRPC_ADDRESS | quote }}
---
{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-worker
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["./worker"]
{{- end }}
