// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: m8/platform/riskdecision/v1/authentication_decision.proto

package riskdecision

import (
	v1 "github.com/m8-team/go-genproto/m8/platform/iam/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RiskLevel int32

const (
	RiskLevel_RISK_LEVEL_UNSPECIFIED RiskLevel = 0
	RiskLevel_RISK_LEVEL_LOW         RiskLevel = 1
	RiskLevel_RISK_LEVEL_MEDIUM      RiskLevel = 2
	RiskLevel_RISK_LEVEL_HIGH        RiskLevel = 3
	RiskLevel_RISK_LEVEL_CRITICAL    RiskLevel = 4
)

// Enum value maps for RiskLevel.
var (
	RiskLevel_name = map[int32]string{
		0: "RISK_LEVEL_UNSPECIFIED",
		1: "RISK_LEVEL_LOW",
		2: "RISK_LEVEL_MEDIUM",
		3: "RISK_LEVEL_HIGH",
		4: "RISK_LEVEL_CRITICAL",
	}
	RiskLevel_value = map[string]int32{
		"RISK_LEVEL_UNSPECIFIED": 0,
		"RISK_LEVEL_LOW":         1,
		"RISK_LEVEL_MEDIUM":      2,
		"RISK_LEVEL_HIGH":        3,
		"RISK_LEVEL_CRITICAL":    4,
	}
)

func (x RiskLevel) Enum() *RiskLevel {
	p := new(RiskLevel)
	*p = x
	return p
}

func (x RiskLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RiskLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_m8_platform_riskdecision_v1_authentication_decision_proto_enumTypes[0].Descriptor()
}

func (RiskLevel) Type() protoreflect.EnumType {
	return &file_m8_platform_riskdecision_v1_authentication_decision_proto_enumTypes[0]
}

func (x RiskLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RiskLevel.Descriptor instead.
func (RiskLevel) EnumDescriptor() ([]byte, []int) {
	return file_m8_platform_riskdecision_v1_authentication_decision_proto_rawDescGZIP(), []int{0}
}

type AuthenticationDecisionAction int32

const (
	AuthenticationDecisionAction_AUTHENTICATION_DECISION_ACTION_UNSPECIFIED AuthenticationDecisionAction = 0
	AuthenticationDecisionAction_AUTHENTICATION_DECISION_ACTION_ALLOW       AuthenticationDecisionAction = 1
	AuthenticationDecisionAction_AUTHENTICATION_DECISION_ACTION_DENY        AuthenticationDecisionAction = 2
	AuthenticationDecisionAction_AUTHENTICATION_DECISION_ACTION_CHALLENGE   AuthenticationDecisionAction = 3
	AuthenticationDecisionAction_AUTHENTICATION_DECISION_ACTION_STEP_UP     AuthenticationDecisionAction = 4
	AuthenticationDecisionAction_AUTHENTICATION_DECISION_ACTION_FALLBACK    AuthenticationDecisionAction = 5
	AuthenticationDecisionAction_AUTHENTICATION_DECISION_ACTION_REVIEW      AuthenticationDecisionAction = 6
)

// Enum value maps for AuthenticationDecisionAction.
var (
	AuthenticationDecisionAction_name = map[int32]string{
		0: "AUTHENTICATION_DECISION_ACTION_UNSPECIFIED",
		1: "AUTHENTICATION_DECISION_ACTION_ALLOW",
		2: "AUTHENTICATION_DECISION_ACTION_DENY",
		3: "AUTHENTICATION_DECISION_ACTION_CHALLENGE",
		4: "AUTHENTICATION_DECISION_ACTION_STEP_UP",
		5: "AUTHENTICATION_DECISION_ACTION_FALLBACK",
		6: "AUTHENTICATION_DECISION_ACTION_REVIEW",
	}
	AuthenticationDecisionAction_value = map[string]int32{
		"AUTHENTICATION_DECISION_ACTION_UNSPECIFIED": 0,
		"AUTHENTICATION_DECISION_ACTION_ALLOW":       1,
		"AUTHENTICATION_DECISION_ACTION_DENY":        2,
		"AUTHENTICATION_DECISION_ACTION_CHALLENGE":   3,
		"AUTHENTICATION_DECISION_ACTION_STEP_UP":     4,
		"AUTHENTICATION_DECISION_ACTION_FALLBACK":    5,
		"AUTHENTICATION_DECISION_ACTION_REVIEW":      6,
	}
)

func (x AuthenticationDecisionAction) Enum() *AuthenticationDecisionAction {
	p := new(AuthenticationDecisionAction)
	*p = x
	return p
}

func (x AuthenticationDecisionAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthenticationDecisionAction) Descriptor() protoreflect.EnumDescriptor {
	return file_m8_platform_riskdecision_v1_authentication_decision_proto_enumTypes[1].Descriptor()
}

func (AuthenticationDecisionAction) Type() protoreflect.EnumType {
	return &file_m8_platform_riskdecision_v1_authentication_decision_proto_enumTypes[1]
}

func (x AuthenticationDecisionAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthenticationDecisionAction.Descriptor instead.
func (AuthenticationDecisionAction) EnumDescriptor() ([]byte, []int) {
	return file_m8_platform_riskdecision_v1_authentication_decision_proto_rawDescGZIP(), []int{1}
}

type AuthenticationDecision struct {
	state                    protoimpl.MessageState             `protogen:"open.v1"`
	DecisionId               string                             `protobuf:"bytes,1,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	Action                   AuthenticationDecisionAction       `protobuf:"varint,2,opt,name=action,proto3,enum=m8.platform.riskdecision.v1.AuthenticationDecisionAction" json:"action,omitempty"`
	SelectedChallenge        v1.AuthenticationChallenge         `protobuf:"varint,3,opt,name=selected_challenge,json=selectedChallenge,proto3,enum=m8.platform.iam.v1.AuthenticationChallenge" json:"selected_challenge,omitempty"`
	CurrentChallenge         v1.AuthenticationChallenge         `protobuf:"varint,4,opt,name=current_challenge,json=currentChallenge,proto3,enum=m8.platform.iam.v1.AuthenticationChallenge" json:"current_challenge,omitempty"`
	DeliveryChannel          v1.ChallengeDeliveryChannel        `protobuf:"varint,5,opt,name=delivery_channel,json=deliveryChannel,proto3,enum=m8.platform.iam.v1.ChallengeDeliveryChannel" json:"delivery_channel,omitempty"`
	RequiredAcr              string                             `protobuf:"bytes,6,opt,name=required_acr,json=requiredAcr,proto3" json:"required_acr,omitempty"`
	ExpectedAmr              []string                           `protobuf:"bytes,7,rep,name=expected_amr,json=expectedAmr,proto3" json:"expected_amr,omitempty"`
	ExpectedMethodReferences []v1.AuthenticationMethodReference `protobuf:"varint,8,rep,packed,name=expected_method_references,json=expectedMethodReferences,proto3,enum=m8.platform.iam.v1.AuthenticationMethodReference" json:"expected_method_references,omitempty"`
	FallbackChallenges       []v1.AuthenticationChallenge       `protobuf:"varint,9,rep,packed,name=fallback_challenges,json=fallbackChallenges,proto3,enum=m8.platform.iam.v1.AuthenticationChallenge" json:"fallback_challenges,omitempty"`
	Reasons                  []string                           `protobuf:"bytes,10,rep,name=reasons,proto3" json:"reasons,omitempty"`
	RiskScore                float64                            `protobuf:"fixed64,11,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	RiskLevel                RiskLevel                          `protobuf:"varint,12,opt,name=risk_level,json=riskLevel,proto3,enum=m8.platform.riskdecision.v1.RiskLevel" json:"risk_level,omitempty"`
	PolicyId                 string                             `protobuf:"bytes,13,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	PolicyVersion            string                             `protobuf:"bytes,14,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	DecisionTime             *timestamppb.Timestamp             `protobuf:"bytes,15,opt,name=decision_time,json=decisionTime,proto3" json:"decision_time,omitempty"`
	Attributes               map[string]string                  `protobuf:"bytes,16,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AuthenticationDecision) Reset() {
	*x = AuthenticationDecision{}
	mi := &file_m8_platform_riskdecision_v1_authentication_decision_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationDecision) ProtoMessage() {}

func (x *AuthenticationDecision) ProtoReflect() protoreflect.Message {
	mi := &file_m8_platform_riskdecision_v1_authentication_decision_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationDecision.ProtoReflect.Descriptor instead.
func (*AuthenticationDecision) Descriptor() ([]byte, []int) {
	return file_m8_platform_riskdecision_v1_authentication_decision_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticationDecision) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *AuthenticationDecision) GetAction() AuthenticationDecisionAction {
	if x != nil {
		return x.Action
	}
	return AuthenticationDecisionAction_AUTHENTICATION_DECISION_ACTION_UNSPECIFIED
}

func (x *AuthenticationDecision) GetSelectedChallenge() v1.AuthenticationChallenge {
	if x != nil {
		return x.SelectedChallenge
	}
	return v1.AuthenticationChallenge(0)
}

func (x *AuthenticationDecision) GetCurrentChallenge() v1.AuthenticationChallenge {
	if x != nil {
		return x.CurrentChallenge
	}
	return v1.AuthenticationChallenge(0)
}

func (x *AuthenticationDecision) GetDeliveryChannel() v1.ChallengeDeliveryChannel {
	if x != nil {
		return x.DeliveryChannel
	}
	return v1.ChallengeDeliveryChannel(0)
}

func (x *AuthenticationDecision) GetRequiredAcr() string {
	if x != nil {
		return x.RequiredAcr
	}
	return ""
}

func (x *AuthenticationDecision) GetExpectedAmr() []string {
	if x != nil {
		return x.ExpectedAmr
	}
	return nil
}

func (x *AuthenticationDecision) GetExpectedMethodReferences() []v1.AuthenticationMethodReference {
	if x != nil {
		return x.ExpectedMethodReferences
	}
	return nil
}

func (x *AuthenticationDecision) GetFallbackChallenges() []v1.AuthenticationChallenge {
	if x != nil {
		return x.FallbackChallenges
	}
	return nil
}

func (x *AuthenticationDecision) GetReasons() []string {
	if x != nil {
		return x.Reasons
	}
	return nil
}

func (x *AuthenticationDecision) GetRiskScore() float64 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *AuthenticationDecision) GetRiskLevel() RiskLevel {
	if x != nil {
		return x.RiskLevel
	}
	return RiskLevel_RISK_LEVEL_UNSPECIFIED
}

func (x *AuthenticationDecision) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *AuthenticationDecision) GetPolicyVersion() string {
	if x != nil {
		return x.PolicyVersion
	}
	return ""
}

func (x *AuthenticationDecision) GetDecisionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DecisionTime
	}
	return nil
}

func (x *AuthenticationDecision) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_m8_platform_riskdecision_v1_authentication_decision_proto protoreflect.FileDescriptor

const file_m8_platform_riskdecision_v1_authentication_decision_proto_rawDesc = "" +
	"\n" +
	"9m8/platform/riskdecision/v1/authentication_decision.proto\x12\x1bm8.platform.riskdecision.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a8m8/platform/iam/v1/authentication_decision_context.proto\"\xd9\b\n" +
	"\x16AuthenticationDecision\x12\x1f\n" +
	"\vdecision_id\x18\x01 \x01(\tR\n" +
	"decisionId\x12Q\n" +
	"\x06action\x18\x02 \x01(\x0e29.m8.platform.riskdecision.v1.AuthenticationDecisionActionR\x06action\x12Z\n" +
	"\x12selected_challenge\x18\x03 \x01(\x0e2+.m8.platform.iam.v1.AuthenticationChallengeR\x11selectedChallenge\x12X\n" +
	"\x11current_challenge\x18\x04 \x01(\x0e2+.m8.platform.iam.v1.AuthenticationChallengeR\x10currentChallenge\x12W\n" +
	"\x10delivery_channel\x18\x05 \x01(\x0e2,.m8.platform.iam.v1.ChallengeDeliveryChannelR\x0fdeliveryChannel\x12!\n" +
	"\frequired_acr\x18\x06 \x01(\tR\vrequiredAcr\x12!\n" +
	"\fexpected_amr\x18\a \x03(\tR\vexpectedAmr\x12o\n" +
	"\x1aexpected_method_references\x18\b \x03(\x0e21.m8.platform.iam.v1.AuthenticationMethodReferenceR\x18expectedMethodReferences\x12\\\n" +
	"\x13fallback_challenges\x18\t \x03(\x0e2+.m8.platform.iam.v1.AuthenticationChallengeR\x12fallbackChallenges\x12\x18\n" +
	"\areasons\x18\n" +
	" \x03(\tR\areasons\x12\x1d\n" +
	"\n" +
	"risk_score\x18\v \x01(\x01R\triskScore\x12E\n" +
	"\n" +
	"risk_level\x18\f \x01(\x0e2&.m8.platform.riskdecision.v1.RiskLevelR\triskLevel\x12\x1b\n" +
	"\tpolicy_id\x18\r \x01(\tR\bpolicyId\x12%\n" +
	"\x0epolicy_version\x18\x0e \x01(\tR\rpolicyVersion\x12?\n" +
	"\rdecision_time\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\fdecisionTime\x12c\n" +
	"\n" +
	"attributes\x18\x10 \x03(\v2C.m8.platform.riskdecision.v1.AuthenticationDecision.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x80\x01\n" +
	"\tRiskLevel\x12\x1a\n" +
	"\x16RISK_LEVEL_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eRISK_LEVEL_LOW\x10\x01\x12\x15\n" +
	"\x11RISK_LEVEL_MEDIUM\x10\x02\x12\x13\n" +
	"\x0fRISK_LEVEL_HIGH\x10\x03\x12\x17\n" +
	"\x13RISK_LEVEL_CRITICAL\x10\x04*\xd3\x02\n" +
	"\x1cAuthenticationDecisionAction\x12.\n" +
	"*AUTHENTICATION_DECISION_ACTION_UNSPECIFIED\x10\x00\x12(\n" +
	"$AUTHENTICATION_DECISION_ACTION_ALLOW\x10\x01\x12'\n" +
	"#AUTHENTICATION_DECISION_ACTION_DENY\x10\x02\x12,\n" +
	"(AUTHENTICATION_DECISION_ACTION_CHALLENGE\x10\x03\x12*\n" +
	"&AUTHENTICATION_DECISION_ACTION_STEP_UP\x10\x04\x12+\n" +
	"'AUTHENTICATION_DECISION_ACTION_FALLBACK\x10\x05\x12)\n" +
	"%AUTHENTICATION_DECISION_ACTION_REVIEW\x10\x06BIZGgithub.com/m8-team/go-genproto/m8/platform/riskdecision/v1;riskdecisionb\x06proto3"

var (
	file_m8_platform_riskdecision_v1_authentication_decision_proto_rawDescOnce sync.Once
	file_m8_platform_riskdecision_v1_authentication_decision_proto_rawDescData []byte
)

func file_m8_platform_riskdecision_v1_authentication_decision_proto_rawDescGZIP() []byte {
	file_m8_platform_riskdecision_v1_authentication_decision_proto_rawDescOnce.Do(func() {
		file_m8_platform_riskdecision_v1_authentication_decision_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_m8_platform_riskdecision_v1_authentication_decision_proto_rawDesc), len(file_m8_platform_riskdecision_v1_authentication_decision_proto_rawDesc)))
	})
	return file_m8_platform_riskdecision_v1_authentication_decision_proto_rawDescData
}

var file_m8_platform_riskdecision_v1_authentication_decision_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_m8_platform_riskdecision_v1_authentication_decision_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_m8_platform_riskdecision_v1_authentication_decision_proto_goTypes = []any{
	(RiskLevel)(0),                        // 0: m8.platform.riskdecision.v1.RiskLevel
	(AuthenticationDecisionAction)(0),     // 1: m8.platform.riskdecision.v1.AuthenticationDecisionAction
	(*AuthenticationDecision)(nil),        // 2: m8.platform.riskdecision.v1.AuthenticationDecision
	nil,                                   // 3: m8.platform.riskdecision.v1.AuthenticationDecision.AttributesEntry
	(v1.AuthenticationChallenge)(0),       // 4: m8.platform.iam.v1.AuthenticationChallenge
	(v1.ChallengeDeliveryChannel)(0),      // 5: m8.platform.iam.v1.ChallengeDeliveryChannel
	(v1.AuthenticationMethodReference)(0), // 6: m8.platform.iam.v1.AuthenticationMethodReference
	(*timestamppb.Timestamp)(nil),         // 7: google.protobuf.Timestamp
}
var file_m8_platform_riskdecision_v1_authentication_decision_proto_depIdxs = []int32{
	1, // 0: m8.platform.riskdecision.v1.AuthenticationDecision.action:type_name -> m8.platform.riskdecision.v1.AuthenticationDecisionAction
	4, // 1: m8.platform.riskdecision.v1.AuthenticationDecision.selected_challenge:type_name -> m8.platform.iam.v1.AuthenticationChallenge
	4, // 2: m8.platform.riskdecision.v1.AuthenticationDecision.current_challenge:type_name -> m8.platform.iam.v1.AuthenticationChallenge
	5, // 3: m8.platform.riskdecision.v1.AuthenticationDecision.delivery_channel:type_name -> m8.platform.iam.v1.ChallengeDeliveryChannel
	6, // 4: m8.platform.riskdecision.v1.AuthenticationDecision.expected_method_references:type_name -> m8.platform.iam.v1.AuthenticationMethodReference
	4, // 5: m8.platform.riskdecision.v1.AuthenticationDecision.fallback_challenges:type_name -> m8.platform.iam.v1.AuthenticationChallenge
	0, // 6: m8.platform.riskdecision.v1.AuthenticationDecision.risk_level:type_name -> m8.platform.riskdecision.v1.RiskLevel
	7, // 7: m8.platform.riskdecision.v1.AuthenticationDecision.decision_time:type_name -> google.protobuf.Timestamp
	3, // 8: m8.platform.riskdecision.v1.AuthenticationDecision.attributes:type_name -> m8.platform.riskdecision.v1.AuthenticationDecision.AttributesEntry
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_m8_platform_riskdecision_v1_authentication_decision_proto_init() }
func file_m8_platform_riskdecision_v1_authentication_decision_proto_init() {
	if File_m8_platform_riskdecision_v1_authentication_decision_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_m8_platform_riskdecision_v1_authentication_decision_proto_rawDesc), len(file_m8_platform_riskdecision_v1_authentication_decision_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_m8_platform_riskdecision_v1_authentication_decision_proto_goTypes,
		DependencyIndexes: file_m8_platform_riskdecision_v1_authentication_decision_proto_depIdxs,
		EnumInfos:         file_m8_platform_riskdecision_v1_authentication_decision_proto_enumTypes,
		MessageInfos:      file_m8_platform_riskdecision_v1_authentication_decision_proto_msgTypes,
	}.Build()
	File_m8_platform_riskdecision_v1_authentication_decision_proto = out.File
	file_m8_platform_riskdecision_v1_authentication_decision_proto_goTypes = nil
	file_m8_platform_riskdecision_v1_authentication_decision_proto_depIdxs = nil
}
