package workspace

import "errors"

var (
	ErrNilWorkspace                = errors.New("workspace is nil")
	ErrEmptyWorkspaceID            = errors.New("workspace id is empty")
	ErrInvalidWorkspaceID          = errors.New("workspace id is invalid")
	ErrInvalidWorkspaceState       = errors.New("workspace state is invalid")
	ErrInvalidStateTransition      = errors.New("workspace state transition is invalid")
	ErrEmptyWorkspaceTime          = errors.New("workspace time is empty")
	ErrInvalidWorkspaceTime        = errors.New("workspace timestamps are inconsistent")
	ErrTimeBeforeLastUpdate        = errors.New("workspace mutation time is before the last update")
	ErrInvalidWorkspaceName        = errors.New("workspace name is not valid UTF-8")
	ErrWorkspaceNameTooLong        = errors.New("workspace name is too long")
	ErrInvalidWorkspaceDescription = errors.New("workspace description is not valid UTF-8")
	ErrWorkspaceDescriptionTooLong = errors.New("workspace description is too long")
	ErrInvalidWorkspaceLabel       = errors.New("workspace label is not valid UTF-8")
	ErrInvalidWorkspaceVersion     = errors.New("workspace version is invalid")
	ErrVersionMismatch             = errors.New("workspace version mismatch")
	ErrVersionOverflow             = errors.New("workspace version overflow")
	ErrNoWorkspaceUpdates          = errors.New("workspace update has no fields")
	ErrWorkspaceDeleted            = errors.New("workspace is deleted")
	ErrWorkspaceAlreadyDeleted     = errors.New("workspace is already deleted")
	ErrWorkspaceNotDeleted         = errors.New("workspace is not deleted")
	ErrDeleteTimeRequired          = errors.New("workspace delete time is required")
	ErrPurgeTimeRequired           = errors.New("workspace purge time is required")
	ErrInvalidPurgeTime            = errors.New("workspace purge time must be after delete time")
	ErrPurgeTimePassed             = errors.New("workspace purge time has passed")
	ErrUnexpectedDeletionTimes     = errors.New("non-deleted workspace has deletion timestamps")
)
