apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: m8-resource-manager
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: m8-resource-manager
      app.kubernetes.io/component: api
