// @generated by protoc-gen-es v2.11.0
// @generated from file m8/platform/type/v1/phone_number.proto (package m8.platform.type.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../../buf/validate/validate_pb";
import { file_google_api_field_behavior } from "../../../../google/api/field_behavior_pb";

/**
 * Describes the file m8/platform/type/v1/phone_number.proto.
 */
export const file_m8_platform_type_v1_phone_number = /*@__PURE__*/
  fileDesc("CiZtOC9wbGF0Zm9ybS90eXBlL3YxL3Bob25lX251bWJlci5wcm90bxITbTgucGxhdGZvcm0udHlwZS52MSI4CgtQaG9uZU51bWJlchIpCgRlMTY0GAEgASgJQhvgQQK6SBVyEzIRXlwrWzEtOV1cZHsxLDE0fSRCO1o5Z2l0aHViLmNvbS9tOC10ZWFtL2dvLWdlbnByb3RvL204L3BsYXRmb3JtL3R5cGUvdjE7dHlwZXBiYgZwcm90bzM", [file_buf_validate_validate, file_google_api_field_behavior]);

/**
 * Describes the message m8.platform.type.v1.PhoneNumber.
 * Use `create(PhoneNumberSchema)` to create a new message.
 */
export const PhoneNumberSchema = /*@__PURE__*/
  messageDesc(file_m8_platform_type_v1_phone_number, 0);

